import { expect, it } from 'vitest';
import { ProjectHistory, stateRevision } from './project-history';
import { createScreenplay, insertScene, updateScene } from './screenplay';
import { migrateStory } from './story';
import type { ProjectWorkspace } from '../shared/models';
import type { HistoryPort } from '../shared/project-history';
function setup() { const doc = createScreenplay({ projectId: 'p', title: 'Script', screenplayType: 'feature' }); let workspace = { project: { schemaVersion: 3, id: 'p', title: 'Project', projectType: 'feature', documentFormat: 'screenplay', metadata: { description: '' }, screenplayId: doc.id, createdAt: doc.createdAt, updatedAt: doc.updatedAt }, screenplays: [doc], story: migrateStory(null, 'p') } as ProjectWorkspace; const data = new Map<string, unknown>(), actor = { id: 'writer', deviceId: 'device', displayName: 'Bob', color: '#f00' }; const port: HistoryPort = { read: async (key, fallback) => structuredClone(data.has(key) ? data.get(key) : fallback) as any, write: async (key, value) => { data.set(key, structuredClone(value)); }, workspace: async () => structuredClone(workspace), apply: async (scope, value) => { workspace = scope === 'project' ? value as ProjectWorkspace : scope === 'story' ? { ...workspace, story: value as any } : { ...workspace, screenplays: workspace.screenplays.map(d => d.id === (value as any).id ? value as any : d) }; } }; const history = new ProjectHistory(port, actor, 'p'); return { history, data, port, doc, actor, get: () => workspace, set: (w: ProjectWorkspace) => { workspace = w; } }; }
it('keeps repeated autosaves in one durable Scene session, with stable element anchors and no unchanged session', async () => { const v = setup(), id = v.doc.scenes[0].id; const change = (text: string) => updateScene(v.doc, id, s => ({ ...s, elements: s.elements.map((e, i) => i === 1 ? { ...e, content: text } : e) })); const a = change('First'), b = change('Final dialogue'); await v.history.screenplay(v.doc, a); await v.history.screenplay(a, b); expect((await v.history.query({ sceneId: id })).entries).toHaveLength(1); const restarted = new ProjectHistory(v.port, v.actor, 'p'); await restarted.request({ action: 'finish', screenplayId: v.doc.id }); const page = await restarted.query({ sceneId: id }); expect(page.entries).toHaveLength(1); expect(page.entries[0].targets[0].sceneId).toBe(id); expect(page.entries[0].targets[0].elementId).toBe(v.doc.scenes[0].elements[1].id); await restarted.screenplay(b, b); await restarted.request({ action: 'finish' }); expect((await restarted.query({})).entries).toHaveLength(1); });
it('does not retain a session when Undo returns to its original content', async () => { const v = setup(), before = v.doc, after = updateScene(before, before.scenes[0].id, s => ({ ...s, elements: s.elements.map((e, i) => i === 1 ? { ...e, content: 'Temporary' } : e) })); await v.history.screenplay(before, after); await v.history.screenplay(after, { ...before, scenes: before.scenes.map(s => ({ ...s, updatedAt: new Date().toISOString() })) }); await v.history.request({ action: 'finish' }); expect((await v.history.query({})).entries).toEqual([]); });
it('restores deleted Scenes by stable ID and records the state immediately before restoration', async () => { const v = setup(); const added = insertScene(v.doc); v.set({ ...v.get(), screenplays: [added] }); await v.history.screenplay(v.doc, added); const entry = (await v.history.query({})).entries[0]; const result = await v.history.request({ action: 'restore', id: entry.id }); expect(result.workspace!.screenplays[0].scenes).toHaveLength(1); const restoredEntry = (await v.history.query({})).entries.find(e => e.operation === 'restored')!; await v.history.request({ action: 'restore', id: restoredEntry.id }); expect(v.get().screenplays[0].scenes).toHaveLength(2); expect((await v.history.query({})).total).toBe(3); });
it('clears a screenplay into a recoverable baseline and protects versions independently', async () => { const v = setup(); const changed = insertScene(v.doc); v.set({ ...v.get(), screenplays: [changed] }); await v.history.screenplay(v.doc, changed); await v.history.request({ action: 'createVersion', name: 'First Draft' }); await v.history.request({ action: 'clear', screenplayId: v.doc.id }); let page = await v.history.query({}); expect(page.entries).toEqual([]); expect(page.versions.map(v => v.name)).toEqual(['First Draft', 'Before History Cleared']); expect((await v.history.query({ recentlyCleared: true })).entries).toHaveLength(1); await v.history.request({ action: 'recoverCleared', id: page.cleared[0].id }); page = await v.history.query({}); expect(page.entries).toHaveLength(1); expect(page.versions).toHaveLength(2); });
it('records canonical Story object deletion and restores its links without erasing later history', async () => { const v = setup(), before = v.get().story!; const added = { ...before, characters: [{ id: 'person', name: 'Alice', description: '' }] }; v.set({ ...v.get(), story: added }); await v.history.story(before, added); await v.history.story(added, before); v.set({ ...v.get(), story: before }); const deleted = (await v.history.query({ objectId: 'person' })).entries.find(e => e.label.startsWith('Deleted'))!; await v.history.request({ action: 'restore', id: deleted.id }); expect(v.get().story!.characters[0].id).toBe('person'); expect((await v.history.query({})).total).toBe(3); });
it('protects shared clearing permissions, stable attribution and the pre-collaboration checkpoint', async () => { const v = setup(); await v.history.request({ action: 'collaborator', value: { id: 'editor', displayName: 'Jimmy', role: 'editor', color: '#00f' } }); expect((await v.history.query({})).versions[0].name).toBe('Before Collaboration'); const editor = new ProjectHistory(v.port, { id: 'editor', deviceId: 'd2', displayName: 'James', color: '#00f' }, 'p'); await expect(editor.request({ action: 'clear', screenplayId: v.doc.id })).rejects.toThrow('owner'); expect((await editor.query({})).collaborators.find(c => c.id === 'editor')?.id).toBe('editor'); });
it('detects changes deterministically without depending on projected transport revision fields', async () => { const v = setup(); expect(await stateRevision(v.doc)).toBe(await stateRevision({ ...v.doc, storageRevision: 'transport-only' })); expect(await stateRevision(v.doc)).not.toBe(await stateRevision({ ...v.doc, title: 'Changed' })); });
it('preserves later current content when restoring an earlier Scene session and reversing that restore', async () => { const v = setup(), id = v.doc.scenes[0].id; const change = (text: string) => updateScene(v.doc, id, s => ({ ...s, elements: s.elements.map((e, i) => i === 1 ? { ...e, content: text } : e) })); const first = change('First edit'), later = change('Later work'); v.set({ ...v.get(), screenplays: [first] }); await v.history.screenplay(v.doc, first); await v.history.request({ action: 'finish' }); const original = (await v.history.query({ sceneId: id })).entries[0]; v.set({ ...v.get(), screenplays: [later] }); await v.history.screenplay(first, later); await v.history.request({ action: 'finish' }); await v.history.request({ action: 'restore', id: original.id }); expect(v.get().screenplays[0].scenes[0].elements[1].content).toBe(''); const restored = (await v.history.query({})).entries.find(e => e.operation === 'restored')!; await v.history.request({ action: 'restore', id: restored.id }); expect(v.get().screenplays[0].scenes[0].elements[1].content).toBe('Later work'); });
it('finds a viewed Scene on a later summary page without loading change payloads', async () => {
    const v = setup();
    for (let i = 0; i < 55; i++) {
        const before = v.get().story!, after = { ...before, events: [...before.events, { id: 'event-' + i, name: 'Event ' + i, description: '', occursInSceneId: i === 0 ? v.doc.scenes[0].id : undefined }] };
        v.set({ ...v.get(), story: after });
        await v.history.story(before, after);
    }
    const page = await v.history.query({ anchorSceneId: v.doc.scenes[0].id });
    expect(page.offset).toBe(50);
    expect(page.entries.some(e => e.targets.some(t => t.sceneId === v.doc.scenes[0].id))).toBe(true);
    expect(page.entries.some(e => 'patches' in e)).toBe(false);
});
it('clears one Scene without hiding the other targets of a shared structural change', async () => { const v = setup(), doc = insertScene(v.doc), before = v.get().story!, first = doc.scenes[0].id, second = doc.scenes[1].id; v.set({ ...v.get(), screenplays: [doc] }); const after = { ...before, scenes: [{ sceneId: first, screenplayId: doc.id, notes: 'First' }, { sceneId: second, screenplayId: doc.id, notes: 'Second' }] }; v.set({ ...v.get(), story: after }); await v.history.story(before, after); await v.history.request({ action: 'clear', screenplayId: doc.id, sceneId: first }); expect((await v.history.query({ sceneId: first })).entries).toHaveLength(0); expect((await v.history.query({ sceneId: second })).entries).toHaveLength(1); expect((await v.history.query({ sceneId: first, recentlyCleared: true })).entries).toHaveLength(1); const baseline = (await v.history.query({})).cleared[0]; await v.history.request({ action: 'recoverCleared', id: baseline.id }); expect((await v.history.query({ sceneId: first })).entries).toHaveLength(1); });

it('establishes a screenplay baseline for global Story changes without clearing another screenplay view',async()=>{const v=setup(),before=v.get().story!,after={...before,characters:[{id:'c',name:'Alice',description:''}]};v.set({...v.get(),story:after});await v.history.story(before,after);await v.history.request({action:'clear',screenplayId:v.doc.id});expect((await v.history.query({screenplayId:v.doc.id})).entries).toHaveLength(0);expect((await v.history.query({screenplayId:'other-screenplay'})).entries).toHaveLength(1);expect((await v.history.query({screenplayId:v.doc.id,recentlyCleared:true})).entries).toHaveLength(1);});
