// @vitest-environment jsdom
import { describe, expect, it } from 'vitest';
import { EditorState, AllSelection, TextSelection } from 'prosemirror-state';
import { history, undo } from 'prosemirror-history';
import { createScreenplay, createElement, insertScene, validateScreenplay } from './screenplay';
import { screenplayToContinuousDocument, continuousDocumentToScreenplay } from './continuous-document';
import { copyScreenplaySelection, pasteScreenplaySelection, pastePlainText, cutScreenplaySelection } from './clipboard-commands';
import { importClipboard, encodeClipboard, type ScreenplayClipboard } from './screenplay-clipboard';
import { professionalLayout } from '../shared/screenplay-layout';
const sceneText='INT. GARAGE - NIGHT\n\nA light flickers.\n\n    MARA\n    Stay here.\n    (quietly)\n    Please.\n\nCUT TO:\n\nEXT. ROAD - DAY\n\nRain falls.';
function fixture(){const record=createScreenplay({projectId:'p',title:'Clipboard',screenplayType:'feature'});record.scenes[0].elements=[createElement('action','Before after',0)];return record;}
function stateFor(record=fixture()){return EditorState.create({doc:screenplayToContinuousDocument(record),plugins:[history()]});}
function select(state:EditorState,from:number,to=from){return state.apply(state.tr.setSelection(TextSelection.create(state.doc,from,to)));}
function roundtrip(state:EditorState,record=fixture()){return continuousDocumentToScreenplay(record,state.doc,record.scenes.map(s=>s.id));}
describe('screenplay clipboard',()=>{
 it('infers multiple scenes and contextual dialogue from plain text',()=>{const result=importClipboard({text:sceneText});expect(result.scenes).toHaveLength(2);expect(result.scenes[0].elements.map(e=>e.type)).toEqual(['scene_heading','action','character','dialogue','parenthetical','dialogue','transition']);});
 it('recovers rich HTML semantics and inline emphasis without source page geometry',()=>{const result=importClipboard({text:'fallback',html:'<p>INT. GARAGE - NIGHT</p><p>A <b>bright</b> light.</p><p style="margin-left:180px">MARA</p><p><i>Stay</i> <u>here.</u></p><p>(quietly)</p><p>Please.</p>'});expect(result.scenes[0].elements.map(e=>e.type)).toEqual(['scene_heading','action','character','dialogue','parenthetical','dialogue']);expect(result.scenes[0].elements[1].formatting).toEqual([{start:2,end:8,bold:true}]);expect(result.scenes[0].elements[3].formatting).toEqual([{start:0,end:4,italic:true},{start:5,end:10,underline:true}]);});
 it('preserves ambiguous uppercase prose and unknown rich types',()=>{const result=importClipboard({text:'THE DOOR SLAMS.\n\nSomeone runs.',html:'<p data-type="Unknown">THE DOOR SLAMS.</p><p>Someone runs.</p>'});expect(result.scenes[0].elements[0]).toMatchObject({type:'action',content:'THE DOOR SLAMS.'});});
 it('prioritizes valid private structure; falls back on invalid data',()=>{const structured:ScreenplayClipboard={version:1,inline:false,scenes:[{elements:[{type:'character',content:'lowercase'},{type:'dialogue',content:'UPPERCASE'}]}]};expect(importClipboard({text:'Other',structured:JSON.stringify(structured)})).toEqual(structured);expect(importClipboard({text:'Saved text',structured:'{"version":500}'}).scenes[0].elements[0].content).toBe('Saved text');});
 it('recognizes FDX clipboard XML and preserves supported styling',()=>{const result=importClipboard({text:'<FinalDraft><Content><Paragraph Type="Scene Heading"><Text>INT. LAB - DAY</Text></Paragraph><Paragraph Type="Action"><Text Style="Bold+Italic">A pulse.</Text></Paragraph></Content></FinalDraft>'});expect(result.scenes[0].elements[1]).toMatchObject({type:'action',content:'A pulse.',formatting:[{start:0,end:8,bold:true,italic:true,underline:false}]});});
 it('exports only screenplay semantics as private data, styled HTML, and indented text',()=>{const payload=importClipboard({text:sceneText});const data=encodeClipboard(payload,professionalLayout('letter'));expect(data.text).toMatch(/\n +MARA/);expect(data.html).toContain('data-screenplay-type="character"');expect(data.html).not.toMatch(/scene-toolbar|pagination-boundary|MORE/);expect(importClipboard({text:data.text,html:data.html})).toEqual(payload);});
 it('pastes multiple scenes at the cursor, preserving prefix/suffix and unique IDs',()=>{const record=fixture();let state=select(stateFor(record),9);const originalId=record.scenes[0].elements[0].id;state=state.apply(pasteScreenplaySelection(state,importClipboard({text:sceneText}))!);const next=roundtrip(state,record);expect(validateScreenplay(next)).toEqual([]);expect(next.scenes.flatMap(s=>s.elements).map(e=>e.content).join('|')).toContain('Before ');expect(next.scenes.flatMap(s=>s.elements).map(e=>e.content).join('|')).toContain('after');expect(next.scenes.some(s=>s.elements.some(e=>e.id===originalId))).toBe(true);expect(next.scenes.filter(s=>s.elements[0].type==='scene_heading')).toHaveLength(2);});
 it('undoes an entire multiple-scene paste in one operation',()=>{const record=fixture();let state=select(stateFor(record),9);const before=state.doc.toJSON();state=state.apply(pasteScreenplaySelection(state,importClipboard({text:sceneText}))!);expect(undo(state,tr=>{state=state.apply(tr);})).toBe(true);expect(state.doc.toJSON()).toEqual(before);});
 it('replaces only a partial selection and pastes plain text without marks or inference',()=>{const record=fixture();let state=select(stateFor(record),2,8);state=state.apply(pastePlainText(state,'INT. PLAIN\nWords'));expect(roundtrip(state,record).scenes[0].elements[0]).toMatchObject({type:'action',content:'INT. PLAIN\nWords after'});});
 it('copies and pastes partial formatted text into the current element',()=>{const record=fixture();record.scenes[0].elements[0].formatting=[{start:0,end:6,bold:true}];let source=select(stateFor(record),3,6);const copy=copyScreenplaySelection(source);expect(copy.inline).toBe(true);expect(copy.scenes[0].elements[0]).toMatchObject({content:'efo',formatting:[{start:0,end:3,bold:true}]});let destination=select(stateFor(record),14);destination=destination.apply(pasteScreenplaySelection(destination,copy)!);expect(roundtrip(destination,record).scenes[0].elements[0].content).toBe('Before afterefo');});
 it('roundtrips full selections, alignment, and soft breaks without carrying IDs',()=>{const record=insertScene(fixture());record.scenes[0].elements[0]={...record.scenes[0].elements[0],content:'One\nTwo',alignment:'center',formatting:[{start:0,end:3,italic:true,underline:true}]};let state=stateFor(record);state=state.apply(state.tr.setSelection(new AllSelection(state.doc)));const copy=copyScreenplaySelection(state);const data=encodeClipboard(copy,professionalLayout('a4'));expect(data.structured).not.toContain(record.scenes[0].elements[0].id);const target=fixture();let dest=stateFor(target);dest=dest.apply(dest.tr.setSelection(new AllSelection(dest.doc)));dest=dest.apply(pasteScreenplaySelection(dest,importClipboard(data))!);const next=roundtrip(dest,target);expect(next.scenes).toHaveLength(2);expect(next.scenes[0].elements[0]).toMatchObject({content:'One\nTwo',alignment:'center',formatting:[{start:0,end:3,italic:true,underline:true}]});expect(validateScreenplay(next)).toEqual([]);});
 it('does not delete unprojected scenes when pasting in Scene Mode',()=>{const record=insertScene(fixture());const hidden=structuredClone(record.scenes[1]);let state=EditorState.create({doc:screenplayToContinuousDocument(record,record.scenes[0].id)});state=select(state,9);state=state.apply(pasteScreenplaySelection(state,importClipboard({text:sceneText}))!);const next=continuousDocumentToScreenplay(record,state.doc,[record.scenes[0].id]);expect(next.scenes.find(s=>s.id===hidden.id)?.elements).toEqual(hidden.elements);expect(next.scenes.length).toBeGreaterThan(2);});
 it('cuts an entire selection into a valid editable document',()=>{const record=fixture();let state=stateFor(record);state=state.apply(state.tr.setSelection(new AllSelection(state.doc)));state=state.apply(cutScreenplaySelection(state));expect(validateScreenplay(roundtrip(state,record))).toEqual([]);});
});

it('preserves a Character → Dialogue → Parenthetical → Dialogue selection and fresh dialogue group IDs', () => {
 const record=fixture();record.scenes[0].elements=[createElement('character','MARA',0),createElement('dialogue','Wait.',1),{...createElement('parenthetical','(quietly)',2),formatting:[{start:1,end:8,italic:true}],alignment:'center'},createElement('dialogue','Please.',3)];
 let source=stateFor(record);source=source.apply(source.tr.setSelection(new AllSelection(source.doc)));
 const payload=copyScreenplaySelection(source);for(const data of [{structured:JSON.stringify(payload),text:''},encodeClipboard(payload,professionalLayout('letter'))]){
  let target=stateFor(fixture());target=target.apply(target.tr.setSelection(new AllSelection(target.doc)));target=target.apply(pasteScreenplaySelection(target,importClipboard(data))!);
  const recopied=copyScreenplaySelection(target.apply(target.tr.setSelection(new AllSelection(target.doc))));expect(recopied.scenes[0].elements).toEqual(payload.scenes[0].elements);
 }
 const plain=encodeClipboard(payload,professionalLayout('letter')).text;expect(importClipboard({text:plain}).scenes[0].elements.map(e=>e.type)).toEqual(['character','dialogue','parenthetical','dialogue']);
 const line=plain.split('\n').find(line=>line.includes('(quietly)'))!;const dialogue=plain.split('\n').find(line=>line.includes('Wait.'))!;expect(line.indexOf('(')).toBeGreaterThan(dialogue.indexOf('W'));
});
it('recognizes a standalone parenthetical and preserves its brackets',()=>{const imported=importClipboard({text:'    (under her breath)'});expect(imported.inline).toBe(false);expect(imported.scenes[0].elements[0]).toEqual({type:'parenthetical',content:'(under her breath)'});});
it('keeps wrapped parentheticals together when copied through plain text',()=>{
 const payload:ScreenplayClipboard={version:1,inline:false,scenes:[{elements:[{type:'character',content:'MARA'},{type:'parenthetical',content:'(quietly, watching the door and waiting for the footsteps in the corridor to fade)'},{type:'dialogue',content:'We can go.'}]}]};
 const data=encodeClipboard(payload,professionalLayout('letter'));const elements=importClipboard({text:data.text}).scenes[0].elements;
 expect(elements.map(element=>element.type)).toEqual(['character','parenthetical','dialogue']);
 expect(elements[1].content.replace(/\s+/g,' ')).toBe(payload.scenes[0].elements[1].content);
 const html=data.html!.replace(/ data-screenplay-clipboard="[^"]*"/,'');
 expect(importClipboard({text:'',html}).scenes[0].elements[1]).toMatchObject(payload.scenes[0].elements[1]);
});
it('honors rich-text normal-weight wrappers and stylesheet emphasis',()=>{const result=importClipboard({text:'',html:'<style>.spoken{font-style:italic} .strong{font-weight:bold}</style><b style="font-weight:normal"><p>INT. ROOM - DAY</p><p class="strong">A light.</p><p>MARA</p><p class="spoken">(quietly)</p><p>Wait.</p></b>'});expect(result.scenes[0].elements[1].formatting).toEqual([{start:0,end:8,bold:true}]);expect(result.scenes[0].elements[3]).toMatchObject({type:'parenthetical',formatting:[{start:0,end:9,italic:true}]});expect(result.scenes[0].elements[4].formatting).toBeUndefined();});
it('makes plain-text replacement of the whole document valid and undoable',()=>{const record=fixture();let state=stateFor(record);state=state.apply(state.tr.setSelection(new AllSelection(state.doc)));const before=state.doc;state=state.apply(pastePlainText(state,'plain\ntext'));expect(validateScreenplay(roundtrip(state,record))).toEqual([]);undo(state,tr=>state=state.apply(tr));expect(state.doc.eq(before)).toBe(true);});
it('preserves prose outside nested HTML blocks and unknown numerical content',()=>{const result=importClipboard({text:'',html:'<div>Before<p>Inside</p>After</div><p>1984.</p>'});expect(result.scenes[0].elements.map(e=>e.content)).toEqual(['Before','Inside','After','1984.']);expect(importClipboard({text:'1984.'}).scenes[0].elements[0].content).toBe('1984.');});
it('ignores identified external pagination but retains screenplay text',()=>{const result=importClipboard({text:'',html:'<div class="page-header">DRAFT</div><p>INT. ROOM - DAY</p><div class="page-number">12.</div><p>Action.</p>'});expect(result.scenes[0].elements.map(e=>e.content)).toEqual(['INT. ROOM - DAY','Action.']);});
it('remaps complete dual-dialogue groups and makes partial groups safe standalone elements',()=>{
 const record=fixture();record.scenes[0].elements=(['left','right'] as const).flatMap((side,i)=>[{...createElement('character',side,2*i),dualDialogue:{groupId:'old-group',side,role:'character' as const}},{...createElement('dialogue','Words.',2*i+1),dualDialogue:{groupId:'old-group',side,role:'dialogue' as const}}]);
 let source=stateFor(record);source=source.apply(source.tr.setSelection(new AllSelection(source.doc)));const payload=copyScreenplaySelection(source);const dest=fixture();let target=stateFor(dest);target=target.apply(target.tr.setSelection(new AllSelection(target.doc)));target=target.apply(pasteScreenplaySelection(target,payload)!);const pasted=roundtrip(target,dest);expect(validateScreenplay(pasted)).toEqual([]);expect(pasted.scenes[0].elements[0].dualDialogue?.groupId).not.toBe('old-group');
 payload.scenes[0].elements=payload.scenes[0].elements.slice(0,2);target=stateFor(dest);target=target.apply(target.tr.setSelection(new AllSelection(target.doc)));target=target.apply(pasteScreenplaySelection(target,payload)!);const partial=roundtrip(target,dest);expect(validateScreenplay(partial)).toEqual([]);expect(partial.scenes[0].elements[0].type).toBe('character');expect(partial.scenes[0].elements[0].dualDialogue).toBeUndefined();
});
