import {expect,it} from 'vitest';
import {captureSource,contextualActions,screenplayContext} from './screenplay-context';
import {deleteStoryEntity,migrateStory} from './story';
import {mergeIdentity,separateIdentity} from './story-identities';
import {createWorld} from './worlds';
import {applyCaptureRelationships} from './capture-relationships';
import type {ScreenplayRecord} from '../shared/models';
import type {WorldLinkContext} from '../shared/worlds';
const documents=[{id:'d',title:'Pilot',scenes:[{id:'s',elements:[{id:'h',type:'scene_heading',content:'INT. OFFICE - AFTERNOON'},{id:'cue',type:'character',content:'APPLE'},{id:'line',type:'dialogue',content:'Gates has transferred to Edinburgh.'}]}]}] as ScreenplayRecord[];
const context:WorldLinkContext={screenplayId:'d',sceneId:'s',elementId:'line',type:'dialogue',selectedText:'Gates has transferred to Edinburgh.',from:{elementId:'line',offset:0},to:{elementId:'line',offset:34},x:0,y:0};
function fixture(){const story=migrateStory(null,'p');story.characters=[{id:'apple',name:'Apple Lennox',sourceNames:['APPLE'],description:''},{id:'gates',name:'DI Gates',sourceNames:['Gates'],description:''}];story.locations=[{id:'office',name:'Office',description:'',sourceElementIds:['h']}];story.scenes=[{sceneId:'s',screenplayId:'d',locationId:'office',chronology:{day:7,time:'14:30'}}];story.worlds=[createWorld('Universe')];return story;}
it('restricts each menu and allows a recognised entity to override generic actions',()=>{
 expect(contextualActions('character','apple')).toEqual(['membership','character','object','rule','note']);expect(contextualActions('dialogue')).not.toContain('object');expect(contextualActions('dialogue')).not.toContain('membership');expect(contextualActions('scene_heading')).toEqual(['location','note','rule']);expect(contextualActions('transition')).toEqual(['note']);expect(contextualActions('dialogue',undefined,{kind:'vehicle',id:'car'})).toEqual(['object','note']);
});
it('distinguishes the Dialogue speaker from the explicitly named subject',()=>{const result=screenplayContext(fixture(),documents,context);expect(result.speakerId).toBe('apple');expect(result.characterId).toBe('gates');expect(result.characterIds).toEqual(['gates']);expect(result.locationId).toBe('office');});
it('recognises the speaker by the preceding cue identity even after a name change',()=>{const story=fixture();story.characters[0]={id:'apple',name:'New name',description:'',sourceElementIds:['cue']};const result=screenplayContext(story,documents,context);expect(result.speakerId).toBe('apple');expect(result.characterId).toBe('gates');});
it('recognises one explicitly named World entity and leaves ambiguous matches for the writer',()=>{const story=fixture();story.worlds![0].entities=[{id:'car',kind:'vehicle',name:'Apple’s Volvo',description:''}];expect(screenplayContext(story,documents,{...context,selectedText:'Apple’s Volvo waits outside.'}).recognised).toMatchObject({entity:{kind:'vehicle',id:'car'}});const other=createWorld('Other');other.entities=[{id:'other-car',kind:'vehicle',name:'Apple’s Volvo',description:''}];story.worlds!.push(other);expect(screenplayContext(story,documents,{...context,selectedText:'Apple’s Volvo waits outside.'}).recognised).toBeUndefined();});
it('round-trips source speaker, location, chronology, record ID and original text independently of the fictional subject',()=>{const story=fixture();const next=captureSource(story,context,{kind:'character',id:'gates'},undefined,documents,{recordId:'appearance'});const restored=migrateStory(JSON.parse(JSON.stringify(next)),'p');expect(restored.worldOccurrences![0]).toMatchObject({entity:{kind:'character',id:'gates'},selectedText:context.selectedText,source:{speakerId:'apple',characterIds:['gates'],locationId:'office',chronology:{day:7,time:'14:30'},recordId:'appearance'}});expect(restored.worlds![0].relationships).toEqual([]);});
it('preserves source attribution through merge/separation and clears deleted identities',()=>{let story=fixture();story.characters.push({id:'alias',name:'Apple',description:'',sourceNames:['APPLE ALIAS']});story=captureSource(story,{...context,selectedText:'',elementId:'line'}, {kind:'lore',id:'phrase'},undefined,documents,{speakerId:'alias',characterIds:['alias']});const merged=mergeIdentity(story,'characters','alias','apple');expect(merged.worldOccurrences![0].source).toMatchObject({speakerId:'apple',characterIds:['apple']});const separated=separateIdentity(merged,'characters','apple','Apple',documents);expect(separated.worldOccurrences![0].source).toMatchObject({speakerId:'alias',characterIds:['alias']});const deleted=deleteStoryEntity(separated,'characters','alias');expect(deleted.worldOccurrences![0].source!.speakerId).toBeUndefined();expect(deleted.worldOccurrences![0].source!.characterIds).toEqual([]);});
it('stores Character assignments on one shared relationship and never invents acquisition or Scene ownership',()=>{const story=fixture(),world=story.worlds![0];world.entities=[{id:'car',kind:'vehicle',name:'Car',description:''}];const draft={id:'r',target:{kind:'character' as const,id:'apple'},type:'owned by',primary:true};let next=applyCaptureRelationships(story,world.id,{kind:'vehicle',id:'car'},[draft]);next=applyCaptureRelationships(next,world.id,{kind:'vehicle',id:'car'},[draft]);expect(next.worlds![0].relationships).toHaveLength(1);expect(next.worlds![0].relationships[0]).toMatchObject({from:{kind:'vehicle',id:'car'},to:{kind:'character',id:'apple'},type:'owned by'});expect(next.worlds![0].relationships[0].fromPoint).toBeUndefined();expect(next.events).toEqual([]);expect(()=>applyCaptureRelationships(story,world.id,{kind:'vehicle',id:'car'},[{...draft,type:''}])).toThrow('Choose an entry');expect(story.worlds![0].relationships).toEqual([]);});
it('uses canonical Event participants without a World and keeps speaker attribution out of involvement',()=>{const story=fixture();story.events=[{id:'event',name:'Transfer',description:''}];const next=applyCaptureRelationships(story,undefined,{kind:'event',id:'event'},[{id:'r',target:{kind:'character',id:'gates'},type:'involved'}]);expect(next.events[0].participantIds).toEqual(['gates']);expect(next.worlds![0].relationships).toEqual([]);});
it('changes ownership from an explicit story point while preserving earlier ownership and unrelated uses',()=>{const story=fixture(),world=story.worlds![0];world.entities=[{id:'car',kind:'vehicle',name:'Car',description:''}];world.relationships=[{id:'owner',from:{kind:'vehicle',id:'car'},to:{kind:'character',id:'apple'},type:'owned by',fromPoint:{chronology:{day:1}}},{id:'driver',from:{kind:'vehicle',id:'car'},to:{kind:'character',id:'apple'},type:'driven by'}];const point={chronology:{day:7}};const next=applyCaptureRelationships(story,world.id,{kind:'vehicle',id:'car'},[{id:'next-owner',target:{kind:'character',id:'gates'},type:'owned by'}],point,undefined,{documents});expect(next.worlds![0].relationships[0].untilPoint).toEqual(point);expect(next.worlds![0].relationships[1].untilPoint).toBeUndefined();expect(next.worlds![0].relationships[2].fromPoint).toEqual(point);expect(story.worlds![0].relationships[0].untilPoint).toBeUndefined();});

it('does not preselect uncertain shared Character aliases for Rule subjects',()=>{const s=fixture();s.characters[0].profile={aliases:['Zider']};s.characters[1].profile={aliases:['Zider']};expect(screenplayContext(s,documents,{...context,selectedText:'Nobody looks Zider in the eyes.'}).characterIds).toEqual([]);});
