import { expect, it } from 'vitest';
import { migrateStory, resolveEvent, chronologyLabel, eventTimingLabel, orderSceneEvents, characterDisplayName } from './story';
import type { StoryEvent } from '../shared/story';
function fixture() { const story=migrateStory(null,'p'); story.scenes=[{sceneId:'s',screenplayId:'d',chronology:{day:14,time:'20:00',endTime:'20:05',duration:5}}]; return story; }
it('inherits live scene time without repeating it on an Event row',()=>{ const story=fixture(); const event:StoryEvent={id:'e',name:'Countdown',description:'',occursInSceneId:'s',contextOverrides:[]}; expect(resolveEvent(story,event).chronology).toMatchObject({day:14,time:'20:00',endTime:'20:05',duration:5}); expect(eventTimingLabel(event)).toBe(''); story.scenes[0].chronology!.time='21:00'; expect(resolveEvent(story,event).chronology?.time).toBe('21:00'); });
it('round-trips overnight occurrence ranges and preserves inherited date',()=>{const story=fixture(); story.events=[{id:'e',name:'Watch',description:'',occursInSceneId:'s',contextOverrides:[],occurrenceTiming:{mode:'range',time:'22:00',endTime:'02:00'}}]; const saved=migrateStory(JSON.parse(JSON.stringify(story)),'p'); expect(chronologyLabel(resolveEvent(saved,saved.events[0]).chronology)).toBe('Day 14 · 22:00–02:00'); expect(eventTimingLabel(saved.events[0])).toBe('22:00–02:00'); });
it('orders explicit times while retaining untimed slots and reference order',()=>{const story=fixture(); const event=(id:string,time?:string):StoryEvent=>({id,name:id,description:'',occursInSceneId:'s',contextOverrides:[],...(time?{occurrenceTiming:{mode:'exact',time}}:{})});const links=[{event:event('late','20:05'),relationship:'occurs' as const},{event:event('untimed'),relationship:'occurs' as const},{event:event('early','20:00'),relationship:'occurs' as const},{event:event('reference','09:00'),relationship:'referenced' as const}];expect(orderSceneEvents(story,links).map(l=>l.event.id)).toEqual(['early','untimed','late','reference']); });
it('supports explicit duration and approximate refinements, then scene inheritance',()=>{const story=fixture();const event:StoryEvent={id:'e',name:'e',description:'',contextOverrides:[],occursInSceneId:'s',occurrenceTiming:{mode:'duration',duration:2.5}};expect(resolveEvent(story,event).chronology?.duration).toBe(2.5);expect(eventTimingLabel(event)).toBe('2.5 min');event.occurrenceTiming={mode:'approximate',timeOfDay:'evening'};expect(eventTimingLabel(event)).toBe('Evening');expect(resolveEvent(story,event).chronology?.time).toBeUndefined();event.occurrenceTiming={mode:'inherit'};expect(eventTimingLabel(event)).toBe('');expect(resolveEvent(story,event).chronology?.time).toBe('20:00'); });
it('uses merge provenance for character names without changing canonical data',()=>{const story=fixture();const character={id:'c',name:'MARSHA',description:''};story.characters=[character];story.identityMerges=[{kind:'characters',targetId:'c',source:{id:'old',name:'SOLICITOR',description:'',sourceNames:['SOLICITOR']},links:[]}];expect(characterDisplayName(story,character)).toBe('MARSHA (SOLICITOR)');expect(character.name).toBe('MARSHA');});
