import { expect, it } from 'vitest';
import { createWorld, copyWorld, packageWorld, validateWorld } from './worlds';
import { migrateStory } from './story';
import { createScreenplay } from './screenplay';
import { createStructures, previewStructures, organisationCategory, structureParents, diagramChildren, setStructureParent, reorderStructures, moveStructures } from './world-structure';
import type { WorldRecord } from '../shared/worlds';

function fixture(){const story=migrateStory(null,'p');const w=createWorld('The Altered');w.entities=[{id:'police',kind:'organisation',name:'Police Scotland',category:'Government / Public',description:''},{id:'scu',kind:'organisation',name:'Specialist Crime Unit',abbreviation:'SCU',description:''}];w.relationships=[{id:'parent',type:'part of',from:{kind:'organisation',id:'scu'},to:{kind:'organisation',id:'police'}}];story.worlds=[w];return {story,w};}
it('reorders selected peers without changing levels or another Organisation',()=>{
 const {story,w}=fixture();let world=createStructures(w,'scu',{type:'Team',names:'Team 1\nTeam 2\nTeam 3',hierarchyLevel:2});world=createStructures(world,'police',{type:'Unit',names:'Unrelated',hierarchyLevel:2});const ids=world.entities.filter(e=>e.organisationId==='scu').map(e=>e.id);const original=world.entities.at(-1)!;const next=reorderStructures(world,[ids[1],ids[2]],-1,story,[]);expect(next.entities.filter(e=>e.organisationId==='scu').sort((a,b)=>a.displayOrder!-b.displayOrder!).map(e=>e.name)).toEqual(['Team 2','Team 3','Team 1']);expect(next.entities.filter(e=>e.organisationId==='scu').every(e=>e.hierarchyLevel===2)).toBe(true);expect(next.entities.at(-1)).toEqual(original);
});
it('moves canonical subtrees while keeping nesting, independent peers, content and personnel history',()=>{
 const {story,w}=fixture();let world=createStructures(w,'scu',{type:'Command',names:'Command',hierarchyLevel:1});const command=world.entities.at(-1)!;world=createStructures(world,'scu',{type:'Team',names:'Team 4',parentId:command.id,hierarchyLevel:2});const team=world.entities.at(-1)!;world=createStructures(world,'scu',{type:'Team',names:'Peer',hierarchyLevel:2});const peer=world.entities.at(-1)!;world.relationships.push({id:'member',type:'member of',from:{kind:'character',id:'apple'},to:{kind:'organisation',id:'scu'},unitId:team.id});const originalMember=world.relationships.at(-1)!;team.description='Keep this note';const next=moveStructures(world,[command.id],'police',story,[],{chronology:{day:5}});expect(next.entities.find(e=>e.id===command.id)!.organisationId).toBe('police');expect(next.entities.find(e=>e.id===team.id)).toMatchObject({organisationId:'police',description:'Keep this note'});expect(next.entities.find(e=>e.id===peer.id)!.organisationId).toBe('scu');expect(next.relationships.find(r=>r.id==='member')).toEqual(originalMember);expect(structureParents(next,story,[],{chronology:{day:3}}).get(command.id)).toEqual([{kind:'organisation',id:'scu'}]);expect(structureParents(next,story,[],{chronology:{day:7}}).get(command.id)).toEqual([{kind:'organisation',id:'police'}]);expect(structureParents(next,story,[],{chronology:{day:7}}).get(team.id)).toEqual([{kind:'structure',id:command.id}]);
});
it('migrates known legacy units and personnel definitions without losing identity, periods, links or pins',()=>{
 const {story,w}=fixture();delete w.structureModelVersion;w.entities.push({id:'team4',kind:'organisation',name:'Team 4',description:'No nuts',organisationRole:'unit'},{id:'dc',kind:'organisation',organisationRole:'rank',name:'Detective Constable',abbreviation:'DC',description:''},{id:'unclear',kind:'organisation',name:'Special Projects',description:''});
 w.relationships.push({id:'unit',type:'part of',from:{kind:'organisation',id:'team4'},to:{kind:'organisation',id:'scu'}},{id:'member',type:'member of',from:{kind:'character',id:'apple'},to:{kind:'organisation',id:'team4'},rankId:'dc',fromPoint:{chronology:{day:1}},untilPoint:{chronology:{day:5}}});
 story.characters=[{id:'apple',name:'Apple',description:''}];story.worldUi={pins:[{worldId:w.id,entity:{kind:'organisation',id:'team4'}}]};story.worldOccurrences=[{id:'o',worldId:w.id,entity:{kind:'organisation',id:'team4'},scope:'scene',sceneId:'s',screenplayId:'d'}];
 const next=migrateStory(story,'p'),world=next.worlds![0];expect(world.entities.find(e=>e.id==='team4')).toMatchObject({kind:'structure',organisationId:'scu',description:'No nuts'});expect(world.entities.find(e=>e.id==='dc')!.kind).toBe('rank');expect(world.entities.find(e=>e.id==='unclear')!.kind).toBe('organisation');expect(world.relationships.find(r=>r.id==='member')).toMatchObject({unitId:'team4',to:{kind:'organisation',id:'scu'},rankId:'dc',fromPoint:{chronology:{day:1}},untilPoint:{chronology:{day:5}}});expect(next.worldUi!.pins[0].entity!.kind).toBe('structure');expect(next.worldOccurrences![0].entity.kind).toBe('structure');expect(migrateStory(next,'p')).toEqual(next);
});
it('preserves ambiguous multi-parent legacy entries as Organisations',()=>{const {story,w}=fixture();delete w.structureModelVersion;w.entities.push({id:'team',kind:'organisation',name:'Team 4',description:''});for(const parent of ['scu','police'])w.relationships.push({id:parent+'-team',type:'part of',from:{kind:'organisation',id:'team'},to:{kind:'organisation',id:parent}});expect(migrateStory(story,'p').worlds![0].entities.find(e=>e.id==='team')!.kind).toBe('organisation');});
it('supports generic list and sequence previews and optional abbreviations',()=>{
 expect(previewStructures({type:'Department',names:'Cardiology\nOncology\n\nNeurology'}).map(e=>e.name)).toEqual(['Cardiology','Oncology','Neurology']);
 expect(previewStructures({type:'Custom',sequence:true,prefix:'Deck',from:1,to:12})).toHaveLength(12);
 expect(previewStructures({type:'Team',sequence:true,prefix:'Team',from:1,to:5,abbreviationPattern:'T{n}'}).at(-1)).toEqual({name:'Team 5',abbreviation:'T5'});
 expect(()=>previewStructures({type:'Unit',sequence:true,prefix:'Unit',from:4,to:1})).toThrow('valid');expect(()=>previewStructures({type:'Unit',names:'A\na'})).toThrow('duplicate');
});
it('creates independent units, inherits categories and remaps ownership and assignments on copy',()=>{
 const {story,w}=fixture();const world=createStructures(w,'scu',{type:'Team',sequence:true,prefix:'Team',from:1,to:5,hierarchyLevel:2});story.worlds=[world];expect(organisationCategory(world,'scu',story,[])).toBe('Government / Public');expect(organisationCategory(world,world.entities[2].id,story,[])).toBe('Government / Public');world.entities[1].category='Private / Commercial';expect(organisationCategory(world,world.entities[2].id,story,[])).toBe('Private / Commercial');world.entities[2].description='Only Team 1';expect(world.entities[3].description).toBe('');
 story.characters=[{id:'apple',name:'Apple',description:''}];world.characterIds=['apple'];world.relationships.push({id:'m',type:'member of',from:{kind:'character',id:'apple'},to:{kind:'organisation',id:'scu'},unitId:world.entities[2].id});const copied=copyWorld(packageWorld(world,story),migrateStory(null,'target')),copy=copied.worlds![0];const owner=copy.entities.find(e=>e.name==='Specialist Crime Unit')!;expect(copy.entities.find(e=>e.name==='Team 1')!.organisationId).toBe(owner.id);expect(copy.relationships.find(r=>r.id===copy.provenance!.identityMap.m)!.unitId).toBe(copy.entities.find(e=>e.name==='Team 1')!.id);
});
it('uses explicit parents before level projections, preserves peers/order and rejects cycles',()=>{
 const {story,w}=fixture();let world=createStructures(w,'scu',{type:'Command',names:'Command',hierarchyLevel:1});const command=world.entities.at(-1)!;world=createStructures(world,'scu',{type:'Team',names:'Team 1\nTeam 2',hierarchyLevel:2});const [a,b]=world.entities.slice(-2);expect(structureParents(world,story,[]).get(a.id)).toEqual([{kind:'structure',id:command.id}]);
 world=setStructureParent(world,[b.id],a.id);expect(structureParents(world,story,[]).get(b.id)).toEqual([{kind:'structure',id:a.id}]);expect(()=>validateWorld(setStructureParent(world,[a.id],b.id),story)).toThrow('Circular');
 expect(diagramChildren(world,story,[],undefined,{kind:'structure',id:command.id}).map(e=>e.ref.id)).toEqual([a.id]);expect(a.hierarchyLevel).toBe(b.hierarchyLevel);expect(a.displayOrder).not.toBe(b.displayOrder);
});
it('projects episode membership and personnel reporting without diagram role nodes or moving linked objects',()=>{
 const {story,w}=fixture();const docs=Array.from({length:7},(_,i)=>createScreenplay({projectId:'p',title:'Episode '+(i+1),screenplayType:'episode'}));const world=createStructures(w,'scu',{type:'Team',names:'Team 4\nTeam 5'});const [t4,t5]=world.entities.slice(-2);world.entities.push({id:'dc',kind:'rank',name:'Detective Constable',description:''},{id:'bell',kind:'object',name:'Attention Bell',description:''});story.characters=[{id:'apple',name:'Apple',description:''},{id:'gates',name:'Gates',description:''}];world.characterIds=['apple','gates'];world.relationships.push({id:'old',type:'member of',from:{kind:'character',id:'apple'},to:{kind:'organisation',id:'scu'},unitId:t4.id,rankId:'dc',reportsToId:'gates',untilPoint:{screenplayId:docs[4].id}},{id:'new',type:'member of',from:{kind:'character',id:'apple'},to:{kind:'organisation',id:'scu'},unitId:t5.id,rankId:'dc',fromPoint:{screenplayId:docs[4].id}},{id:'manager',type:'member of',from:{kind:'character',id:'gates'},to:{kind:'organisation',id:'scu'},unitId:t4.id},{id:'bell',type:'belongs to',from:{kind:'object',id:'bell'},to:{kind:'structure',id:t4.id}});
 expect(diagramChildren(world,story,docs,{screenplayId:docs[2].id},{kind:'structure',id:t4.id}).map(e=>e.ref.id)).toEqual(['gates','bell']);expect(diagramChildren(world,story,docs,{screenplayId:docs[2].id},{kind:'character',id:'gates'}).map(e=>e.ref.id)).toContain('apple');expect(diagramChildren(world,story,docs,{screenplayId:docs[6].id},{kind:'structure',id:t5.id}).map(e=>e.ref.id)).toContain('apple');expect(diagramChildren(world,story,docs,{screenplayId:docs[6].id},{kind:'structure',id:t4.id}).map(e=>e.ref.id)).toContain('bell');expect(world.entities.filter(e=>e.kind==='organisation')).toHaveLength(2);
});
