import {expect,it} from 'vitest';
import {migrateStory} from './story';
import {createWorld} from './worlds';
import {migrateWorldRecord} from './world-structure';
import {rulesForEntity,saveRule} from './world-rules';
import {worldStateAt} from './world-history';
import type {ScreenplayRecord} from '../shared/models';
const docs=[{id:'pilot',title:'Pilot',scenes:[{id:'s1',elements:[]},{id:'s4',elements:[]}]}] as unknown as ScreenplayRecord[];
function fixture(){const s=migrateStory(null,'project');s.characters=[{id:'zider',name:'Zider',description:''},{id:'apple',name:'Apple',description:''}];s.locations=[{id:'room',name:'Interview Room 2',description:''}];s.scenes=[{sceneId:'s1',screenplayId:'pilot',chronology:{day:1}},{sceneId:'s4',screenplayId:'pilot',chronology:{day:4}}];s.worlds=[createWorld('World')];s.worlds[0].entities=[{id:'scu',name:'SCU',kind:'organisation',description:''},{id:'team',name:'Team 5',kind:'structure',organisationId:'scu',description:''},{id:'phone',kind:'object',name:'Red Phone',description:''},{id:'van',kind:'vehicle',name:'Van',description:''}];return s;}
it('uses one Rule with multiple independent applicability and concern endpoints and no source actor inference',()=>{const s=fixture(),w=s.worlds![0];const next=saveRule(s,docs,w.id,{entity:{id:'rule',kind:'rule',name:'Eye Contact',description:'Do not look into Zider’s eyes.',fields:{Exceptions:'Unless Gates is present'}},period:'always',relationships:[{id:'a',target:{kind:'world',id:w.id},type:'applies to'},{id:'b',target:{kind:'structure',id:'team'},type:'applies to'},{id:'c',target:{kind:'character',id:'zider'},type:'concerns'},{id:'d',target:{kind:'object',id:'phone'},type:'concerns'},{id:'e',target:{kind:'vehicle',id:'van'},type:'concerns'}]});expect(next.worlds![0].entities.filter(e=>e.kind==='rule')).toHaveLength(1);expect(rulesForEntity(next,docs,{kind:'character',id:'zider'})[0]).toMatchObject({link:{type:'concerns'},rule:{fields:{Exceptions:'Unless Gates is present'}}});expect(rulesForEntity(next,docs,{kind:'structure',id:'team'})[0].rule.id).toBe('rule');expect(rulesForEntity(next,docs,{kind:'character',id:'apple'})).toEqual([]);expect(migrateStory(JSON.parse(JSON.stringify(next)),'project').worlds).toEqual(next.worlds);expect(s.worlds![0].relationships).toEqual([]);});
it('dated Rules are inactive before the start and at the end, including canonical Location views',()=>{const s=fixture(),w=s.worlds![0];const next=saveRule(s,docs,w.id,{entity:{id:'rule',kind:'rule',name:'Entry',description:'Zider may not enter.'},period:'custom',from:{sceneId:'s4'},until:{chronology:{day:8}},relationships:[{id:'a',target:{kind:'character',id:'zider'},type:'applies to'},{id:'b',target:{kind:'location',id:'room'},type:'concerns'}]});expect(rulesForEntity(next,docs,{kind:'character',id:'zider'},{sceneId:'s1'})[0].status).toBe('inactive');expect(rulesForEntity(next,docs,{kind:'location',id:'room'},{sceneId:'s4'})[0].status).toBe('active');expect(rulesForEntity(next,docs,{kind:'location',id:'room'},{chronology:{day:8}})[0].status).toBe('inactive');expect(worldStateAt(next.worlds![0].entities.at(-1)!,next,docs,{sceneId:'s1'}).Rule).toBeUndefined();});
it('editing at a later point closes older associations without duplicate IDs or modifying unrelated links',()=>{const s=fixture(),w=s.worlds![0];let next=saveRule(s,docs,w.id,{entity:{id:'rule',kind:'rule',name:'Entry',description:'No entry'},period:'point',from:{sceneId:'s1'},relationships:[{id:'a',target:{kind:'character',id:'zider'},type:'applies to'}]});const rule=next.worlds![0].entities.at(-1)!;next=saveRule(next,docs,w.id,{entity:{...rule,description:'Accompanied entry only'},period:'point',from:{sceneId:'s4'},relationships:[{id:'a',target:{kind:'character',id:'zider'},type:'applies to'}]});const links=next.worlds![0].relationships;expect(links).toHaveLength(2);expect(new Set(links.map(r=>r.id)).size).toBe(2);expect(links[0].untilPoint).toEqual({sceneId:'s4'});expect(worldStateAt(next.worlds![0].entities.at(-1)!,next,docs,{sceneId:'s1'}).Rule).toBe('No entry');});
it('migrates clear assigned legacy links but preserves ambiguous custom meanings and periods',()=>{const w=fixture().worlds![0];w.entities.push({id:'rule',kind:'rule',name:'Rule',description:'Policy'});w.relationships=[{id:'assigned',from:{kind:'rule',id:'rule'},to:{kind:'organisation',id:'scu'},unitId:'team',type:'belongs to',fromPoint:{sceneId:'s1'}},{id:'ambiguous',from:{kind:'rule',id:'rule'},to:{kind:'character',id:'zider'},type:'related to'}];const next=migrateWorldRecord(w);expect(next.relationships[0]).toMatchObject({id:'assigned',type:'applies to',to:{kind:'structure',id:'team'},fromPoint:{sceneId:'s1'}});expect(next.relationships[1]).toEqual(w.relationships[1]);expect(migrateWorldRecord(next)).toEqual(next);});
it('rejects incomplete subjects and invalid periods atomically',()=>{const s=fixture(),draft={entity:{id:'rule',kind:'rule' as const,name:'Rule',description:'Text'},period:'point' as const,relationships:[{id:'r',type:'applies to',target:{kind:'character' as const,id:'missing'}}],from:{sceneId:'s4'}};expect(()=>saveRule(s,docs,s.worlds![0].id,draft)).toThrow('no longer available');expect(s.worlds![0].entities.some(e=>e.id==='rule')).toBe(false);expect(()=>saveRule(s,docs,s.worlds![0].id,{...draft,period:'custom',until:{sceneId:'s1'}})).toThrow('end must be after');});
