import { expect, it } from 'vitest';
import { createWorld, packageWorld, copyWorld, relationshipAt, validateWorld, searchWorld, parseWorldPackage, linkCanonicalScene, characterWorldTerms } from './worlds';
import { migrateStory, deleteStoryEntity } from './story';
import { createScreenplay } from './screenplay';
import { mergeIdentity, separateIdentity } from './story-identities';
import type { WorldRelationship } from '../shared/worlds';
const setup = () => { const story = migrateStory(null, 'p'); story.characters = [{ id: 'apple', name: 'Apple', description: 'Detective', sourceNames: ['APPLE'] }]; story.locations = [{ id: 'station', name: 'Station', description: '' }]; const world = createWorld('Universe'); world.characterIds = ['apple']; world.locationIds = ['station']; world.entities = [{ id: 'scu', name: 'SCU', description: '', kind: 'organisation' }, { id: 't4', name: 'Team 4', description: '', kind: 'organisation' }, { id: 't5', name: 'Team 5', description: '', kind: 'organisation' }, { id: 'bell', name: 'Attention Bell', description: 'Quiet please', kind: 'object' }, { id: 'spell', name: 'Binding Spell', description: '', kind: 'lore', fields: { 'Exact wording': 'Veyra', 'Literal translation': 'Bind this soul', 'Meaning / usage': 'Prevents leaving' } }]; story.worlds = [world]; return { story, world }; };
it('projects only effective rank and position abbreviations and retains levels on copies', () => {
  const {story,world} = setup();
  world.entities.push({id:'dc',kind:'organisation',organisationRole:'rank',name:'Detective Constable',abbreviation:'DC',rankGroup:'Detective',rankLevel:1,description:''},{id:'di',kind:'organisation',organisationRole:'rank',name:'Detective Inspector',abbreviation:'DI',rankLevel:3,description:''},{id:'sio',kind:'organisation',organisationRole:'position',name:'Senior Investigating Officer',abbreviation:'SIO',description:''});
  world.relationships = [{id:'old',type:'member of',from:{kind:'character',id:'apple'},to:{kind:'organisation',id:'scu'},rankId:'dc',untilPoint:{chronology:{day:5}}},{id:'new',type:'member of',from:{kind:'character',id:'apple'},to:{kind:'organisation',id:'scu'},rankId:'di',positionId:'sio',fromPoint:{chronology:{day:5}}}];
  expect(characterWorldTerms(story,'apple',[],{chronology:{day:4}})).toBe(' (DC)');
  expect(characterWorldTerms(story,'apple',[],{chronology:{day:5}})).toBe(' (DI, SIO)');
  expect(characterWorldTerms(story,'apple',[],{chronology:{date:'2026-01-01'}})).toBe('');
  const copy=copyWorld(packageWorld(world,story),migrateStory(null,'target'));
  expect(copy.worlds![0].entities.find(e=>e.name==='Detective Constable')).toMatchObject({abbreviation:'DC',rankLevel:1,rankGroup:'Detective'});
});
it('keeps shared hierarchy placements on one entity and rejects a cycle', () => {
  const {story,world}=setup(); world.relationships=[{id:'a',type:'part of',from:{kind:'organisation',id:'t5'},to:{kind:'organisation',id:'scu'}},{id:'b',type:'part of',from:{kind:'organisation',id:'t5'},to:{kind:'organisation',id:'t4'}}];
  expect(()=>validateWorld(world,story)).not.toThrow();
  world.relationships.push({id:'cycle',type:'part of',from:{kind:'organisation',id:'t4'},to:{kind:'organisation',id:'t5'}});
  expect(()=>validateWorld(world,story)).toThrow('Circular');
});
it('copies, merges, separates and deletes typed custom-field links safely', () => {
  const {story,world}=setup(); world.characterIds=[]; world.entities[0].fields={Lead:'Lead detective'}; world.entities[0].fieldLinks={Lead:{kind:'character',id:'apple'}};
  const copied=copyWorld(packageWorld(world,story),migrateStory(null,'target'));
  expect(copied.characters).toHaveLength(1); expect(copied.worlds![0].entities[0].fieldLinks!.Lead.id).toBe(copied.characters[0].id);
  story.characters.push({id:'target',name:'Detective Apple',description:''});
  const merged=mergeIdentity(story,'characters','apple','target'); expect(merged.worlds![0].entities[0].fieldLinks!.Lead.id).toBe('target');
  const separated=separateIdentity(migrateStory(merged,'p'),'characters','target','APPLE',[]); expect(separated.worlds![0].entities[0].fieldLinks!.Lead.id).toBe('apple');
  const deleted=deleteStoryEntity(story,'characters','apple'); expect(deleted.worlds![0].entities[0].fieldLinks).toEqual({}); expect(deleted.worlds![0].entities[0].fields!.Lead).toBe('Lead detective');
});
it('reconstructs a transfer across episodes without moving independently related objects or rules', () => { const { story, world } = setup(); const docs = Array.from({ length: 7 }, (_, i) => createScreenplay({ projectId: 'p', title: 'Episode ' + (i + 1), screenplayType: 'episode' })); const old: WorldRelationship = { id: 'old', from: { kind: 'character', id: 'apple' }, to: { kind: 'organisation', id: 't4' }, type: 'member of', fromPoint: { screenplayId: docs[0].id }, untilPoint: { screenplayId: docs[4].id } }; const next: WorldRelationship = { ...old, id: 'next', to: { kind: 'organisation', id: 't5' }, fromPoint: { screenplayId: docs[4].id }, untilPoint: undefined }; const bell: WorldRelationship = { id: 'bell-link', from: { kind: 'object', id: 'bell' }, to: { kind: 'organisation', id: 't4' }, type: 'belongs to' }; world.relationships = [old, next, bell]; expect(relationshipAt(old, { screenplayId: docs[2].id }, story, docs)).toBe('active'); expect(relationshipAt(next, { screenplayId: docs[2].id }, story, docs)).toBe('inactive'); expect(relationshipAt(old, { screenplayId: docs[6].id }, story, docs)).toBe('inactive'); expect(relationshipAt(next, { screenplayId: docs[6].id }, story, docs)).toBe('active'); expect(relationshipAt(bell, { screenplayId: docs[6].id }, story, docs)).toBe('active'); expect(world.relationships).toHaveLength(3); });
it('uses existing Scene/Event chronology and keeps unknown temporal comparisons explicit', () => { const { story } = setup(); story.scenes = [{ sceneId: 's', screenplayId: 'd', chronology: { day: 3, time: '12:00' } }]; story.events = [{ id: 'e', name: 'Event', description: '', occursInSceneId: 's', contextOverrides: [] }]; const r: WorldRelationship = { id: 'r', from: { kind: 'character', id: 'apple' }, to: { kind: 'organisation', id: 't4' }, type: 'member of', fromPoint: { chronology: { day: 2 } }, untilPoint: { chronology: { day: 4 } } }; expect(relationshipAt(r, { eventId: 'e' }, story, [])).toBe('active'); expect(relationshipAt(r, { chronology: { date: '2026-01-01' } }, story, [])).toBe('unknown'); expect(relationshipAt(r, { chronology: { day: 4 } }, story, [])).toBe('inactive'); });
it('round-trips additive Worlds through validation and rejects cycles/invalid occurrence anchors', () => { const { story, world } = setup(); expect(migrateStory(story, 'p').worlds).toEqual(story.worlds); world.relationships = [{ id: 'a', type: 'part of', from: { kind: 'organisation', id: 't4' }, to: { kind: 'organisation', id: 'scu' } }, { id: 'b', type: 'part of', from: { kind: 'organisation', id: 'scu' }, to: { kind: 'organisation', id: 't4' } }]; expect(() => validateWorld(world)).toThrow('Circular'); expect(() => migrateStory({ ...story, worlds: [], worldOccurrences: [{ id: 'bad', worldId: world.id, entity: { kind: 'object', id: 'bell' }, screenplayId: 'd', sceneId: 's', scope: 'text' }] }, 'p')).toThrow(); });
it('copies all internal identity links independently and preserves provenance without duplicating project characters', () => { const { story, world } = setup(); world.relationships = [{ id: 'r', type: 'member of', from: { kind: 'character', id: 'apple' }, to: { kind: 'organisation', id: 't4' }, rankId: 'scu', positionId: 't5', reportsToId: 'apple' }]; const p = packageWorld(world, story); const a = copyWorld(p, migrateStory(null, 'a')); const b = copyWorld(p, migrateStory(null, 'b')); expect(a.characters).toHaveLength(1); expect(a.worlds![0].characterIds).toEqual([a.characters[0].id]); expect(a.worlds![0].relationships[0].from.id).toBe(a.characters[0].id); expect(a.worlds![0].relationships[0].reportsToId).toBe(a.characters[0].id); expect(a.worlds![0].id).not.toBe(b.worlds![0].id); a.worlds![0].entities[0].name = 'Changed'; expect(p.world.entities[0].name).toBe('SCU'); expect(b.worlds![0].entities[0].name).toBe('SCU'); expect(a.worlds![0].provenance?.worldId).toBe(world.id); expect(parseWorldPackage(p)).toEqual(p); });
it('searches canonical lore translation separately from exact wording', () => { const { story, world } = setup(); expect(searchWorld(world, story, 'Prevents leaving').map(e => e.id)).toEqual(['spell']); expect(searchWorld(world, story, 'Bind this soul')[0].id).toBe('spell'); expect(world.entities.find(e => e.id === 'spell')?.fields?.['Exact wording']).toBe('Veyra'); });
it('redirects canonical World links on identity merge and restores them on separation', () => { const { story, world } = setup(); story.characters.push({ id: 'target', name: 'Detective Apple', description: '', sourceNames: ['DETECTIVE APPLE'] }); world.relationships = [{ id: 'r', type: 'member of', from: { kind: 'character', id: 'apple' }, to: { kind: 'organisation', id: 't4' }, reportsToId: 'apple' }]; story.worldOccurrences = [{ id: 'o', worldId: world.id, entity: { kind: 'character', id: 'apple' }, screenplayId: 'd', sceneId: 's', scope: 'scene' }]; const merged = mergeIdentity(story, 'characters', 'apple', 'target'); expect(merged.worlds![0].characterIds).toEqual(['target']); expect(merged.worlds![0].relationships[0].from.id).toBe('target'); expect(merged.worldOccurrences![0].entity.id).toBe('target'); const restored = separateIdentity(migrateStory(merged, 'p'), 'characters', 'target', 'APPLE', []); expect(restored.worlds![0].characterIds).toEqual(['apple']); expect(restored.worlds![0].relationships[0].reportsToId).toBe('apple'); expect(restored.worldOccurrences![0].entity.id).toBe('apple'); });
it('reuses known source identities when copying back to the same project and includes Location ancestors', () => { const { story, world } = setup(); story.locations.push({ id: 'city', name: 'City', description: '' }); story.locations[0].parentId = 'city'; const pack = packageWorld(world, story); expect(pack.locations).toHaveLength(2); const master = copyWorld(pack, migrateStory(null, 'library')); const result = copyWorld(packageWorld(master.worlds![0], master), story); expect(result.characters).toHaveLength(1); expect(result.locations).toHaveLength(2); expect(result.worlds![1].characterIds).toEqual(['apple']); expect(result.worlds![1].locationIds).toEqual(['station']); });
it('permits hierarchy reversals in non-overlapping history but rejects simultaneous cycles', () => { const { story, world } = setup(); world.relationships = [{ id: 'past', type: 'part of', from: { kind: 'organisation', id: 't4' }, to: { kind: 'organisation', id: 't5' }, fromPoint: { chronology: { day: 1 } }, untilPoint: { chronology: { day: 5 } } }, { id: 'now', type: 'part of', from: { kind: 'organisation', id: 't5' }, to: { kind: 'organisation', id: 't4' }, fromPoint: { chronology: { day: 5 } } }]; expect(() => validateWorld(world, story)).not.toThrow(); world.relationships[0].untilPoint = { chronology: { day: 6 } }; expect(() => validateWorld(world, story)).toThrow('Circular'); });
it('links Plot/Event/Character at their existing Scene relationship source without duplicate World facts', () => { const story = migrateStory(null, 'p'); story.plots = [{ id: 'plot', name: 'Plot', description: '', color: 'accent' }]; story.characters = [{ id: 'apple', name: 'Apple', description: '' }]; story.events = [{ id: 'event', name: 'Event', description: '', occursInSceneId: 'original' }]; const plot = linkCanonicalScene(story, 'scene', 'screenplay', { kind: 'plot', id: 'plot' })!; expect(plot.scenes[0].plotIds).toEqual(['plot']); const event = linkCanonicalScene(plot, 'scene', 'screenplay', { kind: 'event', id: 'event' })!; expect(event.events[0].referencedInSceneIds).toEqual(['scene']); expect(event.events[0].occursInSceneId).toBe('original'); const character = linkCanonicalScene(event, 'scene', 'screenplay', { kind: 'character', id: 'apple' })!; expect(character.scenes[0].referencedIds).toEqual(['apple']); expect(character.scenes[0].presentIds).toBeUndefined(); expect(character.worldOccurrences).toBeUndefined(); expect(migrateStory(character, 'p')).toEqual(character); });

it('deleting a canonical person removes only their World links and leaves Objects and units intact',()=>{const {story,world}=setup();world.relationships=[{id:'member',type:'member of',from:{kind:'character',id:'apple'},to:{kind:'organisation',id:'t4'}},{id:'object',type:'belongs to',from:{kind:'object',id:'bell'},to:{kind:'organisation',id:'t4'}}];story.worldOccurrences=[{id:'person-use',worldId:world.id,entity:{kind:'character',id:'apple'},screenplayId:'d',sceneId:'s',scope:'scene'},{id:'bell-use',worldId:world.id,entity:{kind:'object',id:'bell'},screenplayId:'d',sceneId:'s',scope:'scene'}];const next=deleteStoryEntity(story,'characters','apple');expect(next.worlds![0].entities).toEqual(world.entities);expect(next.worlds![0].characterIds).toEqual([]);expect(next.worlds![0].relationships.map(r=>r.id)).toEqual(['object']);expect(next.worldOccurrences!.map(o=>o.id)).toEqual(['bell-use']);expect(()=>parseWorldPackage(packageWorld(next.worlds![0],next))).not.toThrow();});

it('preserves multiple reporting overrides through migration, copy, merge, separation and deletion',()=>{
 const {story,world}=setup();story.characters.push({id:'gates',name:'Gates',description:'',sourceNames:['GATES']},{id:'lee',name:'Lee',description:'',sourceNames:['LEE']});world.relationships=[{id:'m',type:'member of',from:{kind:'character',id:'apple'},to:{kind:'organisation',id:'scu'},reportsToIds:['gates','lee']}];
 expect(migrateStory(story,'p').worlds![0].relationships[0].reportsToIds).toEqual(['gates','lee']);const pkg=packageWorld(world,story);expect(pkg.characters.map(c=>c.id)).toEqual(expect.arrayContaining(['apple','gates','lee']));const copy=copyWorld(parseWorldPackage(pkg),migrateStory(null,'copy'));expect(copy.worlds![0].relationships[0].reportsToIds).toEqual(['Gates','Lee'].map(name=>copy.characters.find(c=>c.name===name)!.id));
 const merged=migrateStory(mergeIdentity(story,'characters','gates','lee'),'p');expect(merged.worlds![0].relationships[0].reportsToIds).toEqual(['lee']);const restored=separateIdentity(merged,'characters','lee','GATES',[]);expect(restored.worlds![0].relationships[0].reportsToIds).toEqual(expect.arrayContaining(['gates','lee']));expect(deleteStoryEntity(restored,'characters','gates').worlds![0].relationships[0].reportsToIds).toEqual(['lee']);
});
