import { mkdtemp, mkdir, readFile, readdir, rename, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { afterEach, expect, it } from 'vitest';
import { FileProjectRepository, initializeStorageRoot } from './storage';
const roots: string[] = [];
afterEach(async () => { for (const root of roots.splice(0))
    await rm(root, { recursive: true, force: true }); });
async function setup() { const root = await mkdtemp(join(tmpdir(), 'project-history-')); roots.push(root); await initializeStorageRoot(root); const repo = new FileProjectRepository(root), project = await repo.create('History safety', 'feature'); return { root, repo, project, dir: join(root, 'Projects', project.id) }; }
it('preserves both copies of a stale save and never replaces the acknowledged current screenplay', async () => { const { repo, project, dir } = await setup(); const original = (await repo.openWorkspace(project.id)).screenplays[0]; const edited = structuredClone(original); edited.scenes[0].elements[1].content = 'Saved work'; await repo.saveScreenplay(project.id, edited); const stale = structuredClone(original); stale.scenes[0].elements[1].content = 'Offline work'; await expect(repo.saveScreenplay(project.id, stale)).rejects.toThrow('conflicts'); const files = await readdir(join(dir, 'conflicts')); const conflict = JSON.parse(await readFile(join(dir, 'conflicts', files[0]), 'utf8')); expect(conflict.current.scenes[0].elements[1].content).toBe('Saved work'); expect(conflict.incoming.scenes[0].elements[1].content).toBe('Offline work'); expect((await repo.openWorkspace(project.id)).screenplays[0].scenes[0].elements[1].content).toBe('Saved work'); });
it('blocks a competing lease, recovers expired leases and preserves stable identities after folder rename', async () => { const { root, repo, project, dir } = await setup(); const doc = (await repo.openWorkspace(project.id)).screenplays[0]; await writeFile(join(dir, 'editing-lease.json'), JSON.stringify({ id: 'other-session', displayName: 'Other writer', expiresAt: Date.now() + 60000 })); await expect(repo.saveScreenplay(project.id, doc)).rejects.toThrow('Other writer'); await writeFile(join(dir, 'editing-lease.json'), JSON.stringify({ id: 'other-session', expiresAt: Date.now() - 1 })); await repo.saveScreenplay(project.id, doc); await repo.projectHistory(project.id, { action: 'release' }); await rename(dir, join(root, 'Projects', 'Renamed Project')); const moved = await new FileProjectRepository(root).openWorkspace(project.id); expect(moved.project.id).toBe(project.id); expect(moved.screenplays[0].id).toBe(doc.id); expect((await new FileProjectRepository(root).list())[0].id).toBe(project.id); });
it('keeps ordinary writing saved when History cannot be written', async () => {
    const { repo, project, dir } = await setup();
    await writeFile(join(dir,'history','control.json'),'corrupted History control');
    const doc = (await repo.openWorkspace(project.id)).screenplays[0];
    doc.scenes[0].elements[1].content = 'Current work must survive'; // Permission checks must still work when the optional History sidecar is unavailable.
    await repo.saveScreenplay(project.id, doc);
    expect((await repo.openWorkspace(project.id)).screenplays[0].scenes[0].elements[1].content).toBe('Current work must survive');
});
it('writes self-contained periodic backups and restores named Versions across repository restart', async () => { const { root, repo, project, dir } = await setup(); await mkdir(join(dir, 'assets')); await writeFile(join(dir, 'assets', 'asset-id.png'), 'immutable image'); const doc = (await repo.openWorkspace(project.id)).screenplays[0]; doc.scenes[0].elements[1].content = 'First draft'; const saved = await repo.saveScreenplay(project.id, doc); const version = (await repo.projectHistory(project.id, { action: 'createVersion', name: 'Draft one' })).version!; saved.scenes[0].elements[1].content = 'Later draft'; await repo.saveScreenplay(project.id, saved); const reopened = new FileProjectRepository(root); const restored = await reopened.projectHistory(project.id, { action: 'restoreVersion', id: version.id }); expect(restored.workspace!.screenplays[0].scenes[0].elements[1].content).toBe('First draft'); const backups = (await readdir(join(dir, 'backups'))).filter(n => n !== 'latest.json'); expect(backups).toHaveLength(1); expect(await readFile(join(dir, 'backups', backups[0], 'assets', 'asset-id.png'), 'utf8')).toBe('immutable image'); expect(JSON.parse(await readFile(join(dir, 'backups', backups[0], 'workspace.json'), 'utf8')).project.id).toBe(project.id); });
