import type { WorldKind } from './worlds';
export type WorldFormField = { key:string; label?:string; type?:'text'|'multiline'|'number'|'select'; options?:string[]; section?:string; when?:string[] };
const field=(key:string,options?:string[],section?:string):WorldFormField=>({key,type:options?'select':'multiline',options,section});
export const PLACE_TYPES=['Building','Room','Office','Hospital','Police station','House','Flat','Warehouse','Shop','Street','Outdoor location','Fictional location','Other'];
export const VEHICLE_TYPES=['Car','Van','Motorcycle','Bicycle','Lorry','Bus','Train','Boat','Aircraft','Other'];
export const LORE_FORM_TYPES=['Word','Phrase','Saying','Slang','Spell','Ritual','Tradition','Myth','Historical event','Belief','Symbol','Other','Incantation','Prayer','Oath','Chant','Terminology','Code','Potion/Recipe','Custom'];
export const WORLD_FORM_SCHEMAS:Partial<Record<WorldKind,{aliases?:boolean;fields:WorldFormField[]}>>={
 organisation:{aliases:true,fields:[field('Rank terminology'),field('Position terminology')]},
 structure:{fields:[]},rank:{fields:[]},position:{fields:[]},
 character:{aliases:true,fields:[field('Occupation'),field('Skills',undefined,'Personal details'),field('Traits',undefined,'Personal details'),field('Appearance',undefined,'Personal details'),field('Status'),field('Notes',undefined,'Personal details')]},
 location:{fields:[field('Place type',PLACE_TYPES),field('Address / fictional location'),field('Appearance',undefined,'Place details'),field('Function / purpose',undefined,'Place details'),field('Access restrictions',undefined,'Place details'),field('Status'),field('Notes',undefined,'Place details')]},
 object:{aliases:true,fields:[field('Type',['Weapon','Phone','Evidence','Jewellery','Document','Equipment','Personal possession','Other']),field('Appearance'),field('Condition'),field('Significance',undefined,'More details'),field('Purpose',undefined,'More details'),field('Status'),field('Notes',undefined,'More details')]},
 vehicle:{fields:[field('Type',VEHICLE_TYPES),field('Make'),field('Model'),{key:'Year',type:'number'},field('Colour'),{key:'Registration/identifier',label:'Registration',type:'text'},field('Appearance'),field('Condition'),field('Distinguishing features',undefined,'More details'),field('Make/model',undefined,'Previous details'),field('Status'),field('Notes',undefined,'More details')]},
 rule:{fields:[field('Type',['Law','Organisation policy','Procedure','Social rule','Cultural rule','Scientific rule','Magical rule','Religious rule','Other']),field('Exceptions',undefined,'More details'),field('Consequences',undefined,'More details'),field('Reason',undefined,'More details'),field('Status'),field('Notes',undefined,'More details'),field('Importance',['Low','Medium','High'])]},
 lore:{fields:[field('Type',LORE_FORM_TYPES),{key:'Exact wording',label:'Original text',type:'multiline',when:['Word','Phrase','Saying','Slang','Incantation','Prayer','Oath','Chant','Terminology','Code','Custom']}, {key:'Exact wording',label:'Incantation',type:'multiline',when:['Spell']},field('Literal translation',undefined,'Language details'),field('Pronunciation',undefined,'Language details'),field('Language',undefined,'Language details'),field('Meaning / usage'),field('Origin',undefined,'More details'),field('Culture / group',undefined,'More details'),field('Usage',undefined,'More details'),{key:'Effect',type:'multiline',when:['Spell','Potion/Recipe']},{key:'Requirements',type:'multiline',when:['Spell','Ritual']},field('Restrictions',undefined,'More details'),{key:'Ingredients',type:'multiline',when:['Potion/Recipe']},{key:'Preparation',type:'multiline',when:['Potion/Recipe']},{key:'Duration',type:'multiline',when:['Potion/Recipe']},field('Variants',undefined,'Language details'),field('Notes',undefined,'More details')]},
 note:{fields:[field('Type',['General','Research','Medical','Legal','Production','Continuity','Character','Organisation','Location','Other']),field('Importance',['Low','Medium','High'])]},
};
export const WORLD_CHARACTER_LINKS:Partial<Record<WorldKind,string[]>>={object:['owned by','created by','held by','used by','assigned to'],vehicle:['owned by','driven by','passenger','maintained by'],location:['owned by','lived in by','rented by','worked at by','visited by','patient','detained','managed by'],lore:['created by','used by','owned by'],rule:['applies to','enforced by'],note:['about'],organisation:['member of'],structure:['member of']};
export const WORLD_LINK_LABELS:Record<string,[string,string]>={
 'owned by':['Owner','Owns'],'created by':['Creator','Created'],'held by':['Holder','Holds'],'used by':['User','Uses'],'assigned to':['Assigned to','Assigned item'], 'driven by':['Driver / operator','Drives / operates'],'passenger':['Passenger','Passenger in'],'maintained by':['Mechanic','Maintains'], 'lived in by':['Resident','Lives at'],'rented by':['Tenant','Rents'],'worked at by':['Employee','Works at'],'visited by':['Visitor','Visits'],'patient':['Patient','Patient at'],'detained':['Detained person','Detained at'],'managed by':['Manager','Manages'], 'stored at':['Stored at','Stores'],'based at':['Based at','Base for'],'belongs to':['Belongs to','Includes'],'applies to':['Applies to','Subject to'],'enforced by':['Enforced by','Enforces'],'about':['About','Related note'],'related to':['Related to','Related to'],'member of':['Member of','Member'],'part of':['Part of','Includes'], 'reports to':['Reports to','Manages'], 'issued by':['Issued by','Issues']
};
