import { useState } from 'react';
import type { StoryRecord } from '../shared/story';
import type { ScreenplayRecord } from '../shared/models';
import type { WorldPoint, WorldRecord } from '../shared/worlds';
import { characterMemberships } from '../domain/world-memberships';
import { validateWorld } from '../domain/worlds';
import { deleteWorldData } from '../domain/world-delete';
import { MembershipSummary, PointFields, RelationshipEditor } from './WorldRelationshipEditor';
import { WorldDeleteDialog } from './WorldDeleteDialog';
import { WorldEntityContext } from './WorldEntityContext';

export function CharacterWorlds({ story, documents, characterId, change, sceneId, navigate }: { story:StoryRecord; documents:ScreenplayRecord[]; characterId:string; change(s:StoryRecord):void; sceneId?:string; navigate(id:string):void }) {
 const [at,setAt]=useState<WorldPoint>(), [adding,setAdding]=useState(false), [worldId,setWorldId]=useState(''), [begin,setBegin]=useState<{worldId:string;token:number}>(), [error,setError]=useState(''), [deleting,setDeleting]=useState<{world:WorldRecord;id:string}>();
 const available=(story.worlds ?? []).filter(w=>!w.archived), current=characterMemberships(story,characterId,documents,at), history=characterMemberships(story,characterId,documents,undefined,true);
 const apply=(next:WorldRecord)=>{validateWorld(next,story,documents);change({...story,worlds:story.worlds?.map(w=>w.id===next.id?next:w)});setError('');};
 const open=(worldId:string,entity:import('../shared/worlds').WorldRef)=>window.dispatchEvent(new CustomEvent('open-world-reference',{detail:{worldId,entity}}));
 return <section className="character-worlds"><h3>{at ? 'Memberships at selected point' : 'Current memberships'}</h3><PointFields label="View memberships" mode="view" value={at} onChange={setAt} documents={documents} story={story}/>{current.length ? <div className="membership-cards">{current.map(({world,relationship})=><article className="membership-card" key={relationship.id}><small>{world.name}</small><MembershipSummary world={world} story={story} relationship={relationship} documents={documents} at={at} compact/></article>)}</div> : <p>No active memberships{at?' at this point':''}.</p>}
 <button onClick={()=>{setAdding(true);setWorldId(available[0]?.id ?? '');}}>+ Add membership</button>{adding && <fieldset><legend>Add Organisation membership</legend><label>World<select aria-label="World" value={worldId} onChange={e=>setWorldId(e.target.value)}><option value="">Choose World…</option>{available.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label>{!available.length && <p>Create a Project World from Worlds first.</p>}<button disabled={!worldId || !available.find(w=>w.id===worldId)?.entities.some(e=>e.kind==='organisation'&&!e.archived)} onClick={()=>{setBegin({worldId,token:Date.now()});setAdding(false);}}>Continue membership</button><button onClick={()=>setAdding(false)}>Cancel</button></fieldset>}
 {error && <p role="alert">{error}</p>}{(story.worlds ?? []).filter(w=>!w.archived||history.some(m=>m.world.id===w.id)||begin?.worldId===w.id||w.characterIds.includes(characterId)||w.relationships.some(r=>r.from.kind==='character'&&r.from.id===characterId||r.to.kind==='character'&&r.to.id===characterId)).map(world=><details className="membership-world" key={world.id} open={history.some(m=>m.world.id===world.id)||begin?.worldId===world.id||world.characterIds.includes(characterId)||world.relationships.some(r=>r.from.id===characterId||r.to.id===characterId)}><summary>{world.name}{world.archived?' · Archived World':''}</summary><RelationshipEditor world={world} story={story} documents={documents} selected={{kind:'character',id:characterId}} at={at} membershipOnly beginMembership={begin?.worldId===world.id ? begin : undefined} patch={next=>{try{apply(next);}catch(e){setError(String(e));throw e;}}} open={entity=>open(world.id,entity)} remove={id=>setDeleting({world,id})}/><RelationshipEditor world={world} story={story} documents={documents} selected={{kind:'character',id:characterId}} at={at} excludeMemberships patch={next=>{try{apply(next);}catch(e){setError(String(e));}}} open={entity=>open(world.id,entity)} remove={id=>setDeleting({world,id})}/></details>)}
 <WorldEntityContext story={story} documents={documents} entity={{kind:'character',id:characterId}} sceneId={sceneId} navigate={navigate} omitMemberships omitRelationships/>
 {deleting && <WorldDeleteDialog story={story} world={deleting.world} target={{kind:'relationship',id:deleting.id}} cancel={()=>setDeleting(undefined)} confirm={()=>{window.dispatchEvent(new Event('world-permanent-delete'));change(deleteWorldData(story,deleting.world.id,{kind:'relationship',id:deleting.id}));setDeleting(undefined);}}/>}
 </section>;
}
