// @vitest-environment jsdom
import { cleanup, fireEvent, render, within, waitFor } from '@testing-library/react';
import '@testing-library/jest-dom/vitest';
import { useState } from 'react';
import { afterEach, expect, it, vi } from 'vitest';
import { migrateStory } from '../domain/story';
import { createWorld } from '../domain/worlds';
import { createScreenplay } from '../domain/screenplay';
import { ProfileEditor } from './ProfileEditor';
import { CharacterWorlds } from './CharacterWorlds';
import { WorldOrganisationMembers } from './WorldOrganisationMembers';
import { CharacterMembershipCard } from './CharacterMembershipCard';
import type { StoryRecord } from '../shared/story';
afterEach(cleanup);
it('lets an unaffiliated character own a world vehicle directly from their profile',()=>{
 const story=migrateStory(null,'p'),world=createWorld('Vehicle World');story.characters=[{id:'apple',name:'Apple',description:''}];world.entities=[{id:'car',kind:'vehicle',name:'Mondeo',description:''}];story.worlds=[world];let latest=story;
 function Harness(){const[s,set]=useState(story);return <CharacterWorlds story={s} documents={[]} characterId="apple" change={s=>{latest=s;set(s);}} navigate={()=>{}}/>;}
 const v=render(<Harness/>);v.container.querySelector('.membership-world')!.setAttribute('open','');fireEvent.click(v.getByRole('button',{name:'Add world item'}));fireEvent.change(v.getByLabelText('World item'),{target:{value:'car'}});expect(v.queryByLabelText('Organisation')).toBeNull();fireEvent.click(v.getByRole('button',{name:'Save relationship'}));expect(latest.worlds![0].relationships).toHaveLength(1);expect(latest.worlds![0].relationships[0]).toMatchObject({type:'owned by',from:{kind:'vehicle',id:'car'},to:{kind:'character',id:'apple'}});
});
function fixture(){const story=migrateStory(null,'p'),world=createWorld('The Altered'),documents=Array.from({length:7},(_,i)=>createScreenplay({projectId:'p',title:'Episode '+(i+1),screenplayType:'episode'}));story.characters=['apple','gates','outsider'].map(id=>({id,name:id.toUpperCase(),description:''}));world.entities=[{id:'scu',kind:'organisation',name:'Specialist Crime Unit',abbreviation:'SCU',description:'',fields:{'Rank terminology':'Grade'}},{id:'uni',kind:'organisation',name:'University',description:''},{id:'t4',kind:'structure',organisationId:'scu',name:'Team 4',description:''},{id:'t5',kind:'structure',organisationId:'scu',name:'Team 5',description:''},{id:'school',kind:'structure',organisationId:'uni',name:'Medical School',description:''},{id:'dc',kind:'rank',organisationId:'scu',name:'Detective Constable',abbreviation:'DC',description:''}];world.relationships=[{id:'gates-m',type:'member of',from:{kind:'character',id:'gates'},to:{kind:'organisation',id:'scu'}}];world.characterIds=['gates'];story.worlds=[world];return{story,world,documents};}
it('the full profile exposes Worlds and profile/Organisation surfaces edit the same membership with history',async()=>{
 const {story:initial,documents}=fixture();let latest=initial;
 function Harness(){const [story,setStory]=useState(initial),[surface,setSurface]=useState('profile');const change=(s:StoryRecord)=>{latest=s;setStory(s);};return <><button onClick={()=>setSurface(surface==='profile'?'organisation':'profile')}>Switch surface</button>{surface==='profile'?<ProfileEditor story={story} documents={documents} context={{type:'character',entityId:'apple'}} change={change} navigate={vi.fn()} timeline={vi.fn()} close={vi.fn()} undo={vi.fn()} remove={vi.fn()} saveStatus="Saved"/>:<WorldOrganisationMembers story={story} world={story.worlds![0]} documents={documents} selected={{kind:'organisation',id:'scu'}} change={change} patch={w=>change({...story,worlds:[w]})} open={vi.fn()} remove={vi.fn()}/>}</>;}
 const view=render(<Harness/>);fireEvent.click(view.getByRole('button',{name:'Worlds'}));fireEvent.click(view.container.querySelector('.character-worlds > button')!);fireEvent.click(view.getByRole('button',{name:'Continue membership'}));fireEvent.change(view.getByLabelText('Organisation'),{target:{value:'organisation:scu'}});expect(within(view.getByLabelText('Internal unit')).queryByRole('option',{name:/Medical School/})).not.toBeInTheDocument();fireEvent.change(view.getByLabelText('Internal unit'),{target:{value:'t4'}});fireEvent.change(view.getByLabelText('Grade'),{target:{value:'dc'}});
 expect(within(view.getByLabelText('Reports to')).getByRole('option',{name:'GATES'})).toBeInTheDocument();expect(within(view.getByLabelText('Reports to')).queryByRole('option',{name:'OUTSIDER'})).not.toBeInTheDocument();fireEvent.change(view.getByLabelText('Reports to'),{target:{value:'gates'}});fireEvent.change(view.getByLabelText('Starts type'),{target:{value:'episode'}});fireEvent.change(view.getByLabelText('Starts episode'),{target:{value:documents[0].id}});fireEvent.click(view.getByRole('button',{name:'Save relationship'}));
 expect(latest.worlds![0].characterIds).toContain('apple');expect(latest.characters.find(c=>c.id==='apple')).toEqual({id:'apple',name:'APPLE',description:''});expect(view.getByRole('heading',{name:'Current memberships'})).toBeVisible();fireEvent.click(view.getByRole('button',{name:'Switch surface'}));
 fireEvent.click(view.getByRole('button',{name:/^APPLE/}));fireEvent.click(view.getByRole('button',{name:'Transfer membership'}));fireEvent.change(view.getByLabelText('Internal unit'),{target:{value:'t5'}});fireEvent.change(view.getByLabelText('Starts type'),{target:{value:'episode'}});fireEvent.change(view.getByLabelText('Starts episode'),{target:{value:documents[4].id}});fireEvent.click(view.getByRole('button',{name:'Save relationship'}));expect(latest.worlds![0].relationships.filter(r=>r.from.id==='apple')).toHaveLength(2);
 fireEvent.click(view.getByRole('button',{name:'Switch surface'}));fireEvent.click(view.getByRole('button',{name:'Worlds'}));expect(view.getByText('Episode 1 → Episode 4')).toBeVisible();expect(view.getByText('Team / Unit: Team 5')).toBeVisible();expect(view.container.querySelector('.membership-cards')).toHaveTextContent('Team 5');
 fireEvent.click(view.getAllByRole('button',{name:'Delete relationship…'})[0]);fireEvent.click(view.getByRole('button',{name:'Delete relationship'}));await waitFor(()=>expect(view.queryByRole('alertdialog')).not.toBeInTheDocument());expect(latest.worlds![0].relationships.filter(r=>r.from.id==='apple')).toHaveLength(1);expect(latest.characters).toHaveLength(3);expect(latest.worlds![0].entities).toHaveLength(6);
});
it('Organisation Create Character uses the normal canonical Character collection',()=>{
 const {story:initial,documents}=fixture();let latest=initial;function Harness(){const[story,setStory]=useState(initial);const change=(s:StoryRecord)=>{latest=s;setStory(s);};return <WorldOrganisationMembers story={story} world={story.worlds![0]} documents={documents} selected={{kind:'structure',id:'t5'}} change={change} patch={w=>change({...story,worlds:[w]})} open={vi.fn()} remove={vi.fn()}/>;}
 const view=render(<Harness/>);fireEvent.click(view.getByRole('button',{name:'Create Character'}));fireEvent.change(view.getByLabelText('Character name'),{target:{value:'New colleague'}});fireEvent.click(view.getByRole('button',{name:'Create Character and assign membership'}));fireEvent.click(view.getByRole('button',{name:'Save relationship'}));const c=latest.characters.find(c=>c.name==='New colleague')!;expect(c).toBeDefined();expect(latest.worlds![0].characterIds).toContain(c.id);expect(latest.worlds![0].relationships.find(r=>r.from.id===c.id)).toMatchObject({unitId:'t5',to:{kind:'organisation',id:'scu'}});
});
it('quick card projects the scene membership and supports hiding individual fields',()=>{
 const {story,world,documents}=fixture();world.relationships.push({id:'old',type:'member of',from:{kind:'character',id:'apple'},to:{kind:'organisation',id:'scu'},unitId:'t4',rankId:'dc',untilPoint:{screenplayId:documents[4].id}},{id:'new',type:'member of',from:{kind:'character',id:'apple'},to:{kind:'organisation',id:'scu'},unitId:'t5',rankId:'dc',fromPoint:{screenplayId:documents[4].id}});const open=vi.fn();const view=render(<CharacterMembershipCard story={story} documents={documents} characterId="apple" at={{sceneId:documents[2].scenes[0].id}} open={open}/>);expect(view.container).toHaveTextContent('Team 4 · SCU');fireEvent.click(view.getByRole('button'));expect(open).toHaveBeenCalledOnce();view.rerender(<CharacterMembershipCard story={story} documents={documents} characterId="apple" at={{sceneId:documents[6].scenes[0].id}} fields={['unit']} open={open}/>);expect(view.container).toHaveTextContent('Team 5');expect(view.container).not.toHaveTextContent('SCU');expect(view.container).not.toHaveTextContent('Detective Constable');
});
it('ending a membership retains its period and never removes either endpoint',()=>{
 const {story:initial,world,documents}=fixture();world.relationships.push({id:'apple-member',type:'member of',from:{kind:'character',id:'apple'},to:{kind:'organisation',id:'scu'},unitId:'t4',fromPoint:{screenplayId:documents[0].id}});let latest=initial;
 function Harness(){const[story,setStory]=useState(initial);return <CharacterWorlds story={story} documents={documents} characterId="apple" change={s=>{latest=s;setStory(s);}} navigate={vi.fn()}/>;}
 const view=render(<Harness/>);fireEvent.click(view.getByRole('button',{name:'End membership'}));fireEvent.change(view.getByLabelText('Ends before type'),{target:{value:'episode'}});fireEvent.change(view.getByLabelText('Ends before episode'),{target:{value:documents[6].id}});fireEvent.click(view.getByRole('button',{name:'Save relationship'}));expect(latest.worlds![0].relationships.find(r=>r.id==='apple-member')).toMatchObject({untilPoint:{screenplayId:documents[6].id}});expect(view.getByText('Episode 1 → Episode 6')).toBeVisible();expect(view.getByText('No active memberships.')).toBeVisible();expect(latest.characters).toHaveLength(3);expect(latest.worlds![0].entities).toHaveLength(6);
});
it('existing screenplay Characters are explicitly reused when a matching name is entered',()=>{
 const {story:initial,documents}=fixture();let latest=initial;function Harness(){const[story,setStory]=useState(initial);const change=(s:StoryRecord)=>{latest=s;setStory(s);};return <WorldOrganisationMembers story={story} world={story.worlds![0]} documents={documents} selected={{kind:'structure',id:'t4'}} change={change} patch={w=>change({...story,worlds:[w]})} open={vi.fn()} remove={vi.fn()}/>;}
 const view=render(<Harness/>);fireEvent.click(view.getByRole('button',{name:'Create Character'}));fireEvent.change(view.getByLabelText('Character name'),{target:{value:'apple'}});expect(view.getByRole('button',{name:'Create Character and assign membership'})).toBeDisabled();fireEvent.click(view.getByRole('button',{name:'Use existing APPLE'}));fireEvent.click(view.getByRole('button',{name:'Save relationship'}));expect(latest.characters).toHaveLength(3);expect(latest.worlds![0].relationships.find(r=>r.from.id==='apple')).toMatchObject({unitId:'t4'});
});
