import { Choices } from './StoryControls';
import { useState } from 'react';
import type { StoryRecord } from '../shared/story';
import type { ScreenplayRecord } from '../shared/models';
import type { WorldRecord, WorldRef, WorldPoint, WorldEntity } from '../shared/worlds';
import { STRUCTURE_TYPES } from '../shared/worlds';
import { createStructures, previewStructures, structureSort, structureParents, setStructureParent, reorderStructures, moveStructures, isOrganisation, isRole } from '../domain/world-structure';
import { validateWorld, relationshipAt } from '../domain/worlds';

export function OrganisationStructure({ world, story, documents, selected, at, patch, open, remove }: {
 world:WorldRecord; story:StoryRecord; documents:ScreenplayRecord[]; selected:WorldRef; at?:WorldPoint; patch(w:WorldRecord):void; open(r:WorldRef):void; remove(r:WorldRef):void;
}) {
 const [mode,setMode]=useState<'one'|'multiple'>(), [sequence,setSequence]=useState(false), [names,setNames]=useState(''),[prefix,setPrefix]=useState(''),[from,setFrom]=useState('1'),[to,setTo]=useState('5'),[type,setType]=useState('Unit'),[short,setShort]=useState(''),[level,setLevel]=useState(''),[parent,setParent]=useState(''),[error,setError]=useState(''),[chosen,setChosen]=useState<string[]>([]),[bulkLevel,setBulkLevel]=useState(''),[bulkParent,setBulkParent]=useState(''),[bulkType,setBulkType]=useState('Unit'),[destination,setDestination]=useState(''),[includeArchived,setIncludeArchived]=useState(false);
 const org=world.entities.find(e=>e.id===selected.id&&isOrganisation(e));
 if(!org) return null;
 const units=world.entities.filter(e=>e.kind==='structure'&&e.organisationId===org.id&&(includeArchived||!e.archived)).sort(structureSort), parents=structureParents(world,story,documents,at);
 const draft={type,names,prefix,sequence:mode==='multiple'&&sequence,from:from===''?NaN:Number(from),to:to===''?NaN:Number(to),abbreviationPattern:short||undefined,hierarchyLevel:level?Number(level):undefined,parentId:parent||undefined};
 let preview:ReturnType<typeof previewStructures>=[],previewError=''; if(mode)try{preview=previewStructures(draft);}catch(e){previewError=String(e).replace('Error: ','');}
 const save=(next:WorldRecord)=>{try{validateWorld(next,story,documents);patch(next);setError('');return true;}catch(e){setError(String(e));return false;}};
 const edit=(ids:string[],changes:Partial<WorldEntity>)=>save({...world,entities:world.entities.map(e=>ids.includes(e.id)?{...e,...changes}:e)});
 const shift=(ids:string[],delta:number)=>save({...world,entities:world.entities.map(e=>ids.includes(e.id)?{...e,hierarchyLevel:Math.max(1,(e.hierarchyLevel??1)+delta)}:e)});
 const reorder=(id:string,delta:-1|1)=>save(reorderStructures(world,[id],delta,story,documents,at));
 const applyParent=(ids:string[],id:string)=>{try{save(setStructureParent(world,ids,id||undefined,at));}catch(e){setError(String(e));}};
 const move=()=>{if(!destination||destination===org.id)return;try{if(save(moveStructures(world,chosen,destination,story,documents,at)))setChosen([]);}catch(e){setError(String(e));}};
 const peerIndex=(e:WorldEntity)=>{const key=(parents.get(e.id)??[]).map(p=>p.kind+':'+p.id).sort().join(',');const peers=units.filter(o=>o.hierarchyLevel===e.hierarchyLevel&&(parents.get(o.id)??[]).map(p=>p.kind+':'+p.id).sort().join(',')===key).sort((a,b)=>(a.displayOrder??0)-(b.displayOrder??0)||a.name.localeCompare(b.name));return {index:peers.findIndex(o=>o.id===e.id),count:peers.length};};
 const levels=[...new Set(units.map(e=>e.hierarchyLevel))].sort((a,b)=>(a??Infinity)-(b??Infinity));
 return <section className="organisation-structure-editor"><header><div><h3>{org.name} · Structure</h3><small>Internal units belong to this Organisation. Reporting links determine nesting; levels and order control presentation.</small></div><button onClick={()=>open({kind:'organisation',id:org.id})}>Organisation details</button></header>{error&&<p role="alert">{error}</p>}
 <div className="world-toolbar"><button onClick={()=>{setMode('one');setNames('');setShort('');setSequence(false);}}>+ Add one</button><button onClick={()=>{setMode('multiple');setNames('');setShort('');}}>+ Add multiple</button><label><input type="checkbox" checked={includeArchived} onChange={e=>setIncludeArchived(e.target.checked)}/>Include archived structures</label><label><input type="checkbox" checked={units.length>0&&units.every(e=>chosen.includes(e.id))} onChange={e=>setChosen(e.target.checked?units.map(e=>e.id):[])}/>Select all structures</label></div>
 {mode&&<fieldset className="structure-create"><legend>{mode==='one'?'Add one internal structure':'Add multiple internal structures'}</legend><div className="structure-form-grid"><label>Structure type<input list="structure-types" value={type} onChange={e=>setType(e.target.value)}/></label><datalist id="structure-types">{STRUCTURE_TYPES.map(t=><option key={t}>{t}</option>)}</datalist>{mode==='multiple'&&<label>Creation method<select value={sequence?'sequence':'list'} onChange={e=>setSequence(e.target.value==='sequence')}><option value="list">One name per line</option><option value="sequence">Numbered sequence</option></select></label>}
 {mode==='multiple'&&sequence?<><label>Prefix<input value={prefix} onChange={e=>setPrefix(e.target.value)}/></label><label>From<input type="number" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="number" value={to} onChange={e=>setTo(e.target.value)}/></label></>:<label>{mode==='one'?'Structure name':'Names (one per line)'}{mode==='one'?<input value={names} onChange={e=>setNames(e.target.value)}/>:<textarea rows={5} value={names} onChange={e=>setNames(e.target.value)}/>}</label>}
 <label>{mode==='one'?'Structure abbreviation':'Abbreviation pattern (optional)'}<input placeholder={mode==='multiple'?'e.g. T{n}':''} value={short} onChange={e=>setShort(e.target.value)}/></label><label>Initial hierarchy level (optional)<input type="number" min="1" value={level} onChange={e=>setLevel(e.target.value)}/></label><label>Parent / reporting unit<select aria-label="Parent / reporting unit" value={parent} onChange={e=>setParent(e.target.value)}><option value="">Directly inside {org.name}</option>{units.filter(e=>!e.archived).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label></div>
 <div className="structure-preview" aria-label="Structure preview">{preview.map((e,i)=><p key={i}>{e.name}{e.abbreviation?' · '+e.abbreviation:''}</p>)}{previewError&&<small>{previewError}</small>}</div><button disabled={!preview.length} onClick={()=>{try{if(save(createStructures(world,org.id,draft,at))){setMode(undefined);setNames('');}}catch(e){setError(String(e));}}}>Create {preview.length} {type.toLowerCase()}{preview.length===1?'':'s'}</button><button onClick={()=>setMode(undefined)}>Cancel creation</button></fieldset>}
 {chosen.length>0&&<fieldset className="structure-bulk"><legend>{chosen.length} selected · Bulk actions</legend><div className="world-toolbar"><button onClick={()=>shift(chosen,-1)}>Move selected up one level</button><button onClick={()=>shift(chosen,1)}>Move selected down one level</button><button onClick={()=>save(reorderStructures(world,chosen,-1,story,documents,at))}>Move selected earlier among peers</button><button onClick={()=>save(reorderStructures(world,chosen,1,story,documents,at))}>Move selected later among peers</button><label>Bulk hierarchy level<input type="number" min="1" value={bulkLevel} onChange={e=>setBulkLevel(e.target.value)}/></label><button disabled={!bulkLevel||Number(bulkLevel)<1||!Number.isInteger(Number(bulkLevel))} onClick={()=>edit(chosen,{hierarchyLevel:Number(bulkLevel)})}>Set hierarchy level</button><label>Bulk parent / reporting unit<select aria-label="Bulk parent / reporting unit" value={bulkParent} onChange={e=>setBulkParent(e.target.value)}><option value="">Directly inside {org.name}</option>{units.filter(e=>!chosen.includes(e.id)&&!e.archived).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><button onClick={()=>applyParent(chosen,bulkParent)}>Set parent / reporting unit</button><label>Bulk structure type<input list="structure-types" value={bulkType} onChange={e=>setBulkType(e.target.value)}/></label><button disabled={!bulkType.trim()} onClick={()=>edit(chosen,{structureType:bulkType.trim()})}>Set structure type</button><label>Move to Organisation<select aria-label="Move to Organisation" value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Choose Organisation…</option>{world.entities.filter(e=>isOrganisation(e)&&!e.archived&&e.id!==org.id).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><button disabled={!destination} onClick={move}>Move selected structures</button><button onClick={()=>{if(edit(chosen,{archived:true}))setChosen([]);}}>Archive selected structures</button><button onClick={()=>setChosen([])}>Clear selection</button></div><small>Moves include nested units. Personnel history and linked content retain their stable IDs and are not bulk-edited.</small></fieldset>}
 <div className="structure-levels">{levels.map(l=><section key={l??'peers'}><h4>{l===undefined?'Peers · no hierarchy level':'Level '+l}</h4><div className="structure-peer-row">{units.filter(e=>e.hierarchyLevel===l).sort((a,b)=>(a.displayOrder??0)-(b.displayOrder??0)||a.name.localeCompare(b.name)).map(e=><article key={e.id} className={'structure-unit'+(e.archived?' archived':'')}><label><input type="checkbox" checked={chosen.includes(e.id)} onChange={event=>setChosen(event.target.checked?[...chosen,e.id]:chosen.filter(id=>id!==e.id))}/>Select {e.name}</label><button className="structure-unit-name" onClick={()=>open({kind:'structure',id:e.id})}>{e.name}{e.abbreviation?' · '+e.abbreviation:''}</button><small>{e.structureType??'Unit'} · {world.relationships.some(r=>r.from.id===e.id&&r.to.kind==='structure'&&['part of','reports to'].includes(r.type)&&relationshipAt(r,at,story,documents)==='active')?'Reports to ':parents.get(e.id)?.some(p=>p.kind==='structure')?'Displayed under ':''}{parents.get(e.id)?.map(p=>world.entities.find(e=>e.id===p.id)?.name).filter(Boolean).join(', ')||org.name}{e.archived?' · archived':''}</small><div className="world-toolbar"><button aria-label={'Move '+e.name+' up one level'} disabled={e.hierarchyLevel===1} onClick={()=>shift([e.id],-1)}>↑ Level</button><button aria-label={'Move '+e.name+' down one level'} onClick={()=>shift([e.id],1)}>↓ Level</button><button aria-label={'Move '+e.name+' earlier among peers'} disabled={peerIndex(e).index===0} onClick={()=>reorder(e.id,-1)}>← Order</button><button aria-label={'Move '+e.name+' later among peers'} disabled={peerIndex(e).index===peerIndex(e).count-1} onClick={()=>reorder(e.id,1)}>→ Order</button><button className="world-delete-button" onClick={()=>remove({kind:'structure',id:e.id})}>Delete {e.name}…</button></div></article>)}</div></section>)}</div>{!units.length&&<p>No internal structures yet. Add a department, team, command or another structure type here.</p>}
 <PersonnelDefinitions world={world} organisationId={org.id} patch={patch}/>
 </section>;
}
function PersonnelDefinitions({world,organisationId,patch}:{world:WorldRecord;organisationId:string;patch(w:WorldRecord):void}) {
 const [role,setRole]=useState<'rank'|'position'>(),[editing,setEditing]=useState<string>(),[name,setName]=useState(''),[short,setShort]=useState(''),[description,setDescription]=useState(''),[level,setLevel]=useState(''),[allowedRanks,setAllowedRanks]=useState<string[]>([]),[unitIds,setUnitIds]=useState<string[]>([]);
 const entries=(kind:'rank'|'position')=>world.entities.filter(e=>isRole(e,kind)&&(!e.organisationId||e.organisationId===organisationId)).sort((a,b)=>(a.rankLevel??Infinity)-(b.rankLevel??Infinity)||a.name.localeCompare(b.name));
 const begin=(kind:'rank'|'position',entity?:WorldEntity)=>{setRole(kind);setEditing(entity?.id);setAllowedRanks(entity?.allowedRankIds??[]);setUnitIds(entity?.unitIds??[]);setName(entity?.name??'');setShort(entity?.abbreviation??'');setDescription(entity?.description??'');setLevel(entity?.rankLevel?.toString()??(kind==='rank'?String(Math.max(0,...entries('rank').map(e=>e.rankLevel??0))+1):''));};
 const form=(kind:'rank'|'position')=><fieldset className="personnel-definition-form"><legend>{editing?'Edit':'New'} {kind} definition</legend><label>Definition long name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Definition abbreviation<input value={short} onChange={e=>setShort(e.target.value)}/></label><label>Role description<textarea rows={2} value={description} onChange={e=>setDescription(e.target.value)}/></label>{kind==='rank'&&<><label>Hierarchy position<input type="number" min="1" step="1" value={level} onChange={e=>setLevel(e.target.value)}/></label><small>Level 1 is the most senior. Higher numbers are more junior. Ranks with the same number are peers.</small></>}{kind==='position'&&<><Choices label="Allowed ranks" options={entries('rank').filter(e=>!e.archived)} value={allowedRanks} onChange={setAllowedRanks}/><small>No selection means this position can use any rank.</small><Choices label="Available units / teams" options={world.entities.filter(e=>e.kind==='structure'&&e.organisationId===organisationId&&!e.archived)} value={unitIds} onChange={setUnitIds}/><small>No selection means this position is available throughout the Organisation.</small></>}<div className="world-toolbar"><button disabled={!name.trim()||kind==='rank'&&(!level||!Number.isInteger(Number(level))||Number(level)<1)} onClick={()=>{const existing=world.entities.find(e=>e.id===editing);const entity:WorldEntity={...existing,id:editing??crypto.randomUUID(),kind,organisationId:existing?.organisationId??organisationId,name:name.trim(),abbreviation:short.trim()||undefined,description:description.trim(),...(kind==='rank'?{rankLevel:Number(level)}:{allowedRankIds:allowedRanks,unitIds})};patch({...world,entities:editing?world.entities.map(e=>e.id===editing?entity:e):[...world.entities,entity]});setRole(undefined);setEditing(undefined);}}>Save personnel definition</button><button onClick={()=>{setRole(undefined);setEditing(undefined);}}>Cancel personnel definition</button></div></fieldset>;
 return <details className="personnel-definitions"><summary>Personnel definitions · ranks and positions</summary>{(['rank','position'] as const).map(kind=><section className="personnel-section" key={kind}><h4>{kind==='rank'?'Rank / grade definitions':'Position definitions'}</h4>{kind==='rank'&&<p className="personnel-help">Most senior first. Hierarchy positions determine automatic reporting within each internal unit.</p>}<div className="personnel-list">{entries(kind).map(e=><article className="personnel-definition" key={e.id}><div className="personnel-heading"><button onClick={()=>begin(kind,e)}>{e.name}{e.abbreviation?' ('+e.abbreviation+')':''}{e.archived?' · archived':''}</button>{kind==='rank'&&<span>{e.rankLevel===undefined?'Hierarchy not set':'Hierarchy '+e.rankLevel}</span>}</div>{e.description&&<p>{e.description}</p>}<div className="world-toolbar"><button onClick={()=>begin(kind,e)}>Edit {e.name}</button>{kind==='rank'&&<><button aria-label={'Raise '+e.name+' rank'} disabled={e.rankLevel===1} onClick={()=>patch({...world,entities:world.entities.map(x=>x.id===e.id?{...x,rankLevel:Math.max(1,(x.rankLevel??2)-1)}:x)})}>↑ More senior</button><button aria-label={'Lower '+e.name+' rank'} onClick={()=>patch({...world,entities:world.entities.map(x=>x.id===e.id?{...x,rankLevel:(x.rankLevel??0)+1}:x)})}>↓ Less senior</button></>}</div>{role===kind&&editing===e.id&&form(kind)}</article>)}</div><button onClick={()=>begin(kind)}>Add {kind} definition</button>{role===kind&&!editing&&form(kind)}</section>)}</details>;
}
