import { useEffect, useState, useRef } from 'react';
import type { ScreenplayRecord } from '../shared/models';
import type { Appearance, EntityProfile, InspectorContext, StoryPoint } from '../shared/profiles';
import type { StoryEntity, StoryRecord } from '../shared/story';
import { Choices, Notes } from './StoryControls';
import { ChronologyFields } from './StoryControls';
import { sceneHeading } from '../domain/screenplay';
import { ageFromDateOfBirth, appearanceForScene, characterStatistics, dateOfBirthLabel, effectiveRelationships, profileActivity, relationshipDisplayName } from '../domain/profiles';
import { chronologyLabel } from '../domain/story';
import { durationLabel, extractSceneHeading } from '../domain/story-extraction';
import { addScreenplayIdentity, mergeIdentity, separateIdentity } from '../domain/story-identities';
import { MAX_PROFILE_IMAGE_BYTES, RELATIONSHIP_MODIFIERS, RELATIONSHIP_TYPES } from '../shared/profiles';

export function ProfileImage({ projectId, assetId }: { projectId: string; assetId?: string }) {
  const [url, setUrl] = useState('');
  useEffect(() => { let active = true; setUrl(''); if (assetId) void window.desktop.readProjectImage(projectId, assetId).then(url => { if (active) setUrl(url); }).catch(() => {}); return () => { active = false; }; }, [projectId, assetId]);
  return url ? <img className="profile-image" src={url} alt="Profile reference" /> : null;
}

function PointFields({ label, value, story, sceneOptions, onChange }: { label: string; value?: StoryPoint; story: StoryRecord; sceneOptions: { id: string; name: string }[]; onChange(point: StoryPoint | undefined): void }) {
  const mode = value?.sceneId ? 'scene' : value?.eventId ? 'event' : value?.chronology ? 'time' : '';
  const [draftMode, setDraftMode] = useState(mode);
  return <fieldset><legend>{label}</legend><label>Boundary<select aria-label={`${label} boundary`} value={draftMode} onChange={event => { setDraftMode(event.target.value); onChange(undefined); }}><option value="">No boundary</option><option value="scene">Scene chronology</option><option value="event">Event chronology</option><option value="time">Story day / calendar date</option></select></label>
    {draftMode === 'scene' && <Choices label={`${label} scene`} single options={sceneOptions} value={value?.sceneId ? [value.sceneId] : []} onChange={ids => onChange(ids[0] ? { sceneId: ids[0] } : undefined)} />}
    {draftMode === 'event' && <Choices label={`${label} event`} single options={story.events} value={value?.eventId ? [value.eventId] : []} onChange={ids => onChange(ids[0] ? { eventId: ids[0] } : undefined)} />}
    {draftMode === 'time' && <ChronologyFields value={value?.chronology} onChange={chronology => onChange({ chronology })} />}
  </fieldset>;
}

export function ProfileEditor({ context, story, documents, change, navigate, timeline, close, undo, remove, saveStatus }: {
  saveStatus: string; context: InspectorContext; story: StoryRecord; documents: ScreenplayRecord[]; change(story: StoryRecord): void;
  navigate(context: InspectorContext): void; timeline(context: InspectorContext): void; close(): void; undo(): void;
  remove(kind: 'characters' | 'locations', entity: StoryEntity): void;
}) {
  const panel = useRef<HTMLElement>(null);
  useEffect(() => { panel.current?.querySelector<HTMLButtonElement>('button')?.focus(); }, []);
  const kind = context.type === 'character' ? 'characters' : 'locations';
  const entity = story[kind].find(item => item.id === context.entityId);
  const [section, setSection] = useState('Overview'), [descendants, setDescendants] = useState(false), [error, setError] = useState(''), [mergeTarget, setMergeTarget] = useState(''), [newIdentity, setNewIdentity] = useState('');
  const calculatedAge = context.type === 'character' && entity?.profile?.dateOfBirth ? ageFromDateOfBirth(entity.profile.dateOfBirth) : undefined;
  useEffect(() => {
    if (!entity || calculatedAge === undefined || entity.profile?.age === String(calculatedAge)) return;
    change({ ...story, characters: story.characters.map(item => item.id === entity.id ? { ...item, profile: { ...item.profile, age: String(calculatedAge) } } : item) });
  }, [entity?.id, entity?.profile?.dateOfBirth, calculatedAge]);
  if (!entity) return <div className="story-backdrop"><section className="story-panel"><button onClick={close}>Close profile</button><p>This entity is no longer available.</p></section></div>;
  const profile = entity.profile ?? {};
  const update = (patch: Partial<StoryEntity>) => change({ ...story, [kind]: story[kind].map(item => item.id === entity.id ? { ...item, ...patch } : item) });
  const edit = (patch: Partial<EntityProfile>) => update({ profile: { ...profile, ...patch } });
  const sceneOptions = documents.flatMap(document => document.scenes.map((scene, i) => ({ id: scene.id, name: `${document.title} · Scene ${i + 1}: ${sceneHeading(scene, i + 1)}` })));
  const activity = profileActivity(story, documents, context.type as 'character' | 'location', entity.id, descendants);
  const stats = context.type === 'character' ? characterStatistics(story, documents, entity.id) : undefined;
  const fields = context.type === 'character' ? [['fullName','Full name'],['dateOfBirth','Date of birth'],['age','Age / age range'],['occupation','Occupation / role'],['pronouns','Pronouns'],['biography','Biography'],['personality','Personality'],['goals','Goals'],['fears','Fears'],['secrets','Secrets'],['background','Background']] : [['shortName','Short name'],['locationType','Location type'],['structure','Layout / structure'],['atmosphere','Atmosphere'],['visualNotes','Visual notes'],['restrictions','Access / restrictions']];
  const textFields = (keys: string[][], object: object, patch: (value: Record<string, string>) => void) => keys.map(([key, label]) => { const value = String((object as Record<string, unknown>)[key] ?? ''); return <label key={key}>{label}{key === 'dateOfBirth' ? <span className="date-of-birth-control"><input type="date" value={value} onChange={event => { const age = ageFromDateOfBirth(event.target.value); patch({ [key]: event.target.value, ...(age === undefined ? {} : { age: String(age) }) }); }} />{value && <span>{dateOfBirthLabel(value)}</span>}</span> : <textarea value={value} onChange={event => patch({ [key]: event.target.value })} />}</label>; });
  const imageUpload = async (file?: File) => {
    if (!file) return;
    try {
      if (file.size > MAX_PROFILE_IMAGE_BYTES) throw new Error('Choose an image up to 10 MB.');
      const dataUrl = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file); });
      const assetId = await window.desktop.importProjectImage(story.projectId, dataUrl), id = crypto.randomUUID();
      // Asset loading is async: avoid overwriting edits made while the upload was in progress.
      window.dispatchEvent(new CustomEvent('profile-image-imported', { detail: { kind, entityId: entity.id, image: { id, assetId, label: file.name } } }));
      setError('');
    } catch (reason) { setError(String(reason)); }
  };
  const validParents = story.locations.filter(item => {
    let cursor: StoryEntity | undefined = item; const seen = new Set<string>();
    while (cursor && !seen.has(cursor.id)) { if (cursor.id === entity.id) return false; seen.add(cursor.id); cursor = story.locations.find(item => item.id === cursor?.parentId); }
    return true;
  });
  return <div className="story-backdrop profile-backdrop" onKeyDown={event => { event.stopPropagation(); if (event.key === 'Escape') close(); if (event.key === 'Tab') { const nodes = [...(panel.current?.querySelectorAll<HTMLElement>('button,input,select,textarea,summary') ?? [])].filter(node => !node.hasAttribute('disabled') && node.getClientRects().length); const first=nodes[0], last=nodes.at(-1); if(event.shiftKey && document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey && document.activeElement===last){event.preventDefault();first?.focus();} } }}><section ref={panel} role="dialog" aria-modal="true" aria-label={`${context.type} profile`} className="story-panel profile-panel">
    <header><div><h2>{entity.name}</h2><small>{context.type === 'character' ? 'Character profile' : 'Location profile'}{context.sourceSceneId ? ` · ${sceneOptions.find(item => item.id === context.sourceSceneId)?.name ?? 'Removed scene'}` : ''}</small></div><span role="status">{saveStatus}</span><button onClick={undo}>Undo metadata change</button><button onClick={close}>Close profile</button></header>
    <nav>{(context.type === 'character' ? ['Overview','Appearance','Story','Timeline','Relationships','Stats','Images','Notes'] : ['Overview','Structure','Story','Timeline','Images','Notes']).map(name => <button key={name} className={section === name ? 'active' : ''} onClick={() => setSection(name)}>{name}</button>)}</nav>
    <div className="story-body">{error && <p role="alert">{error}</p>}
      {section === 'Overview' && <><div className="profile-form"><label>Display name<input value={entity.name} onChange={event => update({ name: event.target.value })} /></label><label>Short description<textarea value={entity.description} onChange={event => update({ description: event.target.value })} /></label>{textFields(fields, profile, edit)}<label>Aliases / nicknames<input value={profile.aliases?.join(', ') ?? ''} onChange={event => edit({ aliases: event.target.value.split(',').map(value => value.trim()) })} /></label></div>
        {context.type === 'character' && <fieldset><legend>Skills</legend>{profile.skills?.map(skill => <div key={skill.id} className="profile-edit-row"><label>Skill<input value={skill.name} onChange={event => edit({ skills: profile.skills?.map(item => item.id === skill.id ? { ...item, name: event.target.value } : item) })} /></label><label>Skill note<input value={skill.note ?? ''} onChange={event => edit({ skills: profile.skills?.map(item => item.id === skill.id ? { ...item, note: event.target.value } : item) })} /></label><button onClick={() => edit({ skills: profile.skills?.filter(item => item.id !== skill.id) })}>Remove skill</button></div>)}<button onClick={() => edit({ skills: [...profile.skills ?? [], { id: crypto.randomUUID(), name: '' }] })}>Add skill</button></fieldset>}
        <details><summary>Custom fields</summary>{profile.customFields?.map(field => <div className="profile-edit-row" key={field.id}><label>Field name<input value={field.name} onChange={event => edit({ customFields: profile.customFields?.map(item => item.id === field.id ? { ...item, name: event.target.value } : item) })} /></label><label>Value<input value={field.value} onChange={event => edit({ customFields: profile.customFields?.map(item => item.id === field.id ? { ...item, value: event.target.value } : item) })} /></label><button onClick={() => edit({ customFields: profile.customFields?.filter(item => item.id !== field.id) })}>Remove field</button></div>)}<button onClick={() => edit({ customFields: [...profile.customFields ?? [], { id: crypto.randomUUID(), name: '', value: '' }] })}>Add custom field</button></details>
        <details><summary>Screenplay identities and management</summary><p>Screenplay text stays unchanged.</p>{[...new Set(entity.sourceNames ?? [])].map(alias => <p key={alias}>{alias} {alias !== entity.name.toUpperCase() && <button onClick={() => { if (window.confirm(`Separate ${alias} and restore its appearances?`)) { try { change(separateIdentity(story, kind, entity.id, alias, documents)); } catch (reason) { setError(String(reason)); } } }}>Separate identity</button>}</p>)}<div className="profile-edit-row"><label>Add screenplay identity<input aria-label="Add screenplay identity" value={newIdentity} onChange={event => setNewIdentity(event.target.value)} placeholder={context.type === 'character' ? 'Cue name, e.g. SOLICITOR' : 'Heading location'} /></label><button disabled={!newIdentity.trim()} onClick={() => { try { change(addScreenplayIdentity(story, kind, entity.id, newIdentity, documents)); setNewIdentity(''); setError(''); } catch (reason) { setError(String(reason)); } }}>Link identity</button></div><small>Use this when a role, title, disguise or earlier cue is the same canonical {context.type}.</small><Choices label="Merge into" single options={story[kind].filter(item => item.id !== entity.id)} value={mergeTarget ? [mergeTarget] : []} onChange={ids => setMergeTarget(ids[0] ?? '')} /><button disabled={!mergeTarget} onClick={() => { if (window.confirm('Merge these identities and their story relationships? Source profile information remains recoverable. Screenplay text will not change.')) { try { change(mergeIdentity(story, kind, entity.id, mergeTarget)); navigate({ ...context, entityId: mergeTarget }); } catch (reason) { setError(String(reason)); } } }}>Merge identities</button> <button onClick={() => update({ archived: !entity.archived })}>{entity.archived ? 'Unarchive' : 'Archive'}</button> <button onClick={() => remove(kind, entity)}>Delete {context.type}</button></details>
      </>}
      {section === 'Appearance' && <>{appearanceForScene(story, entity, context.sourceSceneId).conflicts.length > 0 && <p role="alert">Conflicting appearances apply to this scene. Select an explicit scene appearance or adjust the ranges.</p>}{profile.appearances?.map(appearance => {
        const patch = (value: Partial<Appearance>) => edit({ appearances: profile.appearances?.map(item => item.id === appearance.id ? { ...item, ...value } : value.isDefault ? { ...item, isDefault: false } : item) });
        return <details key={appearance.id} open><summary>{appearance.name || 'New appearance'}</summary><label>Appearance name<input value={appearance.name} onChange={event => patch({ name: event.target.value })} /></label><label><input type="checkbox" checked={appearance.isDefault ?? false} onChange={event => patch({ isDefault: event.target.checked })} />Default appearance</label><div className="profile-form">{textFields([['description','Description'],['hair','Hair'],['facialHair','Facial hair'],['clothing','Clothing'],['injuries','Injuries'],['marks','Scars / marks'],['accessories','Props / accessories'],['notes','Other notes']], appearance, patch)}</div><Choices label="Specific scenes" options={sceneOptions} value={appearance.sceneIds} onChange={sceneIds => patch({ sceneIds })} /><PointFields label="Applies from" value={appearance.from} story={story} sceneOptions={sceneOptions} onChange={from => patch({ from })} /><PointFields label="Applies until" value={appearance.until} story={story} sceneOptions={sceneOptions} onChange={until => patch({ until })} /><button onClick={() => { if (window.confirm('Delete this appearance? Images remain available.')) edit({ appearances: profile.appearances?.filter(item => item.id !== appearance.id), images: profile.images?.map(item => item.appearanceId === appearance.id ? { ...item, appearanceId: undefined } : item) }); }}>Delete appearance</button></details>;
      })}<button onClick={() => edit({ appearances: [...profile.appearances ?? [], { id: crypto.randomUUID(), name: 'New appearance' }] })}>Add appearance</button></>}
      {section === 'Structure' && <><Choices label="Parent location" single options={validParents} value={entity.parentId ? [entity.parentId] : []} onChange={ids => update({ parentId: ids[0] })} />{(() => { const raw = entity.sourceNames?.find(name => name.includes(' - ')); const parsed = raw ? extractSceneHeading(raw) : undefined; return !entity.parentId && parsed?.parentLocation && parsed.area ? <button onClick={() => { const parent = story.locations.find(item => item.name.toUpperCase() === parsed.parentLocation?.toUpperCase() || item.sourceNames?.includes(parsed.parentLocation!)); const id = parent?.id ?? crypto.randomUUID(); if (window.confirm('Organise ' + entity.name + ' as area ' + parsed.area + ' inside ' + parsed.parentLocation + '? Screenplay text will not change.')) change({ ...story, locations: [...story.locations.map(item => item.id === entity.id ? { ...item, name: parsed.area!, parentId: id } : item), ...(parent ? [] : [{ id, name: parsed.parentLocation!, description: '', sourceNames: [parsed.parentLocation!] }])] }); }}>Organise parent and area from heading</button> : null; })()}<h3>Areas / child locations</h3>{story.locations.filter(item => item.parentId === entity.id).map(item => <button key={item.id} onClick={() => navigate({ ...context, entityId: item.id })}>{item.name}</button>)}<button onClick={() => { const id = crypto.randomUUID(); change({ ...story, locations: [...story.locations, { id, name: 'New area', description: '', parentId: entity.id }] }); navigate({ ...context, entityId: id }); }}>Add area</button><label>Layout / structure<textarea value={profile.structure ?? ''} onChange={event => edit({ structure: event.target.value })} /></label></>}
      {(section === 'Story' || section === 'Timeline') && <>{context.type === 'location' && <label><input type="checkbox" checked={descendants} onChange={event => setDescendants(event.target.checked)} />Include child locations</label>}<button onClick={() => timeline(context)}>View full timeline</button><p>{activity.filter(item => item.kind === 'scene').length} scenes · {activity.filter(item => item.kind === 'event').length} events</p>{section === 'Story' && <><p>Episodes / documents: {[...new Set(activity.map(item => item.screenplayId).filter(Boolean))].map(id => documents.find(item => item.id === id)?.title).join(' · ')}</p>{activity[0] && <p>First chronological activity: {chronologyLabel(activity[0].chronology)} · {activity[0].name}</p>}{activity.at(-1) && <p>Latest chronological activity: {activity.at(-1)?.name}</p>}<p>First screenplay appearance: {sceneOptions.find(option => activity.some(item => item.kind === 'scene' && item.id === option.id))?.name ?? 'No current scene appearance'}</p>{context.type === 'location' && <div>{[...new Set(activity.flatMap(item => item.kind === 'scene' ? item.presentIds ?? [] : []))].map(id => <button key={id} onClick={() => navigate({ type: 'character', entityId: id, sourceSceneId: context.sourceSceneId })}>{story.characters.find(item => item.id === id)?.name} · {activity.filter(item => item.kind === 'scene' && item.presentIds?.includes(id)).length} scenes</button>)}</div>}</>}{activity.map(item => <div className="profile-activity" key={`${item.kind}:${item.id}`}><small>{chronologyLabel(item.chronology)}</small><button onClick={() => navigate({ type: item.kind, entityId: item.id, sourceSceneId: item.sceneId })}>{item.name}</button><p>{item.plotIds?.map(id => <button key={id} onClick={() => navigate({ type: 'plot', entityId: id, sourceSceneId: context.sourceSceneId })}>{story.plots.find(item => item.id === id)?.name}</button>)}{item.locationId && <button onClick={() => navigate({ type: 'location', entityId: item.locationId!, sourceSceneId: item.sceneId })}>{story.locations.find(location => location.id === item.locationId)?.name}</button>}</p></div>)}</>}
      {section === 'Relationships' && <>{story.relationships?.filter(item => item.fromId === entity.id || item.toId === entity.id).map(relation => {
        const patch = (value: object) => change({ ...story, relationships: story.relationships?.map(item => item.id === relation.id ? { ...item, ...value } : item) });
        return <fieldset key={relation.id}><legend>{relationshipDisplayName(relation)}</legend><label>Relationship type<select value={relation.type ?? 'Other'} onChange={event => patch({ type: event.target.value, label: event.target.value })}>{RELATIONSHIP_TYPES.map(type => <option key={type}>{type}</option>)}</select></label><label>Family modifier<select value={relation.modifier ?? ''} onChange={event => patch({ modifier: event.target.value || undefined })}><option value="">None</option>{RELATIONSHIP_MODIFIERS.map(modifier => <option key={modifier} value={modifier}>{modifier}</option>)}</select></label>{relation.type === 'Other' && <label>Relationship label<input value={relation.label} onChange={event => patch({ label: event.target.value })} /></label>}<Choices label="From character" single options={story.characters} value={[relation.fromId]} onChange={ids => ids[0] && patch({ fromId: ids[0] })} /><Choices label="To character" single options={story.characters} value={[relation.toId]} onChange={ids => ids[0] && patch({ toId: ids[0] })} /><label><input type="checkbox" checked={relation.directional ?? false} onChange={event => patch({ directional: event.target.checked })} />One-way relationship</label>{textFields([['description','Description'],['notes','Notes']], relation, patch)}<PointFields label="Relationship starts" value={relation.from} story={story} sceneOptions={sceneOptions} onChange={from => patch({ from })} /><PointFields label="Relationship ends" value={relation.until} story={story} sceneOptions={sceneOptions} onChange={until => patch({ until })} /><PointFields label="Audience discovers relationship" value={relation.audienceDiscoversAt} story={story} sceneOptions={sceneOptions} onChange={audienceDiscoversAt => patch({ audienceDiscoversAt })} /><PointFields label={`${story.characters.find(item => item.id === relation.fromId)?.name ?? 'First character'} discovers relationship`} value={relation.characterDiscoveries?.find(item => item.characterId === relation.fromId)?.at} story={story} sceneOptions={sceneOptions} onChange={at => patch({ characterDiscoveries: [...relation.characterDiscoveries?.filter(item => item.characterId !== relation.fromId) ?? [], ...(at ? [{ characterId: relation.fromId, at }] : [])] })} /><PointFields label={`${story.characters.find(item => item.id === relation.toId)?.name ?? 'Second character'} discovers relationship`} value={relation.characterDiscoveries?.find(item => item.characterId === relation.toId)?.at} story={story} sceneOptions={sceneOptions} onChange={at => patch({ characterDiscoveries: [...relation.characterDiscoveries?.filter(item => item.characterId !== relation.toId) ?? [], ...(at ? [{ characterId: relation.toId, at }] : [])] })} /><button onClick={() => { if (window.confirm('Delete this relationship?')) change({ ...story, relationships: story.relationships?.filter(item => item.id !== relation.id) }); }}>Delete relationship</button></fieldset>;
      })}{effectiveRelationships(story).filter(item => item.derived && item.fromId === entity.id).length > 0 && <fieldset><legend>Automatic reciprocal connections</legend>{effectiveRelationships(story).filter(item => item.derived && item.fromId === entity.id).map(item => <button key={item.id} onClick={() => navigate({ type: 'character', entityId: item.toId, sourceSceneId: context.sourceSceneId })}>{relationshipDisplayName(item)} · {story.characters.find(character => character.id === item.toId)?.name}</button>)}</fieldset>}<button disabled={story.characters.length < 2} onClick={() => change({ ...story, relationships: [...story.relationships ?? [], { id: crypto.randomUUID(), fromId: entity.id, toId: story.characters.find(item => item.id !== entity.id)!.id, type: 'Other', label: 'Other' }] })}>Add relationship</button></>}
      {section === 'Stats' && stats && <><p>{stats.sceneCount} scenes · {stats.episodeCount} screenplay documents · {stats.blocks} dialogue blocks · {stats.words} dialogue words</p><p>Estimated scene presence: {durationLabel(stats.minutes)}</p>{stats.firstScreenplay && <p>First screenplay appearance: {sceneOptions.find(item => item.id === stats.firstScreenplay?.sceneId)?.name} as “{stats.firstScreenplay.cue}”</p>}{stats.firstNamed && <p>First named appearance: {sceneOptions.find(item => item.id === stats.firstNamed?.sceneId)?.name}</p>}{activity[0] && <p>First chronological activity: {chronologyLabel(activity[0].chronology)} · {activity[0].name}</p>}{activity.at(-1) && <p>Latest activity: {activity.at(-1)?.name}</p>}</>}
      {section === 'Images' && <><label>Add image<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={event => { void imageUpload(event.target.files?.[0]); event.target.value = ''; }} /></label><div className="profile-gallery">{profile.images?.map(image => <section key={image.id}><ProfileImage projectId={story.projectId} assetId={image.assetId} /><label>Image label<input value={image.label} onChange={event => edit({ images: profile.images?.map(item => item.id === image.id ? { ...item, label: event.target.value } : item) })} /></label><label>Image notes<textarea value={image.notes ?? ''} onChange={event => edit({ images: profile.images?.map(item => item.id === image.id ? { ...item, notes: event.target.value } : item) })} /></label>{context.type === 'character' && <Choices label="Appearance association" single options={profile.appearances ?? []} value={image.appearanceId ? [image.appearanceId] : []} onChange={ids => edit({ images: profile.images?.map(item => item.id === image.id ? { ...item, appearanceId: ids[0] } : item) })} />}<button onClick={() => edit({ primaryImageId: image.id })}>{profile.primaryImageId === image.id ? 'Primary image' : 'Use as primary'}</button> <button onClick={() => { if (window.confirm('Remove this image from the profile? The managed asset is retained for recovery.')) edit({ images: profile.images?.filter(item => item.id !== image.id), primaryImageId: profile.primaryImageId === image.id ? undefined : profile.primaryImageId }); }}>Remove image</button></section>)}</div></>}
      {section === 'Notes' && <><Notes value={profile.notes} onChange={notes => edit({ notes })} />{story.identityMerges?.filter(item => item.kind === kind && item.targetId === entity.id).map(item => <details key={item.source.id}><summary>Retained profile: {item.source.name}</summary><p>{item.source.description}</p>{Object.entries(item.source.profile ?? {}).filter(([,value]) => typeof value === 'string').map(([key,value]) => <p key={key}>{key}: {String(value)}</p>)}</details>)}</>}
    </div>
  </section></div>;
}
