import { useState } from 'react';
import type { StoryRecord } from '../shared/story';
import type { ScreenplayRecord } from '../shared/models';
import type { WorldKind, WorldLinkContext, WorldRecord, WorldRef } from '../shared/worlds';
import { chronologyLabel } from '../domain/story';
import { screenplayContext } from '../domain/screenplay-context';
import { OrganisationPicker, UnitPicker, WorldSearchSelect } from './WorldLinkControls';

export interface CaptureRelationship { id:string; target:WorldRef; type:string; primary?:boolean; }
export function ScreenplaySourceDetails({source,story}:{source?:import('../shared/worlds').WorldOccurrence['source'];story:StoryRecord}) {
 if(!source)return null;
 return <small>Established from {source.elementType?.replace('_',' ')??'screenplay'}{source.speakerId?' · Speaker: '+(story.characters.find(c=>c.id===source.speakerId)?.name??'Removed Character'):''}{source.locationId?' · Source Location: '+(story.locations.find(l=>l.id===source.locationId)?.name??'Removed Location'):''}{source.chronology?' · '+chronologyLabel(source.chronology):''}</small>;
}
export const CAPTURE_RELATIONSHIPS:Partial<Record<WorldKind,Partial<Record<WorldKind,[string,string][]>>>>={
 vehicle:{character:[['owned by','Owns'],['driven by','Drives'],['passenger','Passenger'],['used by','Uses'],['assigned to','Assigned to'],['accessible to','Has access to']],organisation:[['owned by','Owned by'],['operated by','Operated by'],['assigned to','Assigned to']],location:[['stored at','Stored at'],['usually located at','Usually located at']]},
 object:{character:[['owned by','Owns'],['carried by','Carries'],['used by','Uses'],['created by','Created by'],['assigned to','Assigned to'],['accessible to','Has access to']],organisation:[['belongs to','Belongs to'],['issued by','Issued by']],location:[['located at','Located at']]},
 rule:{character:[['applies to','Applies to']],organisation:[['applies to','Applies to']],structure:[['applies to','Applies to']],location:[['applies to','Applies to']],world:[['applies to','Applies to']]},
 lore:{character:[['used by','Uses'],['created by','Created by'],['known by','Knows']],organisation:[['belongs to','Belongs to']],location:[['used at','Used at']]},
 note:{character:[['about','About']],organisation:[['about','About']],structure:[['about','About']],location:[['about','About']],object:[['about','About']],vehicle:[['about','About']],event:[['about','About']],plot:[['about','About']],rule:[['about','About']],lore:[['about','About']],scene:[['about','About']]},
 event:{character:[['involved','Involved']],organisation:[['involves','Involves']],location:[['associated with','Associated with']]},plot:{character:[['involves','Involves']],event:[['developed by','Developed by']]}
};
export function ScreenplayCaptureContext({story,documents,context,locationOverride,onLocationOverride}:{story:StoryRecord;documents:ScreenplayRecord[];context:WorldLinkContext;locationOverride?:string;onLocationOverride(id?:string):void}) {
 const resolved=screenplayContext(story,documents,context),[overriding,setOverriding]=useState(false);
 const location=story.locations.find(l=>l.id===(locationOverride??resolved.locationId));
 return <fieldset className="screenplay-capture-context"><legend>Created from screenplay</legend><p>{resolved.document?.title??'Screenplay'} · Scene {resolved.scene && resolved.document?resolved.document.scenes.indexOf(resolved.scene)+1:'—'} · {context.type.replace('_',' ')}</p><p>Source Location: {location?.name??'Not established'}</p><p>Story time: {chronologyLabel(resolved.sceneStory?.chronology)||'Not established'}</p>{resolved.speakerId&&<p>Source / Speaker: {story.characters.find(c=>c.id===resolved.speakerId)?.name}</p>}{resolved.characterIds.length>0&&<p>Identified Characters: {resolved.characterIds.map(id=>story.characters.find(c=>c.id===id)?.name).join(', ')}</p>}<label><input type="checkbox" checked={overriding} onChange={e=>{setOverriding(e.target.checked);if(!e.target.checked)onLocationOverride(undefined);}}/>Override source location</label>{overriding&&<WorldSearchSelect label="Source Location" options={story.locations.filter(l=>!l.archived).map(l=>({value:l.id,label:l.name}))} value={locationOverride??resolved.locationId??''} onChange={id=>onLocationOverride(id||undefined)}/>}</fieldset>;
}
export function CaptureRelationships({kind,world,story,documents,relationships,change}:{kind:WorldKind;world?:WorldRecord;story:StoryRecord;documents:ScreenplayRecord[];relationships:CaptureRelationship[];change(r:CaptureRelationship[]):void}) {
 const [custom,setCustom]=useState<string[]>([]);
 const patch=(id:string,update:Partial<CaptureRelationship>)=>change(relationships.map(r=>r.id===id?{...r,...update}:r));
 const allowed=Object.keys(CAPTURE_RELATIONSHIPS[kind]??{}) as WorldKind[];if(allowed.includes('organisation')&&!allowed.includes('structure'))allowed.push('structure');
 const options=(type:WorldKind)=>type==='character'?story.characters:type==='location'?story.locations:type==='event'?story.events:type==='plot'?story.plots:type==='world'?story.worlds??[]:type==='scene'?documents.flatMap(d=>d.scenes.map((s,i)=>({id:s.id,name:d.title+' · Scene '+(i+1)}))):world?.entities.filter(e=>e.kind===type)??[];
 return <fieldset><legend>Relationships</legend>{relationships.map((r,i)=>{const standard=CAPTURE_RELATIONSHIPS[kind]?.[r.target.kind==='structure'?'organisation':r.target.kind]??[['related to','Related to']];const types=[...standard,...world?.relationshipOptions?.filter(o=>o.sourceKind===kind&&o.targetKind===r.target.kind&&!standard.some(([v])=>v===o.label)).map(o=>[o.label,o.label])??[]];return <fieldset key={r.id}><legend>{r.primary?'Primary relationship':'Relationship '+(i+1)}</legend>{r.primary?<p>{options(r.target.kind).find(e=>e.id===r.target.id)?.name}</p>:<><label>Related entry type<select aria-label={'Related entry type '+(i+1)} value={r.target.kind} onChange={e=>patch(r.id,{target:{kind:e.target.value as WorldKind,id:''},type:''})}>{allowed.map(k=><option key={k} value={k}>{k==='organisation'?'Organisation / Structure':k==='location'?'Location':k==='lore'?'Language & Lore':k[0].toUpperCase()+k.slice(1)}</option>)}</select></label>{r.target.kind==='organisation'&&world?<><OrganisationPicker world={world} story={story} documents={documents} value={r.target.id} onChange={id=>patch(r.id,{target:{kind:'organisation',id}})}/>{r.target.id&&<UnitPicker world={world} story={story} documents={documents} organisationId={r.target.id} value={undefined} onChange={id=>{if(id)patch(r.id,{target:{kind:'structure',id}});}}/>}</>:<WorldSearchSelect label={'Related '+(r.target.kind==='location'?'Location':r.target.kind==='character'?'Character':'entry')+' '+(i+1)} options={options(r.target.kind).filter(e=>!('archived' in e)||!e.archived).map(e=>({value:e.id,label:e.name}))} value={r.target.id} onChange={id=>patch(r.id,{target:{...r.target,id}})}/>}</>}
 <label>Relationship<select aria-label={'Relationship '+(i+1)} value={custom.includes(r.id)?'__custom':r.type} onChange={e=>{if(e.target.value==='__custom'){setCustom([...custom,r.id]);patch(r.id,{type:''});}else{setCustom(custom.filter(id=>id!==r.id));patch(r.id,{type:e.target.value});}}}><option value="">Choose relationship</option>{[...types,...r.type&&!types.some(([v])=>v===r.type)?[[r.type,r.type]]:[]].map(([v,l])=><option key={v} value={v}>{l}</option>)}<option value="__custom">Other / Custom</option></select></label>{custom.includes(r.id)&&<label>Custom relationship<input aria-label={'Custom relationship '+(i+1)} value={r.type} onChange={e=>patch(r.id,{type:e.target.value})}/></label>}{!r.primary&&<button onClick={()=>change(relationships.filter(item=>item.id!==r.id))}>Remove relationship</button>}</fieldset>;})}<button onClick={()=>change([...relationships,{id:crypto.randomUUID(),target:{kind:allowed[0]??'character',id:''},type:''}])}>+ Add relationship</button>{<button onClick={()=>change([...relationships,{id:crypto.randomUUID(),target:{kind:'character',id:''},type:kind==='event'?'involved':''}])}>+ Add Character</button>}</fieldset>;
}
