import { EntityRules } from './EntityRules';
// @vitest-environment jsdom
import { cleanup, fireEvent, render } from '@testing-library/react';
import '@testing-library/jest-dom/vitest';
import { afterEach, expect, it, vi } from 'vitest';
import { useState } from 'react';
import { ScreenplayStoryActions } from './ScreenplayStoryActions';
import { migrateStory, resolveEvent } from '../domain/story';
import { createWorld } from '../domain/worlds';
import { worldStateAt } from '../domain/world-history';
import { appearanceForScene } from '../domain/profiles';
import type { StoryRecord } from '../shared/story';
import type { WorldLinkContext } from '../shared/worlds';
import type { ScreenplayRecord } from '../shared/models';

afterEach(cleanup);
const documents = [{id:'d',title:'Episode 1',scenes:[{id:'before',elements:[]},{id:'s',elements:[{id:'cue',type:'character',content:'APPLE'},{id:'a',type:'dialogue',content:'Vara kel’then.'}]}]}] as ScreenplayRecord[];
const context:WorldLinkContext={screenplayId:'d',sceneId:'s',elementId:'a',type:'action',selectedText:'A scar crosses the bonnet.',from:{elementId:'a',offset:0},to:{elementId:'a',offset:26},x:0,y:0};
function setup(initial:StoryRecord, c=context){let latest=initial;const close=vi.fn();function Harness(){const [story,setStory]=useState(initial);return <ScreenplayStoryActions story={story} documents={documents} context={c} change={s=>{latest=s;setStory(s);}} close={close} open={()=>{}}/>;}return {...render(<Harness/>),latest:()=>latest,close};}
function base(){const story=migrateStory(null,'p');story.worlds=[createWorld('Universe')];story.characters=[{id:'apple',name:'Apple Lennox',sourceNames:['APPLE'],description:''}];story.scenes=[{sceneId:'s',screenplayId:'d',chronology:{day:6,time:'09:00'},locationId:'loc'}];return story;}

it('creates one Event, inherits Scene context and assigns Plot development to the Event',()=>{
 const initial=base(),v=setup(initial);fireEvent.click(v.getByRole('button',{name:/Add \/ Update Event/}));fireEvent.change(v.getByLabelText('Name'),{target:{value:'Crash'}});fireEvent.click(v.getByRole('button',{name:'Save Event and choose Plot'}));
 const event=v.latest().events[0];expect(event.occursInSceneId).toBe('s');expect(resolveEvent(v.latest(),event)).toMatchObject({chronology:{day:6,time:'09:00'},locationId:'loc'});
 fireEvent.change(v.getByLabelText('Name'),{target:{value:'Investigation'}});fireEvent.click(v.getByRole('button',{name:'Save'}));expect(v.latest().events).toHaveLength(1);expect(v.latest().events[0].plotIds).toEqual([v.latest().plots[0].id]);expect(v.latest().events[0].plotEffects).toEqual({[v.latest().plots[0].id]:'Developed'});expect(v.latest().scenes[0].plotIds).toBeUndefined();expect(v.latest().worldOccurrences![0].selectedText).toBe(context.selectedText);expect(initial.events).toHaveLength(0);
});
it('updates Vehicle condition from this Scene without changing its base description or screenplay source',()=>{
 const story=base();story.worlds![0].entities=[{id:'car',kind:'vehicle',name:'Apple’s Car',description:'Silver electric car',fields:{Condition:'Pristine'}}];const v=setup(story);
 fireEvent.click(v.getByRole('button',{name:/Object \/ Vehicle/}));fireEvent.change(v.getByLabelText('Entry type'),{target:{value:'vehicle'}});fireEvent.change(v.getByLabelText('Create or update'),{target:{value:'car'}});fireEvent.change(v.getByLabelText('Add selected text to'),{target:{value:'Condition'}});fireEvent.change(v.getByLabelText('Effective'),{target:{value:'point'}});fireEvent.change(v.getByLabelText('Information to save'),{target:{value:'Bonnet scraped'}});fireEvent.click(v.getByRole('button',{name:'Save'}));
 const car=v.latest().worlds![0].entities[0];expect(car.description).toBe('Silver electric car');expect(car.fields!.Condition).toBe('Pristine');expect(worldStateAt(car,v.latest(),documents,{sceneId:'before'}).Condition).toBe('Pristine');expect(worldStateAt(car,v.latest(),documents,{sceneId:'s'}).Condition).toBe('Bonnet scraped');expect(v.latest().worldOccurrences![0].selectedText).toBe(context.selectedText);expect(documents[0].scenes[1].elements[1].content).toBe('Vara kel’then.');
});
it('recognises the Dialogue speaker and captures a dated appearance on the canonical Character',()=>{
 const initial=base();initial.characters[0].profile={appearances:[{id:'old',name:'Old haircut',from:{sceneId:'before'},description:'Long hair'}]};const v=setup(initial,{...context,type:'dialogue'});fireEvent.click(v.getByRole('button',{name:/Update Character Profile/}));expect(v.getByLabelText('Character')).toHaveValue('apple');fireEvent.change(v.getByLabelText('Effective'),{target:{value:'point'}});fireEvent.click(v.getByRole('button',{name:'Save'}));expect(v.latest().characters[0].profile!.appearances![1]).toMatchObject({from:{sceneId:'s'},description:context.selectedText});expect(v.latest().characters).toHaveLength(1);expect(appearanceForScene(v.latest(),v.latest().characters[0],'before',documents).appearance?.description).toBe('Long hair');expect(appearanceForScene(v.latest(),v.latest().characters[0],'s',documents).appearance?.description).toBe(context.selectedText);
});
it('inserts only existing Lore exact wording on explicit invocation',()=>{
 const story=base();story.worlds![0].entities=[{id:'spell',kind:'lore',name:'Binding Spell',description:'',fields:{'Exact wording':'Vara kel’then.','Literal translation':'Be bound','Meaning / usage':'Binding'}}];const insert=vi.fn();window.addEventListener('world-insert-text',insert);
 const v=setup(story,{...context,type:'dialogue',selectedText:undefined,from:undefined,to:undefined});fireEvent.click(v.getByRole('button',{name:/Language & Lore/}));fireEvent.change(v.getByLabelText('Create or update'),{target:{value:'spell'}});expect(insert).not.toHaveBeenCalled();fireEvent.click(v.getByRole('button',{name:'Insert canonical wording into dialogue'}));expect(insert.mock.calls[0][0].detail).toEqual({text:'Vara kel’then.',type:'dialogue'});expect(v.latest().worlds![0].entities).toHaveLength(1);window.removeEventListener('world-insert-text',insert);
});
it('captures a scoped dated Rule on the same World state history',()=>{
 const story=base();const v=setup(story);fireEvent.click(v.getByRole('button',{name:/Character & World Rule/}));fireEvent.change(v.getByLabelText('Name'),{target:{value:'No eating at desks'}});fireEvent.change(v.getByLabelText('Effective'),{target:{value:'point'}});fireEvent.click(v.getByRole('button',{name:'Save Rule'}));expect(v.latest().worlds![0].entities[0].history![0]).toMatchObject({fromPoint:{sceneId:'s'},fields:{Rule:context.selectedText}});expect(v.latest().worlds![0].relationships[0]).toMatchObject({type:'applies to',to:{kind:'world',id:story.worlds![0].id}});
});
it('confirms a transfer and preserves the previous Team membership period',()=>{
 const story=base(),world=story.worlds![0];world.characterIds=['apple'];world.entities=[{id:'org',kind:'organisation',name:'SCU',description:''},{id:'four',kind:'structure',organisationId:'org',name:'Team 4',description:''},{id:'five',kind:'structure',organisationId:'org',name:'Team 5',description:''}];world.relationships=[{id:'old',from:{kind:'character',id:'apple'},to:{kind:'organisation',id:'org'},type:'member of',unitId:'four',fromPoint:{sceneId:'before'}}];
 const v=setup(story,{...context,type:'character',elementId:'cue',from:undefined,to:undefined,selectedText:undefined});fireEvent.click(v.getByRole('button',{name:/Organisation \/ Membership/}));fireEvent.click(v.getByRole('button',{name:'+ Add membership'}));fireEvent.change(v.getByLabelText('Organisation'),{target:{value:'organisation:org'}});fireEvent.change(v.getByLabelText('Internal unit'),{target:{value:'five'}});fireEvent.click(v.getByRole('button',{name:'Save membership'}));expect(v.latest().worlds![0].relationships).toHaveLength(1);expect(v.getByText(/currently assigned to Team 4/)).toBeInTheDocument();fireEvent.click(v.getByRole('button',{name:'Transfer'}));expect(v.latest().worlds![0].relationships).toHaveLength(2);expect(v.latest().worlds![0].relationships[0].untilPoint).toEqual({sceneId:'s'});expect(v.latest().worlds![0].relationships[1]).toMatchObject({unitId:'five',fromPoint:{sceneId:'s'}});
});
it('refuses moving an Event occurrence to another Scene without changing the record',()=>{
 const story=base();story.events=[{id:'event',name:'Crash',description:'Original',occursInSceneId:'before'}];const v=setup(story);fireEvent.click(v.getByRole('button',{name:/Add \/ Update Event/}));fireEvent.change(v.getByLabelText('Create or update'),{target:{value:'event'}});fireEvent.click(v.getByRole('button',{name:'Save Event and choose Plot'}));expect(v.getByRole('alert')).toHaveTextContent('already occurs in another Scene');expect(v.latest()).toBe(story);fireEvent.change(v.getByLabelText('How this Event appears in this Scene'),{target:{value:'revealed'}});fireEvent.click(v.getByRole('button',{name:'Save Event and choose Plot'}));expect(v.latest().events[0]).toMatchObject({occursInSceneId:'before',revealedInSceneIds:['s']});
});
it('shows a small Character menu and requires the relationship when assigning a new Vehicle',()=>{
 const v=setup(base(),{...context,type:'character',elementId:'cue',selectedText:undefined,from:undefined,to:undefined});expect(v.queryByRole('button',{name:/Language & Lore/})).toBeNull();expect(v.queryByRole('button',{name:/Add \/ Update Event/})).toBeNull();expect(v.getByRole('button',{name:/Rules/})).toBeInTheDocument();fireEvent.click(v.getByRole('button',{name:/Assign Object \/ Vehicle/}));expect(v.queryByLabelText('Related Character 1')).toBeNull();expect(v.getByText('Apple Lennox',{selector:'p'})).toBeInTheDocument();fireEvent.change(v.getByLabelText('Entry type'),{target:{value:'vehicle'}});fireEvent.change(v.getByLabelText('Name'),{target:{value:'Apple’s Volvo'}});fireEvent.click(v.getByRole('button',{name:'Save'}));expect(v.getByRole('alert')).toHaveTextContent('Choose an entry and relationship');expect(v.latest().worlds![0].entities).toHaveLength(0);fireEvent.change(v.getByLabelText('Relationship 1'),{target:{value:'owned by'}});fireEvent.click(v.getByRole('button',{name:'Save'}));expect(v.latest().worlds![0].relationships[0]).toMatchObject({type:'owned by',to:{kind:'character',id:'apple'}});expect(v.latest().worlds![0].relationships[0].fromPoint).toBeUndefined();expect(v.latest().worldOccurrences![0].source!.characterIds).toEqual(['apple']);
});
it('keeps the clicked Character as the primary Note subject while allowing another association',()=>{
 const story=base();story.worlds![0].entities=[{id:'bell',kind:'object',name:'Bell',description:''}];const v=setup(story,{...context,type:'character',elementId:'cue',selectedText:undefined,from:undefined,to:undefined});fireEvent.click(v.getByRole('button',{name:/Add Note/}));expect(v.queryByLabelText('Attach Note to')).toBeNull();expect(v.getByText('Primary relationship: Apple Lennox')).toBeInTheDocument();fireEvent.change(v.getByLabelText('Name'),{target:{value:'Nervous habit'}});fireEvent.change(v.getByLabelText('Information to save'),{target:{value:'Taps the bell'}});fireEvent.click(v.getByRole('button',{name:'+ Add relationship'}));fireEvent.change(v.getByLabelText('Related entry type 1'),{target:{value:'object'}});fireEvent.change(v.getByLabelText('Related entry 1'),{target:{value:'bell'}});fireEvent.change(v.getByLabelText('Relationship 1'),{target:{value:'about'}});fireEvent.click(v.getByRole('button',{name:'Save'}));expect(v.latest().worlds![0].relationships.map(r=>r.to)).toEqual([{kind:'character',id:'apple'},{kind:'object',id:'bell'}]);
});
it('defaults Dialogue Events to revelation and stores the speaker as source rather than a participant',()=>{
 const v=setup(base(),{...context,type:'dialogue'});expect(v.queryByRole('button',{name:/Object \/ Vehicle/})).toBeNull();fireEvent.click(v.getByRole('button',{name:/Add \/ Update Event/}));expect(v.getByLabelText('How this Event appears in this Scene')).toHaveValue('revealed');fireEvent.change(v.getByLabelText('Name'),{target:{value:'An earlier crash'}});fireEvent.click(v.getByRole('button',{name:'Save Event and choose Plot'}));expect(v.latest().events[0].occursInSceneId).toBeUndefined();expect(v.latest().events[0].revealedInSceneIds).toEqual(['s']);expect(v.latest().events[0].participantIds).toBeUndefined();expect(v.latest().worldOccurrences![0].source).toMatchObject({speakerId:'apple',locationId:'loc',chronology:{day:6,time:'09:00'}});
});
it('separates source speaker and subject when Dialogue names another Character',()=>{
 const story=base();story.characters.push({id:'gates',name:'Gates',description:''});const v=setup(story,{...context,type:'dialogue',selectedText:'Gates has a scar.'});fireEvent.click(v.getByRole('button',{name:/Update Character Profile/}));expect(v.getByLabelText('Character')).toHaveValue('gates');expect(v.getByText('Source / Speaker: Apple Lennox')).toBeInTheDocument();fireEvent.click(v.getByRole('button',{name:'Save'}));expect(v.latest().characters[1].profile!.appearances![0].description).toBe('Gates has a scar.');expect(v.latest().worldOccurrences![0]).toMatchObject({entity:{kind:'character',id:'gates'},source:{speakerId:'apple',characterIds:['gates']}});
});
it('provides Location actions on headings and only Notes for Transitions',()=>{
 const story=base();story.locations=[{id:'loc',name:'Office',description:''}];const v=setup(story,{...context,type:'scene_heading'});expect(v.queryByRole('button',{name:/Organisation \/ Membership/})).toBeNull();expect(v.queryByRole('button',{name:/Object \/ Vehicle/})).toBeNull();expect(v.getByRole('button',{name:'Open Location'})).toBeInTheDocument();fireEvent.click(v.getByRole('button',{name:/Update Location/}));fireEvent.change(v.getByLabelText('Information to save'),{target:{value:'A cramped office'}});fireEvent.click(v.getByRole('button',{name:'Save'}));expect(v.latest().locations[0].description).toBe('A cramped office');cleanup();const t=setup(base(),{...context,type:'transition'});expect(t.queryByRole('button',{name:/Event/})).toBeNull();expect(t.getByRole('button',{name:/Add Note/})).toBeInTheDocument();
});
it('defaults a linked Vehicle condition change to this point and captures its specific history source',()=>{
 const story=base();story.worlds![0].entities=[{id:'car',kind:'vehicle',name:'Apple’s Car',description:'Silver car'}];story.worldOccurrences=[{id:'prior',entity:{kind:'vehicle',id:'car'},worldId:story.worlds![0].id,screenplayId:'d',sceneId:'s',scope:'text',from:context.from,to:context.to,selectedText:context.selectedText}];const v=setup(story);fireEvent.click(v.getByRole('button',{name:'Update condition'}));expect(v.getByLabelText('Effective')).toHaveValue('point');expect(v.getByLabelText('Create or update')).toHaveValue('car');fireEvent.click(v.getByRole('button',{name:'Save'}));expect(v.latest().worldOccurrences!.at(-1)!.source!.recordId).toBe(v.latest().worlds![0].entities[0].history![0].id);expect(v.latest().worlds![0].entities[0].description).toBe('Silver car');
});
it('captures Dialogue Lore with inherited source context and an explicit source Location override',()=>{
 const story=base();story.locations=[{id:'loc',name:'Office',description:''},{id:'elsewhere',name:'Edinburgh',description:''}];const v=setup(story,{...context,type:'dialogue',selectedText:'Vara kel’then.'});fireEvent.click(v.getByRole('button',{name:/Language & Lore/}));expect(v.getByText('Source Location: Office')).toBeInTheDocument();fireEvent.click(v.getByLabelText('Override source location'));fireEvent.change(v.getByLabelText('Source Location'),{target:{value:'elsewhere'}});fireEvent.change(v.getByLabelText('Name'),{target:{value:'Binding Spell'}});fireEvent.change(v.getByLabelText('Type'),{target:{value:'Spell'}});fireEvent.click(v.getByRole('button',{name:'Save'}));expect(v.latest().worlds![0].entities[0].fields).toMatchObject({Type:'Spell','Exact wording':'Vara kel’then.'});expect(v.latest().worldOccurrences![0].source).toMatchObject({speakerId:'apple',locationId:'elsewhere',chronology:{day:6,time:'09:00'}});expect(v.latest().scenes[0].locationId).toBe('loc');expect(v.latest().worlds![0].relationships).toEqual([]);
});
it('updates existing Plot text while keeping the Plot effect Event-owned',()=>{
 const story=base();story.plots=[{id:'plot',name:'Investigation',description:'Original',color:'red'}];story.events=[{id:'event',name:'Crash',description:'',occursInSceneId:'s',plotIds:['plot']}];const v=setup(story);fireEvent.click(v.getByRole('button',{name:/Add \/ Update Plot/}));fireEvent.change(v.getByLabelText('Create or update'),{target:{value:'plot'}});fireEvent.change(v.getByLabelText('Plot effect'),{target:{value:'Complicated'}});fireEvent.click(v.getByRole('button',{name:'Save'}));expect(v.latest().plots[0].description).toBe('Original\n'+context.selectedText);expect(v.latest().events[0].plotEffects).toEqual({plot:'Complicated'});expect(v.latest().scenes[0].plotIds).toBeUndefined();
});

it('creates a Rule concerning the known cue without reselecting the Character',()=>{
 const story=base(),v=setup(story,{...context,type:'character',elementId:'cue',selectedText:undefined,from:undefined,to:undefined});fireEvent.click(v.getByRole('button',{name:/Character & World Rules/}));fireEvent.click(v.getByRole('button',{name:'Create rule concerning Apple Lennox'}));expect(v.queryByLabelText('Concerns entry 1')).toBeNull();fireEvent.change(v.getByLabelText('Name'),{target:{value:'Eye Contact'}});fireEvent.change(v.getByLabelText('Rule',{exact:true}),{target:{value:'Do not look into Apple’s eyes.'}});fireEvent.change(v.getByLabelText('Exceptions / Conditions'),{target:{value:'Unless Gates is present'}});fireEvent.click(v.getByRole('button',{name:'Save Rule'}));const world=v.latest().worlds![0];expect(world.entities.filter(e=>e.kind==='rule')).toHaveLength(1);expect(world.relationships).toEqual(expect.arrayContaining([expect.objectContaining({type:'concerns',to:{kind:'character',id:'apple'}}),expect.objectContaining({type:'applies to',to:{kind:'world',id:world.id}})]));expect(world.entities[0].fields!.Exceptions).toBe('Unless Gates is present');
});
it('creates a Rule applying to the known Character with a Location concern',()=>{
 const story=base();story.locations=[{id:'room',name:'Interview Room 2',description:''}];const v=setup(story,{...context,type:'character',elementId:'cue',selectedText:undefined,from:undefined,to:undefined});fireEvent.click(v.getByRole('button',{name:/Character & World Rules/}));fireEvent.click(v.getByRole('button',{name:'Create rule applying to Apple Lennox'}));expect(v.queryByLabelText('Applies to entry 1')).toBeNull();fireEvent.change(v.getByLabelText('Name'),{target:{value:'Restricted room'}});fireEvent.change(v.getByLabelText('Rule',{exact:true}),{target:{value:'Must not enter Room 2'}});fireEvent.click(v.getByRole('button',{name:'+ Add concerns'}));fireEvent.change(v.getByLabelText('Concerns type 1'),{target:{value:'location'}});fireEvent.change(v.getByLabelText('Concerns entry 1'),{target:{value:'room'}});fireEvent.change(v.getByLabelText('Effective'),{target:{value:'point'}});fireEvent.click(v.getByRole('button',{name:'Save Rule'}));expect(v.latest().worlds![0].relationships).toEqual(expect.arrayContaining([expect.objectContaining({type:'applies to',to:{kind:'character',id:'apple'},fromPoint:{sceneId:'s'}}),expect.objectContaining({type:'concerns',to:{kind:'location',id:'room'}})]));
});
it('Dialogue Rule identifies the subject without making the speaker a fictional Rule endpoint',()=>{
 const story=base();story.characters.push({id:'zider',name:'Zider Lennox',sourceNames:['Zider'],description:''});const v=setup(story,{...context,type:'dialogue',selectedText:'Nobody looks Zider in the eyes.'});fireEvent.click(v.getByRole('button',{name:/Character & World Rule/}));expect(v.getByLabelText('Concerns entry 1')).toHaveValue('zider');fireEvent.change(v.getByLabelText('Name'),{target:{value:'Eye Contact'}});fireEvent.click(v.getByRole('button',{name:'Save Rule'}));expect(v.latest().worldOccurrences![0].source!.speakerId).toBe('apple');expect(v.latest().worlds![0].relationships.some(r=>r.to.kind==='character'&&r.to.id==='apple')).toBe(false);
});

it('edits the same canonical Rule from a Character Rules section while preserving its other details',()=>{
 const story=base(),world=story.worlds![0];world.entities=[{id:'rule',kind:'rule',name:'Restricted room',description:'No entry',fields:{Exceptions:'With Gates',Custom:'Keep this'},imageIds:['image']}];world.relationships=[{id:'r',from:{kind:'rule',id:'rule'},to:{kind:'character',id:'apple'},type:'applies to'}];let latest=story;function Harness(){const [value,setValue]=useState(story);return <EntityRules story={value} documents={documents} entity={{kind:'character',id:'apple'}} change={next=>{latest=next;setValue(next);}}/>;}const v=render(<Harness/>);fireEvent.click(v.getByRole('button',{name:'Restricted room'}));fireEvent.change(v.getByLabelText('Rule',{exact:true}),{target:{value:'Accompanied entry only'}});fireEvent.click(v.getByRole('button',{name:'Save Rule'}));expect(latest.worlds![0].entities).toHaveLength(1);expect(latest.worlds![0].entities[0]).toMatchObject({id:'rule',description:'Accompanied entry only',fields:{Exceptions:'With Gates',Custom:'Keep this'},imageIds:['image']});expect(latest.worlds![0].relationships).toHaveLength(1);expect(latest.worlds![0].relationships[0]).toMatchObject({id:'r',type:'applies to'});expect(v.getByText('Accompanied entry only')).toBeInTheDocument();
});
