import { RuleEditor } from './RuleEditor';
import { ScreenplayCaptureContext, CaptureRelationships, type CaptureRelationship } from './ScreenplayCaptureContext';
import { applyCaptureRelationships } from '../domain/capture-relationships';
import { useEffect, useRef, useState } from 'react';
import type { StoryRecord, StoryEvent, PlotEffect } from '../shared/story';
import type { ScreenplayRecord } from '../shared/models';
import type { WorldEntity, WorldLinkContext, WorldPoint, WorldRef } from '../shared/worlds';
import { captureSource, contextualActions, eventSceneAction, screenplayContext } from '../domain/screenplay-context';
import { nextPlotColor, PLOT_RELATIONSHIPS } from '../shared/story-config';
import { saveWorldState } from '../domain/world-history';
import { createWorld, compareWorldPoints, validateWorld } from '../domain/worlds';
import { PointFields, RelationshipEditor } from './WorldRelationshipEditor';
import { WorldSearchSelect } from './WorldLinkControls';

type Action = import('../domain/screenplay-context').ScreenplayAction;
const labels: Record<Action,string> = {event:'Add / Update Event',plot:'Add / Update Plot',character:'Update Character Profile',membership:'Organisation / Membership',object:'Object / Vehicle',rule:'Rule',lore:'Language & Lore',note:'Add Note',location:'Update Location'};
const append = (old: string | undefined, text: string) => text ? old ? old + '\n' + text : text : old ?? '';
export function ScreenplayStoryActions({story,documents,context,currentWorldId,change,close,open}:{story:StoryRecord;documents:ScreenplayRecord[];context:WorldLinkContext;currentWorldId?:string;change(s:StoryRecord):void;close():void;open(worldId:string,ref:WorldRef):void}) {
 const dialog=useRef<HTMLElement>(null);
 useEffect(()=>{dialog.current?.querySelector<HTMLElement>('button')?.focus({preventScroll:true});},[]);
 const resolved = screenplayContext(story,documents,context);
 const characterWorlds=story.worlds?.filter(w=>!w.archived&&(w.characterIds.includes(resolved.characterId??'')||w.relationships.some(r=>r.from.kind==='character'&&r.from.id===resolved.characterId)))??[];
 const [action,setAction]=useState<Action>(),[worldId,setWorldId]=useState(resolved.occurrences.find(o=>o.worldId)?.worldId ?? resolved.recognised?.worldId ?? (characterWorlds.length===1?characterWorlds[0].id:undefined) ?? currentWorldId ?? story.worlds?.[0]?.id ?? ''),[targetId,setTargetId]=useState(''),[characterId,setCharacterId]=useState(resolved.characterId??''),[name,setName]=useState(''),[text,setText]=useState(context.selectedText??''),[query,setQuery]=useState(''),[destination,setDestination]=useState('Description'),[kind,setKind]=useState<'object'|'vehicle'>('object'),[period,setPeriod]=useState('always'),[from,setFrom]=useState<WorldPoint|undefined>(resolved.point),[until,setUntil]=useState<WorldPoint>(),[eventAction,setEventAction]=useState('occurs'),[eventId,setEventId]=useState(''),[effect,setEffect]=useState<PlotEffect>('Developed'),[scope,setScope]=useState<WorldRef>({kind:'scene',id:context.sceneId}),[fields,setFields]=useState<Record<string,string>>({}),[error,setError]=useState('');
 const [relationships,setRelationships]=useState<CaptureRelationship[]>([]),[sourceLocation,setSourceLocation]=useState<string>();
 const [ruleMenu,setRuleMenu]=useState(false),[ruleMeaning,setRuleMeaning]=useState<'applies to'|'concerns'>('concerns');
 const world=story.worlds?.find(w=>w.id===worldId), character=story.characters.find(c=>c.id===characterId);
 const linked=resolved.occurrences.find(o=>['object','vehicle','lore'].includes(o.entity.kind))??resolved.recognised;
 const events=story.events.filter(e=>e.occursInSceneId===context.sceneId || e.revealedInSceneIds?.includes(context.sceneId) || e.referencedInSceneIds?.includes(context.sceneId) || e.sceneInteractions?.some(i=>i.sceneId===context.sceneId));
 const candidates=(action==='event'?story.events:action==='plot'?story.plots:(world?.entities??[]).filter(e=>action==='object'?e.kind===kind:e.kind===action)).filter(e=>!e.archived && JSON.stringify(e).toLowerCase().includes(query.toLowerCase()));
 const choose=(a:Action, dest?:string)=>{setAction(a);setError('');setName('');setFields({});setQuery('');setText(context.type==='character'&&a==='object'?'':context.selectedText??(['action','dialogue','scene_heading'].includes(context.type)?resolved.element?.content??'':''));setFrom(resolved.point);setPeriod(a==='object'&&['Appearance','Condition','Ownership / relationship'].includes(dest??'')?'point':'always');setUntil(undefined);setEventAction(['dialogue','parenthetical'].includes(context.type)?'revealed':'occurs');setRelationships(a==='object'&&dest==='Ownership / relationship'?[{id:crypto.randomUUID(),target:{kind:'character',id:resolved.characterIds[0]??''},type:''}]:a==='event'?resolved.characterIds.map(id=>({id:crypto.randomUUID(),target:{kind:'character' as const,id},type:'involved'})):a==='object'&&context.type==='character'&&resolved.characterId?[{id:crypto.randomUUID(),target:{kind:'character',id:resolved.characterId},type:'',primary:true}]:[]);setScope(a==='rule'?(context.type==='scene_heading'&&resolved.locationId?{kind:'location',id:resolved.locationId}:{kind:'world',id:worldId}):a==='note'?(linked?.entity??(context.type==='scene_heading'&&resolved.locationId?{kind:'location',id:resolved.locationId}:context.type==='character'&&characterId?{kind:'character',id:characterId}:{kind:'scene',id:context.sceneId})):{kind:'scene',id:context.sceneId});setDestination(dest??(a==='lore'?'Exact wording':a==='character'?'Appearance':'Description'));const match=resolved.occurrences.find(o=>a==='object'?['object','vehicle'].includes(o.entity.kind):o.entity.kind===a)??(linked&&(a==='object'?['object','vehicle'].includes(linked.entity.kind):linked.entity.kind===a)?linked:undefined);setTargetId(match?.entity.id??'');if(match?.worldId)setWorldId(match.worldId);if(match?.entity.kind==='vehicle')setKind('vehicle');if(a==='plot')setEventId(resolved.occurrences.find(o=>o.entity.kind==='event')?.entity.id??(events.length===1?events[0].id:''));};
 const openCharacter=()=>{close();window.dispatchEvent(new CustomEvent('open-story-profile',{detail:{type:'character',entityId:characterId,sourceSceneId:context.sceneId,full:true}}));};
 const insertLore=(id:string)=>{const wording=world?.entities.find(e=>e.id===id)?.fields?.['Exact wording'];if(!wording){setError('This entry has no exact wording.');return;}if(context.type!=='dialogue'||resolved.scene?.locked){setError('Place the cursor in unlocked Dialogue before inserting wording.');return;}close();window.dispatchEvent(new CustomEvent('world-insert-text',{detail:{text:wording,type:'dialogue'}}));};
 const save=()=>{try{
   if(!text.trim() && action!=='plot' && !(action==='object'&&relationships.length))throw Error('Enter the information to save.');
   if(period!=='always' && !from)throw Error('Choose when this change begins.');if(period==='custom'&&from&&until&&(compareWorldPoints(from,until,story,documents)??-1)>=0)throw Error('The end must be after the start.');
   let next=story;let ref:WorldRef;let recordId:string|undefined;const id=targetId||crypto.randomUUID();
   if(action==='event') {
    const old=story.events.find(e=>e.id===id);if(!old&&!name.trim())throw Error('Give the Event a name.');
    const event:StoryEvent=eventSceneAction(old?{...old,description:append(old.description,text)}:{id,name:name.trim(),description:text,contextOverrides:[],occurrenceTiming:{mode:'inherit'}},context.sceneId,eventAction);
    next={...story,scenes:story.scenes.some(s=>s.sceneId===context.sceneId)?story.scenes:[...story.scenes,resolved.sceneStory],events:[...story.events.filter(e=>e.id!==id),event]};ref={kind:'event',id};
   }else if(action==='plot') {
    if(!targetId&&!name.trim())throw Error('Give the Plot a name.');
    next=targetId?{...story,plots:story.plots.map(p=>p.id===id?{...p,description:append(p.description,text)}:p)}:{...story,plots:[...story.plots,{id,name:name.trim(),description:text,color:nextPlotColor(story.plots)}]};
    if(eventId)next={...next,events:next.events.map(e=>e.id===eventId?{...e,plotIds:[...new Set([...e.plotIds??[],id])],plotEffects:{...e.plotEffects,[id]:effect}}:e)};
    else {if(events.some(e=>e.plotIds?.includes(id)))throw Error('This Plot already develops through an Event here. Choose that Event to update its Plot effect.');const scene=resolved.sceneStory??{sceneId:context.sceneId,screenplayId:context.screenplayId};next={...next,scenes:[...next.scenes.filter(s=>s.sceneId!==context.sceneId),{...scene,plotIds:[...new Set([...scene.plotIds??[],id])],plotRoles:{...scene.plotRoles,[id]:effect},manualFields:[...new Set([...scene.manualFields??[],'plotIds'])]}]};}
    ref={kind:'plot',id};
   }else if(action==='location') {
    const location=story.locations.find(l=>l.id===resolved.locationId);if(!location)throw Error('This Scene has no established Location. Set its Location from the Scene Heading first.');let updated=location;if(destination==='Description')updated={...location,description:append(location.description,text)};else {const key=destination==='Appearance'?'visualNotes':destination==='Access restrictions'?'restrictions':'notes';updated={...location,profile:{...location.profile,[key]:append(location.profile?.[key],text)}};}next={...story,locations:story.locations.map(l=>l.id===location.id?updated:l)};ref={kind:'location',id:location.id};
   }else if(action==='character') {
    if(!character)throw Error('Choose a Character.');const profile={...character.profile};
    if(destination==='Appearance') {const old=profile.appearances?.find(a=>a.isDefault);profile.appearances=period==='always'?[...profile.appearances?.filter(a=>a.id!==old?.id)??[],{...old,id:old?.id??crypto.randomUUID(),name:old?.name??'General appearance',isDefault:true,description:append(old?.description,text)}]:[...profile.appearances?.map(a=>!a.isDefault&&!a.until&&(!a.from||(compareWorldPoints(a.from,from!,story,documents)??1)<0)?{...a,until:from}:a)??[],{id:crypto.randomUUID(),name:name.trim()||'Appearance change',from,until,description:text}];}
    else if(destination==='Skills')profile.skills=[...profile.skills??[],{id:crypto.randomUUID(),name:text}];
    else {const key=destination==='Occupation / role'?'occupation':destination==='Traits'?'personality':'notes';profile[key]=append(profile[key],text);}
    next={...story,characters:story.characters.map(c=>c.id===character.id?{...c,profile}:c)};ref={kind:'character',id:character.id};
   }else {
    if(!world)throw Error('Choose a Project World.');const entity=world.entities.find(e=>e.id===id);if(!entity&&!name.trim())throw Error('Give the entry a name.');
    const entityKind=action==='object'?kind:action==='rule'?'rule':action==='lore'?'lore':'note';
    let updated:WorldEntity=entity??{id,kind:entityKind,name:name.trim(),description:'',fields:{}};
    if(action==='lore')updated={...updated,fields:{...updated.fields,...fields,[destination]:text}};
    else if(action==='object' && ['Appearance','Condition'].includes(destination) && period!=='always')updated={...updated,history:saveWorldState(updated,{id:crypto.randomUUID(),fromPoint:from,untilPoint:until,fields:{[destination]:text}},story,documents)};
    else if(action==='rule' && period!=='always')updated={...updated,fields:{...updated.fields,...fields},history:saveWorldState(updated,{id:crypto.randomUUID(),fromPoint:from,untilPoint:until,fields:{Rule:text}},story,documents)};
    else if(destination==='Description'||action==='note')updated={...updated,description:append(updated.description,text),fields:{...updated.fields,...fields}};
    else if(destination==='Ownership / relationship'||destination==='Location'){/* The Relationships section owns this edit. */}
    else updated={...updated,fields:{...updated.fields,...fields,[destination]:append(updated.fields?.[destination],text)}};
    const relation=action==='rule'?'applies to':action==='note'?'about':destination==='Location'?'located at':undefined;
    let updatedWorld={...world,entities:[...world.entities.filter(e=>e.id!==id),updated]};
    if(relation)updatedWorld={...updatedWorld,characterIds:[...new Set([...world.characterIds,...scope.kind==='character'?[scope.id]:[]])],locationIds:[...new Set([...world.locationIds,...scope.kind==='location'?[scope.id]:[]])],relationships:[...world.relationships.map(r=>period!=='always'&&r.from.id===id&&r.type===relation&&!r.untilPoint?{...r,untilPoint:from}:r),{id:crypto.randomUUID(),from:{kind:entityKind,id},to:scope,type:relation,fromPoint:period==='always'?undefined:from,untilPoint:period==='custom'?until:undefined}]};
    next={...story,worlds:story.worlds?.map(w=>w.id===world.id?updatedWorld:w)};validateWorld(updatedWorld,next,documents);ref={kind:entityKind,id};
   }
   if(period!=='always')recordId=ref.kind==='character'?next.characters.find(c=>c.id===ref.id)?.profile?.appearances?.at(-1)?.id:next.worlds?.find(w=>w.id===world?.id)?.entities.find(e=>e.id===ref.id)?.history?.at(-1)?.id;
   next=applyCaptureRelationships(next,world?.id,ref,relationships,period==='always'?undefined:from,period==='custom'?until:undefined,action==='object'&&destination==='Ownership / relationship'?{documents}:undefined);
   next=captureSource(next,context,ref,world?.id,documents,{...(sourceLocation?{locationId:sourceLocation}:{}),recordId});change(next);setError('');
   if(action==='event'){setRelationships([]);setAction('plot');setEventId(ref.id);setTargetId('');setName('');setText('');}else close();
 }catch(e){setError(String(e));}};
 const order=contextualActions(context.type,resolved.characterId,linked?.entity);
 const temporal=(action==='character'&&destination==='Appearance')||action==='rule'||(action==='object'&&['Appearance','Condition','Ownership / relationship','Location'].includes(destination));
 return <div className="world-backdrop"><section ref={dialog} className="world-link-dialog" role="dialog" aria-modal="true" aria-label="Story and World actions" onKeyDown={e=>{e.stopPropagation();if(e.key==='Escape')close();if(e.key==='Tab'){const controls=[...dialog.current?.querySelectorAll<HTMLElement>('button,input,textarea,select,summary')??[]].filter(n=>!n.hasAttribute('disabled')&&n.getClientRects().length);const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}><header><h2>{action?labels[action]:linked?world?.entities.find(e=>e.id===linked.entity.id)?.name:context.type==='character'?character?.name??'Character':context.type==='scene_heading'?story.locations.find(l=>l.id===resolved.locationId)?.name??'Scene Location':context.type==='dialogue'?'Dialogue':'Story & World'}</h2><button onClick={close}>Close</button></header>
 {!action?<><p>Choose what this screenplay information means.</p>{linked&&<fieldset><legend>{world?.entities.find(e=>e.id===linked.entity.id)?.name}</legend><button onClick={()=>{close();open(linked.worldId??worldId,linked.entity);}}>Open entry / View history</button>{linked.entity.kind!=='lore'&&<button onClick={()=>choose('object','Ownership / relationship')}>Change Character relationship</button>}{linked.entity.kind==='lore'&&<><button disabled={context.type!=='dialogue'} onClick={()=>insertLore(linked.entity.id)}>Insert canonical wording</button><button onClick={()=>choose('lore','Meaning / usage')}>Update meaning</button><details><summary>View translation</summary><p>{world?.entities.find(e=>e.id===linked.entity.id)?.fields?.['Literal translation']??'No translation recorded'}</p></details></>}{linked.entity.kind!=='lore'?['Description','Appearance','Condition'].map(d=><button key={d} onClick={()=>choose('object',d)}>Update {d.toLowerCase()}</button>):<button onClick={()=>choose('lore')}>Update entry / Insert wording</button>}</fieldset>}{ruleMenu&&character&&<fieldset><legend>{character.name} · Rules</legend><button onClick={()=>{setRuleMeaning('concerns');choose('rule');}}>Create rule concerning {character.name}</button><button onClick={()=>{setRuleMeaning('applies to');choose('rule');}}>Create rule applying to {character.name}</button><button onClick={()=>{close();window.dispatchEvent(new CustomEvent('open-story-profile',{detail:{type:'character',entityId:character.id,sourceSceneId:context.sceneId,full:true,section:'Rules'}}));}}>View {character.name}'s rules</button></fieldset>}<nav>{order.filter(a=>a!=='membership'||!!characterId).map(a=><button key={a} onClick={()=>{if(a==='rule'&&context.type==='character')setRuleMenu(true);else choose(a);}}><small>{['event','plot'].includes(a)?'Story':'Character & World'}</small>{a==='object'&&context.type==='character'?'Assign Object / Vehicle':context.type==='scene_heading'?a==='note'?'Location Note':a==='rule'?'Add Rule for Location':labels[a]:context.type==='character'&&a==='rule'?'Rules':labels[a]}</button>)}</nav>{context.type==='character'&&character&&<button onClick={openCharacter}>Open Character Profile</button>}{context.type==='scene_heading'&&resolved.locationId&&<button onClick={()=>{close();window.dispatchEvent(new CustomEvent('open-story-profile',{detail:{type:'location',entityId:resolved.locationId,sourceSceneId:context.sceneId,full:true}}));}}>Open Location</button>}{context.type==='scene_heading'&&world&&<button onClick={()=>{close();open(world.id,{kind:'world',id:world.id});}}>World / Organisation</button>}</>:<>
 <button onClick={()=>setAction(undefined)}>Back to actions</button>{action!=='rule'&&<ScreenplayCaptureContext story={story} documents={documents} context={context} locationOverride={sourceLocation} onLocationOverride={setSourceLocation}/>}{action!=='rule'&&context.selectedText&&<><h4>Selected screenplay text</h4><blockquote>{context.selectedText}</blockquote></>}
 {['character','membership'].includes(action)&&(context.type==='character'&&resolved.characterId?<p>Subject Character: {character?.name}</p>:<label>{action==='character'?'Subject Character':'Character'}<select aria-label="Character" value={characterId} onChange={e=>setCharacterId(e.target.value)}><option value="">Choose Character</option>{story.characters.filter(c=>!c.archived).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>)}
 {action==='location'&&<p>Location: {story.locations.find(l=>l.id===resolved.locationId)?.name??'Not established'}</p>}
 {!['character','location'].includes(action)&&<><label>Project World<select value={worldId} onChange={e=>{setWorldId(e.target.value);setTargetId('');if(action==='rule')setScope({kind:'world',id:e.target.value});}}><option value="">Choose World</option>{story.worlds?.filter(w=>!w.archived).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label>{!world&&<fieldset><legend>Create a Project World</legend><label>World name<input value={name} onChange={e=>setName(e.target.value)}/></label><button disabled={!name.trim()} onClick={()=>{const w=createWorld(name);change({...story,worlds:[...story.worlds??[],w]});setWorldId(w.id);setName('');if(action==='rule')setScope({kind:'world',id:w.id});}}>Create World</button></fieldset>}</>}
 {action==='rule'?world&&<><WorldSearchSelect label="Create or update Rule" value={targetId} options={world.entities.filter(e=>e.kind==='rule'&&!e.archived).map(e=>({value:e.id,label:e.name}))} empty="Create new Rule" onChange={setTargetId}/><RuleEditor key={world.id+targetId+ruleMeaning} story={story} documents={documents} worldId={world.id} entity={world.entities.find(e=>e.id===targetId)} context={context} primary={context.type==='character'&&character?{target:{kind:'character',id:character.id},meaning:ruleMeaning}:context.type==='scene_heading'&&resolved.locationId?{target:{kind:'location',id:resolved.locationId},meaning:'applies to'}:undefined} change={change} done={close}/></>:action==='membership'?world&&character&&<RelationshipEditor world={world} story={story} documents={documents} selected={{kind:'character',id:character.id}} membershipOnly contextualCapture at={from} patch={w=>{validateWorld(w,story,documents);change(captureSource({...story,worlds:story.worlds?.map(x=>x.id===w.id?w:x)},context,{kind:'character',id:character.id},w.id,documents,{recordId:w.relationships.find(r=>!world.relationships.some(old=>old.id===r.id))?.id,...(sourceLocation?{locationId:sourceLocation}:{})}));}} open={ref=>{close();open(world.id,ref);}}/>:<>
 {action==='object'&&<label>Entry type<select value={kind} onChange={e=>{setKind(e.target.value as typeof kind);setTargetId('');}}><option value="object">Object</option><option value="vehicle">Vehicle</option></select></label>}
 {!['character','location'].includes(action)&&<><label>Search existing<input value={query} onChange={e=>setQuery(e.target.value)}/></label><label>{action==='note'?'Note':'Create or update'}<select value={targetId} onChange={e=>setTargetId(e.target.value)}><option value="">Create new</option>{candidates.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>{!targetId&&<label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label>}</>}
 {action==='event'&&<label>How this Event appears in this Scene<select value={eventAction} onChange={e=>setEventAction(e.target.value)}>{[['occurs','Occurs'],['revealed','Revealed'],['referenced','Referenced'],['investigated','Investigated'],['new_evidence','New evidence'],['reinterpreted','Reinterpreted']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
 {action==='plot'&&<><label>Plot development belongs to<select value={eventId} onChange={e=>setEventId(e.target.value)}><option value="">This Scene</option>{events.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Plot effect<select value={effect} onChange={e=>setEffect(e.target.value as PlotEffect)}>{PLOT_RELATIONSHIPS.map(p=><option key={p}>{p}</option>)}</select></label></>}
 {['object','character','lore','location'].includes(action)&&<label>Add selected text to<select value={destination} onChange={e=>{setDestination(e.target.value);if(e.target.value==='Location')setScope({kind:'location',id:resolved.locationId??''});if(action==='object'&&['Appearance','Condition'].includes(e.target.value))setPeriod('point');if(action==='object'&&e.target.value==='Ownership / relationship'&&!relationships.length)setRelationships([{id:crypto.randomUUID(),target:{kind:'character',id:resolved.characterIds[0]??''},type:''}]);}}>{(action==='character'?['Appearance','Occupation / role','Skills','Traits','Notes']:action==='lore'?['Exact wording','Meaning / usage','Notes']:action==='location'?['Description','Appearance','Access restrictions','Notes']:['Description','Appearance','Condition','Notes','Ownership / relationship','Location']).map(d=><option key={d}>{d}</option>)}</select></label>}
 {temporal&&<><label>Effective<select value={period} onChange={e=>{setPeriod(e.target.value);setFrom(resolved.point);setUntil(undefined);}}><option value="always">{action==='character'?'General appearance':'Always'}</option><option value="point">From this point</option><option value="custom">Custom effective period</option></select></label>{period!=='always'&&<PointFields label="Starts" value={from} onChange={setFrom} documents={documents} story={story}/>} {period==='custom'&&<PointFields label="Ends before" value={until} onChange={setUntil} documents={documents} story={story}/>}</>}
 {(action==='note'||['Location'].includes(destination))&&world&&!(action==='note'&&(context.type==='character'||context.type==='scene_heading'||linked))&&<WorldSearchSelect label={action==='note'?'Attach Note to':destination} value={scope.kind+':'+scope.id} options={[...(destination==='Location'?[]:[{value:'scene:'+context.sceneId,label:'This Scene'}]),{value:'world:'+world.id,label:world.name},...world.entities.map(e=>({value:e.kind+':'+e.id,label:e.name})),...story.characters.map(e=>({value:'character:'+e.id,label:e.name})),...story.locations.map(e=>({value:'location:'+e.id,label:e.name})),...story.events.map(e=>({value:'event:'+e.id,label:e.name})),...story.plots.map(e=>({value:'plot:'+e.id,label:e.name}))].filter(o=>destination==='Location'?o.value.startsWith('location:'):true)} onChange={v=>{const [kind,id]=v.split(':');setScope({kind:kind as WorldRef['kind'],id});}}/>}
 {action==='lore'&&['Type','Language','Literal translation','Meaning / usage','Pronunciation','Variants','Notes'].map(f=><label key={f}>{f}<input value={fields[f]??''} onChange={e=>setFields({...fields,[f]:e.target.value})}/></label>)}
 {action==='note'&&<p>Primary relationship: {scope.kind==='character'?story.characters.find(c=>c.id===scope.id)?.name:scope.kind==='location'?story.locations.find(l=>l.id===scope.id)?.name:scope.kind==='scene'?'This Scene':world?.entities.find(e=>e.id===scope.id)?.name}</p>}{targetId&&<div>Existing information: {candidates.find(e=>e.id===targetId)?.description}{action==='lore'&&<blockquote>{world?.entities.find(e=>e.id===targetId)?.fields?.['Exact wording']}<br/>{world?.entities.find(e=>e.id===targetId)?.fields?.['Literal translation']}<br/>{world?.entities.find(e=>e.id===targetId)?.fields?.['Meaning / usage']}</blockquote>}</div>}
 {['event','plot','object','rule','lore','note'].includes(action)&&<CaptureRelationships kind={action==='object'?kind:action as WorldRef['kind']} world={world} story={story} documents={documents} relationships={relationships} change={setRelationships}/>}
 <label>{action==='plot'?'Plot description':'Information to save'}<textarea value={text} onChange={e=>setText(e.target.value)}/></label><small>Saving this information keeps the screenplay wording as written.</small>
 {action==='lore'&&context.type==='dialogue'&&targetId&&<button onClick={()=>{const wording=world?.entities.find(e=>e.id===targetId)?.fields?.['Exact wording'];if(!wording){setError('This entry has no exact wording.');return;}if(resolved.scene?.locked){setError('Unlock this Scene before inserting wording.');return;}close();window.dispatchEvent(new CustomEvent('world-insert-text',{detail:{text:wording,type:'dialogue'}}));}}>Insert canonical wording into dialogue</button>}
 <button onClick={save}>{action==='event'?'Save Event and choose Plot': 'Save'}</button>{action==='plot'&&eventId&&<button onClick={close}>Done without Plot</button>}</>}
 </>}{error&&<p role="alert">{error}</p>}</section></div>;
}
