// @vitest-environment jsdom
import { cleanup, fireEvent, render, within, act } from '@testing-library/react';
import '@testing-library/jest-dom/vitest';
import { afterEach, expect, it, vi } from 'vitest';
import { useState } from 'react';
import { WorldWorkspace } from './WorldWorkspace';
import { WorldEntityContext } from './WorldEntityContext';
import { createWorld } from '../domain/worlds';
import { migrateStory } from '../domain/story';
import type { StoryRecord } from '../shared/story';
afterEach(cleanup);
it('explicitly converts an ambiguous Organisation while preserving its ID, membership, occurrence and footer pin',()=>{
 const story=migrateStory(null,'p'),w=createWorld('Universe');w.entities=[{id:'owner',kind:'organisation',name:'SCU',description:''},{id:'ambiguous',kind:'organisation',name:'Special Projects',description:'Keep this description'}];story.characters=[{id:'apple',name:'Apple',description:''}];w.relationships=[{id:'m',type:'member of',from:{kind:'character',id:'apple'},to:{kind:'organisation',id:'ambiguous'},untilPoint:{chronology:{day:4}}}];story.worlds=[w];story.worldOccurrences=[{id:'o',worldId:w.id,entity:{kind:'organisation',id:'ambiguous'},scope:'scene',sceneId:'s',screenplayId:'d'}];story.worldUi={pins:[{worldId:w.id,entity:{kind:'organisation',id:'ambiguous'}}]};let latest=story;
 const view=render(<Harness initial={story} onChange={s=>latest=s}/>);fireEvent.click(within(view.container.querySelector('.writing-header')!).getByRole('button',{name:'Worlds'}));const d=within(view.getByRole('dialog',{name:'Worlds workspace'}));fireEvent.click(d.getByRole('button',{name:'Organisations'}));fireEvent.click(d.getByRole('button',{name:'Special Projects Keep this description'}));fireEvent.change(d.getByLabelText('Owning Organisation'),{target:{value:'owner'}});fireEvent.click(d.getByRole('button',{name:'Convert to internal structure'}));expect(latest.worlds![0].entities.find(e=>e.id==='ambiguous')).toMatchObject({kind:'structure',organisationId:'owner',description:'Keep this description'});expect(latest.worlds![0].relationships[0]).toMatchObject({id:'m',unitId:'ambiguous',to:{kind:'organisation',id:'owner'},untilPoint:{chronology:{day:4}}});expect(latest.worldOccurrences![0].entity).toEqual({kind:'structure',id:'ambiguous'});expect(latest.worldUi!.pins[0].entity).toEqual({kind:'structure',id:'ambiguous'});
});
it('creates rank and position definitions with visible forms and saves shared membership', () => {
 const story=migrateStory(null,'p'),w=createWorld('Universe'); story.characters=[{id:'apple',name:'Apple',description:''}]; w.characterIds=['apple']; w.entities=[{id:'police',kind:'organisation',name:'Police Scotland',description:''}]; story.worlds=[w]; let latest=story;
 const view=render(<Harness initial={story} onChange={s=>latest=s}/>); fireEvent.click(within(view.container.querySelector('.writing-header')!).getByRole('button',{name:'Worlds'})); const d=within(view.getByRole('dialog',{name:'Worlds workspace'})); fireEvent.click(d.getByRole('button',{name:'People'})); fireEvent.click(d.getByRole('button',{name:'Apple'})); fireEvent.click(d.getByRole('button',{name:'Add organisation'})); fireEvent.change(d.getByLabelText('Organisation'),{target:{value:'organisation:police'}});
 fireEvent.click(d.getByRole('button',{name:'Create rank'})); fireEvent.change(d.getByLabelText('Long term'),{target:{value:'Detective Constable'}}); fireEvent.change(d.getByLabelText('Abbreviated term'),{target:{value:'DC'}}); fireEvent.click(d.getByRole('button',{name:'Save definition'}));
 fireEvent.click(d.getByRole('button',{name:'Create position'})); fireEvent.change(d.getByLabelText('Long term'),{target:{value:'Senior Investigating Officer'}}); fireEvent.change(d.getByLabelText('Abbreviated term'),{target:{value:'SIO'}}); fireEvent.click(d.getByRole('button',{name:'Save definition'})); fireEvent.click(d.getByRole('button',{name:'Save relationship'}));
 expect(latest.worlds![0].entities.find(e=>e.abbreviation==='DC')).toMatchObject({kind:'rank'}); expect(latest.worlds![0].relationships[0]).toMatchObject({to:{kind:'organisation',id:'police'},rankId:latest.worlds![0].entities.find(e=>e.abbreviation==='DC')!.id,positionId:latest.worlds![0].entities.find(e=>e.abbreviation==='SIO')!.id});
});
it('bulk creates internal structures without cluttering Organisations and keeps custom links canonical', () => {
 const story=migrateStory(null,'p'),w=createWorld('Universe'); w.entities=[{id:'scu',kind:'organisation',name:'SCU',description:''}]; story.characters=[{id:'apple',name:'Apple',description:''}]; story.worlds=[w]; let latest=story;
 const view=render(<Harness initial={story} onChange={s=>latest=s}/>); fireEvent.click(within(view.container.querySelector('.writing-header')!).getByRole('button',{name:'Worlds'})); const d=within(view.getByRole('dialog',{name:'Worlds workspace'})); fireEvent.click(d.getByRole('button',{name:'Organisations'})); fireEvent.click(d.getByRole('button',{name:'SCU'}));
 fireEvent.click(d.getByRole('button',{name:'+ Add multiple'})); fireEvent.change(d.getByLabelText('Structure type'),{target:{value:'Team'}}); fireEvent.change(d.getByLabelText('Creation method'),{target:{value:'sequence'}}); fireEvent.change(d.getByLabelText('Prefix'),{target:{value:'Team'}}); fireEvent.change(d.getByLabelText('Abbreviation pattern (optional)'),{target:{value:'T{n}'}}); fireEvent.change(d.getByLabelText('Initial hierarchy level (optional)'),{target:{value:'2'}}); fireEvent.click(d.getByRole('button',{name:'Create 5 teams'}));
 expect(latest.worlds![0].entities.filter(e=>e.kind==='structure')).toHaveLength(5); expect(latest.worlds![0].entities.find(e=>e.name==='Team 4')).toMatchObject({kind:'structure',organisationId:'scu',abbreviation:'T4',hierarchyLevel:2});
 fireEvent.click(d.getByRole('checkbox',{name:'Select Team 1'})); fireEvent.click(d.getByRole('checkbox',{name:'Select Team 2'})); fireEvent.click(d.getByRole('button',{name:'Move selected down one level'})); expect(latest.worlds![0].entities.find(e=>e.name==='Team 1')!.hierarchyLevel).toBe(3); expect(latest.worlds![0].entities.find(e=>e.name==='Team 3')!.hierarchyLevel).toBe(2);
 fireEvent.click(d.getByRole('button',{name:'← All Organisations'})); expect(view.container.querySelector('.world-results')).not.toHaveTextContent('Team 1');
 fireEvent.click(d.getByRole('button',{name:'SCU'})); fireEvent.click(d.getByRole('button',{name:'Add custom field'})); fireEvent.change(d.getByLabelText('Custom field name'),{target:{value:'Lead'}}); fireEvent.click(d.getByRole('button',{name:'Save custom field'})); fireEvent.change(d.getByLabelText('Lead linked entity'),{target:{value:'character:apple'}}); fireEvent.change(d.getByLabelText('Lead value'),{target:{value:'Case lead'}}); expect(latest.worlds![0].entities.find(e=>e.id==='scu')!.fieldLinks!.Lead).toEqual({kind:'character',id:'apple'});
});
it('edits World membership and linked field values from the canonical character profile context', () => {
 const story=migrateStory(null,'p'),w=createWorld('Universe'); w.entities=[{id:'police',kind:'organisation',name:'Police Scotland',description:'',fields:{Lead:'Detective'},fieldLinks:{Lead:{kind:'character',id:'apple'}}},{id:'dc',kind:'organisation',organisationRole:'rank',name:'Detective Constable',abbreviation:'DC',description:''}]; story.characters=[{id:'apple',name:'Apple',description:''}]; story.worlds=[w]; let latest=story;
 function ProfileHarness(){ const [s,set]=useState(story); return <WorldEntityContext story={s} documents={[]} entity={{kind:'character',id:'apple'}} navigate={()=>{}} change={next=>{latest=next;set(next);}}/>; }
 const view=render(<ProfileHarness/>); fireEvent.click(view.getByRole('button',{name:'Add organisation'})); fireEvent.change(view.getByLabelText('Organisation'),{target:{value:'organisation:police'}}); fireEvent.change(view.getByLabelText('Rank / grade'),{target:{value:'dc'}}); fireEvent.click(view.getByRole('button',{name:'Save relationship'})); expect(latest.worlds![0].relationships[0].rankId).toBe('dc'); expect(latest.worlds![0].characterIds).toEqual(['apple']);
 fireEvent.change(view.getByLabelText('Universe · Police Scotland · Lead'),{target:{value:'Senior detective'}}); expect(latest.worlds![0].entities[0].fields!.Lead).toBe('Senior detective');
});
function Harness({ initial, onChange = () => { } }: {
    initial: StoryRecord;
    onChange?(story: StoryRecord): void;
}) { const [story, setStory] = useState(initial); return <><header className="writing-header"/><footer className="screenplay-statistics"/><WorldWorkspace story={story} documents={[]} change={next => { setStory(next); onChange(next); }} navigateScene={() => { }} status="Saved" error="" retry={() => { }}/></>; }
it('links existing canonical people, edits references and generates live organisation nodes', () => { const story = migrateStory(null, 'p'); story.characters = [{ id: 'apple', name: 'Apple', description: '' }]; const w = createWorld('Universe'); w.entities = [{ id: 'team', kind: 'organisation', name: 'Team 4', description: '' }]; story.worlds = [w]; let latest = story; const view = render(<Harness initial={story} onChange={s => latest = s}/>); fireEvent.click(within(view.container.querySelector('.writing-header')!).getByRole('button', { name: 'Worlds' })); const dialog = within(view.getByRole('dialog', { name: 'Worlds workspace' })); fireEvent.click(dialog.getByRole('button', { name: 'People' })); fireEvent.change(dialog.getByLabelText('Link existing character'), { target: { value: 'apple' } }); expect(latest.characters).toHaveLength(1); expect(latest.worlds![0].characterIds).toEqual(['apple']); fireEvent.click(dialog.getByRole('button', { name: 'Apple' })); fireEvent.click(dialog.getByRole('button', { name: 'Add organisation' })); fireEvent.change(dialog.getByLabelText('Organisation'), { target: { value: 'organisation:team' } }); fireEvent.click(dialog.getByRole('button', { name: 'Save relationship' })); expect(latest.worlds![0].relationships[0]).toMatchObject({ from: { id: 'apple', kind: 'character' }, to: { id: 'team', kind: 'organisation' }, type: 'member of' }); fireEvent.click(dialog.getByRole('button', { name: 'Diagrams' })); expect(view.container.querySelector('.world-diagram-canvas')).toHaveTextContent('Apple'); fireEvent.click(dialog.getByRole('button', { name: 'Collapse Team 4' })); expect(view.container.querySelector('.world-diagram-canvas')).not.toHaveTextContent('Apple'); fireEvent.click(dialog.getByRole('button', { name: 'Expand Team 4' })); expect(view.container.querySelector('.world-diagram-canvas')).toHaveTextContent('Apple'); });
it('keeps selected-text occurrences separate from Scene links and resolves the existing entity', () => { const story = migrateStory(null, 'p'); const w = createWorld('Universe'); w.entities = [{ id: 'bell', kind: 'object', name: 'Attention Bell', description: '' }]; story.worlds = [w]; let latest = story; const view = render(<Harness initial={story} onChange={s => latest = s}/>); act(() => window.dispatchEvent(new CustomEvent('world-link-context', { detail: { screenplayId: 'd', sceneId: 's', type: 'action', selectedText: 'bell', from: { elementId: 'a', offset: 0 }, to: { elementId: 'a', offset: 4 }, x: 0, y: 0 } }))); const dialog = within(view.getByRole('dialog', { name: 'Add or link story entity' })); fireEvent.click(dialog.getByRole('button', { name: 'Objects' })); fireEvent.click(dialog.getByRole('button', { name: 'Attention Bell' })); expect(latest.worldOccurrences).toHaveLength(1); expect(latest.worldOccurrences![0]).toMatchObject({ entity: { kind: 'object', id: 'bell' }, scope: 'text', from: { elementId: 'a', offset: 0 }, selectedText: 'bell' }); expect(latest.worlds![0].entities).toHaveLength(1); });
it('publishes only Exact wording for an explicitly invoked dialogue insertion', () => { const story = migrateStory(null, 'p'); const w = createWorld('Universe'); w.entities = [{ id: 'spell', kind: 'lore', name: 'Binding Spell', description: '', fields: { Type: 'Spell', 'Exact wording': 'Veyra', 'Literal translation': 'Bind this soul', 'Meaning / usage': 'Restrains' } }]; story.worlds = [w]; const listener = vi.fn(); window.addEventListener('world-insert-text', listener); const view = render(<Harness initial={story}/>); fireEvent.click(within(view.container.querySelector('.writing-header')!).getByRole('button', { name: 'Worlds' })); const d = within(view.getByRole('dialog', { name: 'Worlds workspace' })); fireEvent.click(d.getByRole('button', { name: 'Language & Lore' })); fireEvent.click(d.getByRole('button', { name: 'Binding Spell' })); expect(listener).not.toHaveBeenCalled(); fireEvent.click(d.getByRole('button', { name: 'Add to dialogue' })); expect(listener.mock.calls[0][0].detail).toEqual({ text: 'Veyra', type: 'dialogue' }); window.removeEventListener('world-insert-text', listener); });
