import { useState } from 'react';
import type { StoryRecord } from '../shared/story';
import type { ScreenplayRecord } from '../shared/models';
import { ORGANISATION_CATEGORIES, STRUCTURE_TYPES, type WorldEntity, type WorldRecord, type WorldRef, type WorldPoint } from '../shared/worlds';
import { isOrganisation, organisationCategory, setStructureParent } from '../domain/world-structure';
import { relationshipAt, validateWorld } from '../domain/worlds';

export function WorldOrganisationFields({entity,world,story,documents,at,patch,patchWorld,convert,open}:{
 entity:WorldEntity;world:WorldRecord;story:StoryRecord;documents:ScreenplayRecord[];at?:WorldPoint;
 patch(p:Partial<WorldEntity>):void;patchWorld(w:WorldRecord):void;convert(ownerId:string):void;open(r:WorldRef):void;
}) {
 const [parent,setParent]=useState(''),[owner,setOwner]=useState(''),[error,setError]=useState(''),[child,setChild]=useState(''),[short,setShort]=useState(''),[person,setPerson]=useState('');
 if(!['organisation','structure','rank','position'].includes(entity.kind))return null;
 const organisations=world.entities.filter(e=>isOrganisation(e)&&!e.archived&&e.id!==entity.id);
 const category=organisationCategory(world,entity.id,story,documents,at);
 const save=(next:WorldRecord)=>{try{validateWorld(next,story,documents);patchWorld(next);setError('');}catch(e){setError(String(e));}};
 const active=world.relationships.filter(r=>['part of','reports to'].includes(r.type)&&r.from.id===entity.id&&relationshipAt(r,at,story,documents)==='active');
 return <>{error&&<p role="alert">{error}</p>}{entity.kind==='organisation'&&<><label>Organisation category<input list="organisation-categories" placeholder="Use the parent Organisation’s category" value={entity.category??''} onChange={e=>patch({category:e.target.value||undefined})}/></label><datalist id="organisation-categories">{ORGANISATION_CATEGORIES.map(c=><option key={c}>{c}</option>)}</datalist><small>{entity.category?'Category: '+entity.category:category?'Using parent category: '+category:'No shared parent category. Choose a category here if needed.'} · Leave empty to use the parent Organisation’s category.</small>
 <section><h4>Parent Organisations</h4>{active.filter(r=>r.to.kind==='organisation').map(r=><p key={r.id}><button onClick={()=>open(r.to)}>{world.entities.find(e=>e.id===r.to.id)?.name??'Organisation unavailable'}</button><button onClick={()=>save({...world,relationships:world.relationships.map(e=>e.id!==r.id?e:at?{...e,untilPoint:at}:{...e,archived:true})})}>Remove parent placement</button></p>)}<label>Parent Organisation<select aria-label="Parent Organisation" value={parent} onChange={e=>setParent(e.target.value)}><option value="">Choose parent…</option>{organisations.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><button disabled={!parent||active.some(r=>r.to.id===parent)} onClick={()=>{save({...world,relationships:[...world.relationships,{id:crypto.randomUUID(),type:'part of',from:{kind:'organisation',id:entity.id},to:{kind:'organisation',id:parent},fromPoint:at}]});setParent('');}}>Add parent Organisation</button></section>
 <details><summary>Create a separate child Organisation</summary><small>Use Structure for teams, departments and sections.</small><label>Child Organisation name<input value={child} onChange={e=>setChild(e.target.value)}/></label><label>Child Organisation abbreviation<input value={short} onChange={e=>setShort(e.target.value)}/></label><button disabled={!child.trim()} onClick={()=>{const id=crypto.randomUUID();save({...world,entities:[...world.entities,{id,kind:'organisation',name:child.trim(),abbreviation:short.trim()||undefined,description:''}],relationships:[...world.relationships,{id:crypto.randomUUID(),type:'part of',from:{kind:'organisation',id},to:{kind:'organisation',id:entity.id},fromPoint:at}]});setChild('');setShort('');}}>Create child Organisation</button></details>
 <details><summary>Convert an existing entry to internal structure</summary><small>Keeps this entry’s links and history. Choose the Organisation it belongs to.</small><label>Owning Organisation<select aria-label="Owning Organisation" value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Choose owner…</option>{organisations.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><button disabled={!owner} onClick={()=>convert(owner)}>Convert to internal structure</button></details></>}
 {entity.kind==='structure'&&<><p>Organisation: <button onClick={()=>entity.organisationId&&open({kind:'organisation',id:entity.organisationId})}>{world.entities.find(e=>e.id===entity.organisationId)?.name??'Organisation unavailable'}</button></p><label>Internal structure type<input list="unit-types" value={entity.structureType??'Unit'} onChange={e=>patch({structureType:e.target.value})}/></label><datalist id="unit-types">{STRUCTURE_TYPES.map(t=><option key={t}>{t}</option>)}</datalist><label>Reports to / Parent unit<select aria-label="Reports to / Parent unit" value={active.find(r=>r.to.kind==='structure')?.to.id??''} onChange={e=>{try{save(setStructureParent(world,[entity.id],e.target.value||undefined,at));}catch(err){setError(String(err));}}}><option value="">Directly inside Organisation</option>{world.entities.filter(e=>e.kind==='structure'&&e.organisationId===entity.organisationId&&e.id!==entity.id&&!e.archived).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><details><summary>Hierarchy and display order</summary><label>Hierarchy level<input type="number" min="1" value={entity.hierarchyLevel??''} onChange={e=>{if(e.target.value===''||Number(e.target.value)>0&&Number.isInteger(Number(e.target.value)))patch({hierarchyLevel:e.target.value===''?undefined:Number(e.target.value)});}}/></label><label>Display order<input type="number" value={entity.displayOrder??''} onChange={e=>{if(e.target.value===''||Number.isInteger(Number(e.target.value)))patch({displayOrder:e.target.value===''?undefined:Number(e.target.value)});}}/></label><small>Level 1 is the most senior. Higher levels sit below it. Display order only changes the order within a level.</small></details><small>Category: {category??'uncategorised'} (from Organisation)</small><fieldset><legend>Assign a Character to this unit</legend><label>Assign Character<select aria-label="Assign Character" value={person} onChange={e=>setPerson(e.target.value)}><option value="">Choose existing Character…</option>{story.characters.filter(c=>!c.archived).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button disabled={!person||world.relationships.some(r=>r.type==='member of'&&r.from.id===person&&r.unitId===entity.id&&relationshipAt(r,at,story,documents)==='active')} onClick={()=>{if(!entity.organisationId)return;save({...world,characterIds:[...new Set([...world.characterIds,person])],relationships:[...world.relationships,{id:crypto.randomUUID(),type:'member of',from:{kind:'character',id:person},to:{kind:'organisation',id:entity.organisationId},unitId:entity.id,fromPoint:at}]});setPerson('');}}>Assign to this unit</button><small>Edit the membership below to choose a rank, position, manager or transfer date.</small></fieldset></>}
 {(entity.kind==='rank'||entity.kind==='position')&&<label>Definition Organisation<select aria-label="Definition Organisation" value={entity.organisationId??''} onChange={e=>patch({organisationId:e.target.value||undefined})}><option value="">Available to all Organisations</option>{organisations.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>}
 </>;
}
