// @vitest-environment jsdom
import { useState } from 'react';
import { cleanup, fireEvent, render, within } from '@testing-library/react';
import '@testing-library/jest-dom/vitest';
import { afterEach, expect, it } from 'vitest';
import { WorldConfiguredFields, CanonicalWorldFields } from './WorldConfiguredFields';
import { RelationshipEditor } from './WorldRelationshipEditor';
import { createWorld } from '../domain/worlds';
import { migrateStory } from '../domain/story';
import type { WorldEntity, WorldRecord, WorldRef } from '../shared/worlds';
afterEach(cleanup);

it('uses simple Notes and Rules forms and keeps Lore fields relevant to the selected type',()=>{
 const story=migrateStory(null,'p');
 function Harness(){const [e,set]=useState<WorldEntity>({id:'n',kind:'note',name:'Note',description:''});return <><button onClick={()=>set({...e,kind:'rule'})}>Rule</button><button onClick={()=>set({...e,kind:'lore',fields:{Type:'Phrase'}})}>Lore</button><WorldConfiguredFields entity={e} patch={p=>set({...e,...p})} story={story} documents={[]}/></>;}
 const v=render(<Harness/>);expect(v.queryByLabelText('Aliases / nicknames')).toBeNull();expect(v.getByLabelText('Importance')).toHaveDisplayValue('Not set');fireEvent.change(v.getByLabelText('Importance'),{target:{value:'High'}});fireEvent.change(v.getByLabelText('Importance'),{target:{value:'Low'}});expect(v.getByLabelText('Importance')).toHaveValue('Low');
 fireEvent.click(v.getByText('Rule',{exact:true}));expect(v.getByLabelText('Rule type').tagName).toBe('SELECT');expect(v.queryByLabelText('Aliases / nicknames')).toBeNull();
 fireEvent.click(v.getByText('Lore',{exact:true}));expect(v.getByLabelText('Original text')).toBeInTheDocument();expect(v.queryByLabelText('Requirements')).toBeNull();fireEvent.change(v.getByLabelText('Type',{exact:true}),{target:{value:'Spell'}});expect(v.getByLabelText('Incantation')).toBeInTheDocument();expect(v.getByLabelText('Effect')).toBeInTheDocument();expect(v.queryByLabelText('Original text')).toBeNull();
});
it('reuses custom vehicle types and updates the canonical Place with cycle-safe parent choices',()=>{
 const story=migrateStory(null,'p'),w=createWorld('World');w.entities=[{id:'v',kind:'vehicle',name:'Sub',description:'',fields:{Type:'Submarine'}}];story.worlds=[w];story.locations=[{id:'building',name:'Station',description:''},{id:'room',name:'Interview room',description:'',parentId:'building'}];let latest=story.locations[0];
 const v=render(<><WorldConfiguredFields entity={{id:'new',kind:'vehicle',name:'New',description:''}} patch={()=>{}} story={story} documents={[]}/><CanonicalWorldFields kind="location" entity={story.locations[0]} story={story} patch={p=>latest={...latest,...p}}/></>);
 expect(within(v.getByLabelText('Vehicle type')).getByRole('option',{name:'Submarine'})).toBeInTheDocument();expect(within(v.getByLabelText('Parent location')).queryByRole('option',{name:'Interview room'})).toBeNull();fireEvent.change(v.getByLabelText('Place type'),{target:{value:'Hospital'}});expect(latest.profile?.locationType).toBe('Hospital');
});
it('stores ownership once, edits it from the character side and remembers contextual custom relationships',()=>{
 const story=migrateStory(null,'p'),initial=createWorld('World');story.characters=[{id:'apple',name:'Apple',description:''}];initial.entities=[{id:'car',kind:'vehicle',name:'Mondeo',description:''}];let latest=initial;
 function Harness(){const [world,set]=useState(initial),[selected,select]=useState<WorldRef>({kind:'vehicle',id:'car'});return <><button onClick={()=>select({kind:'character',id:'apple'})}>Character side</button><button onClick={()=>select({kind:'vehicle',id:'car'})}>Vehicle side</button><RelationshipEditor world={world} story={story} documents={[]} selected={selected} patch={w=>{latest=w;set(w);}} open={()=>{}} remove={id=>{const w={...world,relationships:world.relationships.filter(r=>r.id!==id)};latest=w;set(w);}}/></>;}
 const v=render(<Harness/>);fireEvent.click(v.getByRole('button',{name:'Add character'}));expect(v.queryByLabelText('Organisation')).toBeNull();fireEvent.change(v.getByLabelText('Character',{exact:true}),{target:{value:'apple'}});fireEvent.click(v.getByRole('button',{name:'Save relationship'}));expect(latest.relationships).toHaveLength(1);expect(latest.characterIds).toContain('apple');expect(latest.relationships[0].type).toBe('owned by');
 fireEvent.click(v.getByRole('button',{name:'Character side'}));expect(v.getByRole('button',{name:/Owns · Mondeo/})).toBeInTheDocument();fireEvent.click(v.getByRole('button',{name:'Edit / end period'}));fireEvent.change(v.getByLabelText('Notes'),{target:{value:'Inherited'}});fireEvent.click(v.getByRole('button',{name:'Save relationship'}));expect(latest.relationships).toHaveLength(1);expect(latest.relationships[0].notes).toBe('Inherited');fireEvent.click(v.getByRole('button',{name:'Delete relationship…'}));expect(latest.relationships).toHaveLength(0);
 fireEvent.click(v.getByRole('button',{name:'Vehicle side'}));fireEvent.click(v.getByRole('button',{name:'Add character'}));fireEvent.change(v.getByLabelText('Character',{exact:true}),{target:{value:'apple'}});fireEvent.change(v.getByLabelText('Relationship',{exact:true}),{target:{value:'__custom'}});fireEvent.change(v.getByLabelText('Relationship name'),{target:{value:'Restorer'}});fireEvent.click(v.getByRole('button',{name:'Save relationship'}));fireEvent.click(v.getByRole('button',{name:'Add character'}));expect(within(v.getByLabelText('Relationship',{exact:true})).getByRole('option',{name:'Restorer'})).toBeInTheDocument();
});
it('reveals organisation descendants progressively and filters unit-specific positions and their ranks',()=>{
 const story=migrateStory(null,'p'),initial=createWorld('World');story.characters=[{id:'apple',name:'Apple',description:''}];
 initial.entities=[{id:'police',kind:'organisation',name:'Police Scotland',description:''},{id:'scu',kind:'organisation',name:'Crime Unit',description:''},{id:'team',kind:'structure',organisationId:'scu',name:'Team 5',description:''},{id:'dc',kind:'rank',organisationId:'scu',name:'DC',description:'',rankLevel:2},{id:'ds',kind:'rank',organisationId:'scu',name:'DS',description:'',rankLevel:1},{id:'det',kind:'position',organisationId:'scu',name:'Detective',description:'',unitIds:['team'],allowedRankIds:['dc']}];initial.relationships=[{id:'hierarchy',type:'part of',from:{kind:'organisation',id:'scu'},to:{kind:'organisation',id:'police'}}];
 const v=render(<RelationshipEditor world={initial} story={story} documents={[]} selected={{kind:'character',id:'apple'}} patch={()=>{}} open={()=>{}}/>);fireEvent.click(v.getByRole('button',{name:'Add organisation'}));expect(v.queryByLabelText('Rank / grade')).toBeNull();expect(within(v.getByLabelText('Organisation',{exact:true})).queryByRole('option',{name:'Crime Unit'})).toBeNull();fireEvent.change(v.getByLabelText('Organisation',{exact:true}),{target:{value:'organisation:police'}});fireEvent.change(v.getByLabelText('Organisation within Police Scotland'),{target:{value:'scu'}});expect(within(v.getByLabelText('Position',{exact:true})).queryByRole('option',{name:'Detective'})).toBeNull();fireEvent.change(v.getByLabelText('Internal unit'),{target:{value:'team'}});fireEvent.change(v.getByLabelText('Position',{exact:true}),{target:{value:'det'}});expect(within(v.getByLabelText('Rank / grade')).getByRole('option',{name:'DC'})).toBeInTheDocument();expect(within(v.getByLabelText('Rank / grade')).queryByRole('option',{name:'DS'})).toBeNull();
});
it('preserves earlier ownership when adding the next dated period',()=>{
 const story=migrateStory(null,'p'),world=createWorld('World');story.characters=[{id:'apple',name:'Apple',description:''},{id:'peter',name:'Peter',description:''}];world.entities=[{id:'car',kind:'vehicle',name:'Mondeo',description:''}];world.relationships=[{id:'owner',type:'owned by',from:{kind:'vehicle',id:'car'},to:{kind:'character',id:'apple'},fromPoint:{chronology:{day:1}}}];let latest:WorldRecord=world;
 const v=render(<RelationshipEditor world={world} story={story} documents={[]} selected={{kind:'vehicle',id:'car'}} patch={w=>latest=w} open={()=>{}}/>);fireEvent.click(v.getByRole('button',{name:'Add next period'}));fireEvent.change(v.getByLabelText('Character',{exact:true}),{target:{value:'peter'}});fireEvent.change(v.getByLabelText('Starts type'),{target:{value:'chronology'}});fireEvent.change(v.getByLabelText('Story day'),{target:{value:'4'}});fireEvent.click(v.getByRole('button',{name:'Save relationship'}));expect(latest.relationships).toHaveLength(2);expect(latest.relationships[0]).toMatchObject({id:'owner',to:{id:'apple'},untilPoint:{chronology:{day:4}}});expect(latest.relationships[1]).toMatchObject({to:{id:'peter'},fromPoint:{chronology:{day:4}}});
});
