import { useState } from 'react';
import type { StoryEntity, StoryRecord } from '../shared/story';
import type { EntityProfile } from '../shared/profiles';
import type { ScreenplayRecord } from '../shared/models';
import type { WorldEntity, WorldPoint } from '../shared/worlds';
import { WORLD_FORM_SCHEMAS, type WorldFormField } from '../shared/world-forms';
import { PointFields } from './WorldRelationshipEditor';
import { membershipPeriod } from '../domain/world-memberships';
import { compareWorldPoints } from '../domain/worlds';
import { WorldSearchSelect } from './WorldLinkControls';
import { saveWorldState, worldStateAt } from '../domain/world-history';

export function WorldOptionField({label,value,options,onChange,custom=true}:{label:string;value:string;options:string[];onChange(v:string):void;custom?:boolean}) {
 const [adding,setAdding]=useState(false),[draft,setDraft]=useState(''),[search,setSearch]=useState('');
 const all=[...new Set([...options,...value?[value]:[]])];
 return <div className="world-option-field">{all.length>12&&<label>Search {label.toLowerCase()}<input value={search} onChange={e=>setSearch(e.target.value)}/></label>}<label>{label}<select aria-label={label} value={adding?'__new':value} onChange={e=>{if(e.target.value==='__new'){setAdding(true);setDraft('');}else{setAdding(false);onChange(e.target.value);}}}><option value="">Not set</option>{all.filter(v=>v===value||v.toLowerCase().includes(search.toLowerCase())).map(v=><option key={v} value={v}>{v}</option>)}{custom&&<option value="__new">Add another option…</option>}</select></label>{adding&&<div className="world-inline-form"><label>New {label.toLowerCase()}<input value={draft} onChange={e=>setDraft(e.target.value)}/></label><button disabled={!draft.trim()} onClick={()=>{onChange(draft.trim());setAdding(false);}}>Add option</button><button onClick={()=>setAdding(false)}>Cancel option</button></div>}</div>;
}
export function ConfiguredFields({kind,get,set,extraOptions,exclude=[]}:{kind:string;get(key:string):string;set(key:string,v:string):void;extraOptions?(key:string):string[];exclude?:string[]}) {
 const schema=WORLD_FORM_SCHEMAS[kind as keyof typeof WORLD_FORM_SCHEMAS];
 const fields=(schema?.fields??[]).flatMap(f=>!f.when||f.when.includes(get('Type'))?[f]:get(f.key)&&!schema?.fields.some(other=>other.key===f.key&&other!==f&&other.when?.includes(get('Type')))?[{...f,section:'Other recorded details'}]:[]).filter(f=>!exclude.includes(f.key)&&(f.section!=='Previous details'||get(f.key)));
 const render=(f:WorldFormField)=><div key={f.key}>{f.type==='select'?<WorldOptionField label={f.label??(f.key==='Type'?kind==='lore'?'Type':kind==='note'?'Note type':kind==='vehicle'?'Vehicle type':kind==='rule'?'Rule type':'Object type':f.key)} value={get(f.key)} options={[...f.options??[],...extraOptions?.(f.key)??[]]} onChange={v=>set(f.key,v)} custom={f.key!=='Importance'}/>:<label>{f.label??f.key}{f.type==='text'||f.type==='number'?<input aria-label={f.label??f.key} type={f.type==='number'?'number':'text'} value={get(f.key)} onChange={e=>set(f.key,e.target.value)}/>:<textarea aria-label={f.label??f.key} rows={2} value={get(f.key)} onChange={e=>set(f.key,e.target.value)}/>}</label>}</div>;
 return <div className="world-configured-fields">{fields.filter(f=>!f.section).map(render)}{[...new Set(fields.map(f=>f.section).filter((s):s is string=>Boolean(s)))].map(section=><details key={section}><summary>{section}</summary><div className="world-field-section">{fields.filter(f=>f.section===section).map(render)}</div></details>)}</div>;
}
export function WorldConfiguredFields({entity,patch,story,documents,at}:{entity:WorldEntity;patch(p:Partial<WorldEntity>):void;story:StoryRecord;documents:ScreenplayRecord[];at?:WorldPoint}) {
 return <><ConfiguredFields kind={entity.kind} get={key=>entity.fields?.[key]??''} set={(key,v)=>patch({fields:{...entity.fields,[key]:v}})} extraOptions={key=>(story.worlds??[]).flatMap(w=>[...w.fieldOptions?.[entity.kind+':'+key]??[],...w.entities.filter(e=>e.kind===entity.kind).map(e=>e.fields?.[key]??'')]).filter(Boolean)}/>{WORLD_FORM_SCHEMAS[entity.kind]?.aliases&&<details><summary>Other names</summary><label>Aliases / nicknames<input value={entity.aliases?.join(', ')??''} onChange={e=>patch({aliases:e.target.value.split(',').map(s=>s.trim()).filter(Boolean)})}/></label></details>}{['object','vehicle','rule'].includes(entity.kind)&&<WorldStateHistory entity={entity} patch={patch} story={story} documents={documents} at={at}/>}</>;
}
const PROFILE_FIELDS:Record<string,keyof EntityProfile>={'Occupation':'occupation','Traits':'personality','Appearance':'visualNotes','Status':'customFields','Notes':'notes','Place type':'locationType','Access restrictions':'restrictions'};
export function CanonicalWorldFields({kind,entity,story,patch}:{kind:'character'|'location';entity:StoryEntity;story:StoryRecord;patch(p:Partial<StoryEntity>):void}) {
 const get=(key:string)=>key==='Skills'?entity.profile?.skills?.map(s=>s.name).join(', ')??'':key==='Appearance'&&kind==='character'?entity.profile?.appearances?.find(a=>a.isDefault)?.description??'':PROFILE_FIELDS[key]&&PROFILE_FIELDS[key]!=='customFields'?String(entity.profile?.[PROFILE_FIELDS[key]]??''):entity.profile?.customFields?.find(f=>f.name===key)?.value??'';
 const set=(key:string,v:string)=>{const profile={...entity.profile};if(key==='Skills'){profile.skills=v.split(',').map(s=>s.trim()).filter(Boolean).map(name=>entity.profile?.skills?.find(s=>s.name===name)??{id:crypto.randomUUID(),name});}else if(key==='Appearance'&&kind==='character'){const old=profile.appearances?.find(a=>a.isDefault);profile.appearances=[...profile.appearances?.filter(a=>a.id!==old?.id)??[],{...old,id:old?.id??crypto.randomUUID(),name:old?.name??'Default appearance',isDefault:true,description:v}];}else if(PROFILE_FIELDS[key]&&PROFILE_FIELDS[key]!=='customFields'){Object.assign(profile,{[PROFILE_FIELDS[key]]:v});}else{const old=profile.customFields?.find(f=>f.name===key);profile.customFields=[...profile.customFields?.filter(f=>f.name!==key)??[],{id:old?.id??crypto.randomUUID(),name:key,value:v}];}patch({profile});};
 const parents=story.locations.filter(l=>l.id!==entity.id&&!l.archived&&!isDescendant(l.id,entity.id));
 function isDescendant(id:string,root:string){const seen=new Set<string>();let item=story.locations.find(l=>l.id===id);while(item?.parentId&&!seen.has(item.id)){seen.add(item.id);if(item.parentId===root)return true;item=story.locations.find(l=>l.id===item!.parentId);}return false;}
 return <><ConfiguredFields kind={kind} get={get} set={set} extraOptions={key=>[...(story.worlds??[]).flatMap(w=>w.fieldOptions?.[kind+':'+key]??[]),...(kind==='location'?story.locations:story.characters).map(e=>key==='Place type'?e.profile?.locationType??'':'')].filter(Boolean)}/>{kind==='character'&&<details><summary>Aliases / nicknames</summary><label>Aliases / nicknames<input value={entity.profile?.aliases?.join(', ')??''} onChange={e=>patch({profile:{...entity.profile,aliases:e.target.value.split(',').map(s=>s.trim()).filter(Boolean)}})}/></label></details>}{kind==='location'&&<WorldSearchSelect label="Parent location" options={parents.map(l=>({value:l.id,label:l.name}))} value={entity.parentId??''} empty="No parent location" onChange={id=>patch({parentId:id||undefined})}/>}<details><summary>Custom fields</summary>{entity.profile?.customFields?.filter(f=>!WORLD_FORM_SCHEMAS[kind]?.fields.some(field=>field.key===f.name)).map(f=><label key={f.id}>{f.name}<input value={f.value} onChange={e=>patch({profile:{...entity.profile,customFields:entity.profile?.customFields?.map(item=>item.id===f.id?{...item,value:e.target.value}:item)}})}/></label>)}<CanonicalCustomField kind={kind} entity={entity} patch={patch}/></details></>;
}
function CanonicalCustomField({entity,patch,kind}:{kind:'character'|'location';entity:StoryEntity;patch(p:Partial<StoryEntity>):void}){const [adding,setAdding]=useState(false),[name,setName]=useState('');return <><button onClick={()=>{setAdding(true);setName('');}}>Add custom field</button>{adding&&<fieldset><legend>New custom field</legend><label>Custom field name<input value={name} onChange={e=>setName(e.target.value)}/></label><button disabled={!name.trim()||WORLD_FORM_SCHEMAS[kind]?.fields.some(f=>f.key.toLowerCase()===name.trim().toLowerCase())||entity.profile?.customFields?.some(f=>f.name.toLowerCase()===name.trim().toLowerCase())} onClick={()=>{patch({profile:{...entity.profile,customFields:[...entity.profile?.customFields??[],{id:crypto.randomUUID(),name:name.trim(),value:''}]}});setAdding(false);}}>Save custom field</button><button onClick={()=>setAdding(false)}>Cancel custom field</button></fieldset>}</>;}
function WorldStateHistory({entity,patch,story,documents,at}:{entity:WorldEntity;patch(p:Partial<WorldEntity>):void;story:StoryRecord;documents:ScreenplayRecord[];at?:WorldPoint}) {
 const [draft,setDraft]=useState<NonNullable<WorldEntity['history']>[number]>(),[error,setError]=useState('');
 const [viewAt,setViewAt]=useState<WorldPoint|undefined>(at);
 const current=worldStateAt(entity,story,documents,viewAt);
 return <details className="world-state-history"><summary>{entity.kind==='rule'?'Rule history':'Appearance & condition history'}</summary><PointFields label="View changes" mode="view" value={viewAt} onChange={setViewAt} story={story} documents={documents}/><p><strong>{viewAt?'At this story point':entity.kind==='rule'?'Current Rule':'Current appearance & condition'}</strong><br/>{[current.Rule??(entity.kind==='rule'?entity.description:undefined),current.Appearance,current.Condition].filter(Boolean).join(' · ')||'No details recorded.'}</p>{entity.history?.map(h=><article key={h.id}><p>{h.fields.Rule} {h.fields.Appearance} {h.fields.Condition}</p><small>{membershipPeriod({...h,type:'state',from:{kind:entity.kind,id:entity.id},to:{kind:entity.kind,id:entity.id}},story,documents)}</small><button onClick={()=>{setDraft(h);setError('');}}>Edit history entry</button><button onClick={()=>{if(window.confirm('Delete this history entry? This cannot be undone.')){window.dispatchEvent(new Event('world-permanent-delete'));patch({history:entity.history?.filter(item=>item.id!==h.id)});}}}>Delete history entry</button></article>)}<button onClick={()=>{setDraft({id:crypto.randomUUID(),fields:{Appearance:worldStateAt(entity,story,documents,viewAt).Appearance??'',Condition:worldStateAt(entity,story,documents,viewAt).Condition??''},fromPoint:viewAt});setError('');}}>Add change</button>{draft&&<fieldset><legend>Record a change</legend>{(entity.kind==='rule'?['Rule']:['Appearance','Condition']).map(key=><label key={key}>{key}<textarea aria-label={key} value={draft.fields[key]??''} onChange={e=>setDraft({...draft,fields:{...draft.fields,[key]:e.target.value}})}/></label>)}<PointFields label="Starts" value={draft.fromPoint} onChange={fromPoint=>setDraft({...draft,fromPoint})} documents={documents} story={story}/><PointFields label="Ends before" value={draft.untilPoint} onChange={untilPoint=>setDraft({...draft,untilPoint})} documents={documents} story={story}/>{error&&<p role="alert">{error}</p>}<button disabled={!Object.values(draft.fields).some(v=>v.trim())} onClick={()=>{if(draft.fromPoint&&draft.untilPoint){const order=compareWorldPoints(draft.fromPoint,draft.untilPoint,story,documents);if(order!==undefined&&order>=0){setError('The end must be after the start.');return;}}try{patch({history:saveWorldState(entity,draft,story,documents)});setDraft(undefined);}catch(reason){setError(String(reason));}}}>Save change</button><button onClick={()=>setDraft(undefined)}>Cancel change</button></fieldset>}</details>;
}
