import { _electron as electron } from 'playwright'; import { mkdtemp } from 'node:fs/promises'; import { join } from 'node:path'; import { tmpdir } from 'node:os';
const root = await mkdtemp(join(tmpdir(), 'screenplay-002d-')); const profile = join(root, 'profile'); const storage = join(root, 'storage'); let app = await electron.launch({ args: ['.', `--user-data-dir=${profile}`] }); let page = await app.firstWindow();
async function createProject(title, type) { await page.getByRole('button', { name: /New Project/i }).click(); await page.getByPlaceholder('Untitled story').fill(title); await page.getByRole('button', { name: new RegExp(`^${type}`) }).click(); await page.getByRole('button', { name: 'Create project' }).click(); }
async function saved() { await page.getByText(/Unsaved changes|Saving…/, { exact: true }).waitFor({ timeout: 10_000 }); await page.getByText('Saved', { exact: true }).waitFor({ timeout: 10_000 }); }
try {
  await page.getByPlaceholder('Choose a folder…').fill(storage); await page.getByRole('button', { name: 'Use this folder' }).click();
  await createProject('Film One', 'Feature'); await createProject('Small Hours', 'Short'); await page.getByRole('button', { name: /Small Hours/ }).click(); await page.getByLabel('Scene heading').fill('EXT. SMALL ROAD - NIGHT'); await page.getByLabel('Action').fill('A short story begins.'); await saved(); await page.getByRole('button', { name: 'Library', exact: true }).click();
  await createProject('Long Arc', 'Series'); await page.getByRole('button', { name: /Long Arc/ }).click(); const seriesOne = await page.getByLabel('Current Series').inputValue(); if (!seriesOne) throw new Error('Series 1 was not created automatically.'); await page.getByLabel('Episode title').fill('Pilot'); await page.getByRole('button', { name: 'Create episode' }).click(); await page.getByLabel('Scene heading').fill('INT. PILOT ROOM - DAY'); await saved();
  await page.getByRole('button', { name: 'Add Series' }).click(); await page.getByLabel('Current Series').selectOption({ index: 1 }); await page.getByLabel('Episode title').fill('Aftermath'); await page.getByRole('button', { name: 'Create episode' }).click(); await page.getByLabel('Scene heading').fill('EXT. AFTERMATH ROAD - NIGHT'); await saved();
  await page.getByLabel('Current Series').selectOption({ index: 0 }); await page.getByRole('button', { name: 'Pilot', exact: true }).click(); await page.getByLabel('Move Episode to').selectOption({ index: 1 }); await page.getByRole('button', { name: 'Pilot', exact: true }).waitFor({ timeout: 5_000 }); await page.getByRole('button', { name: 'Pilot', exact: true }).click(); if (!(await page.getByLabel('Scene heading').innerText()).includes('PILOT ROOM')) throw new Error('Episode screenplay content was lost during movement.');
  await page.getByRole('button', { name: 'Library', exact: true }).click(); await page.getByRole('button', { name: 'New Collection' }).click(); await page.getByPlaceholder('Collection name').fill('Example Universe'); await page.getByRole('button', { name: 'Create Collection' }).click(); const collection = page.locator('.collection-card'); await collection.waitFor({ timeout: 5_000 }); for (let index = 0; index < 3; index++) { await collection.locator('.collection-add select').selectOption({ index: 1 }); await collection.getByRole('button', { name: 'Add', exact: true }).click(); await page.waitForFunction((count) => document.querySelectorAll('.collection-card .project-card').length === count, index + 1); } if (await collection.locator('.project-card').count() !== 3) throw new Error('Mixed Collection membership failed.');
  await collection.getByRole('button', { name: 'Remove from collection' }).nth(0).click(); if (await page.getByRole('button', { name: /Film One/ }).count() < 1) throw new Error('Removing from a Collection deleted the project.'); page.once('dialog', (dialog) => dialog.accept()); await collection.getByRole('button', { name: 'Delete collection' }).click(); await collection.waitFor({ state: 'detached' }); if (await page.getByRole('button', { name: /Small Hours/ }).count() < 1 || await page.getByRole('button', { name: /Long Arc/ }).count() < 1) throw new Error('Deleting a Collection deleted projects.');
  if (!page.isClosed()) await page.close({ runBeforeUnload: false }); await app.close(); app = await electron.launch({ args: ['.', `--user-data-dir=${profile}`] }); page = await app.firstWindow(); await page.locator('.project-card').filter({ hasText: 'Small Hours' }).first().click(); if (!(await page.getByLabel('Scene heading').innerText()).includes('SMALL ROAD')) throw new Error('Short content did not persist after restart.');
  console.log(JSON.stringify({ checks: ['Feature creation','Short editor/persistence','Series 1 automatic creation','multiple Series','Episodes per Series','Episode move preserving screenplay','mixed Project Collection','safe removal','safe Collection deletion','application restart'] }, null, 2));
} finally { if (!page.isClosed()) await page.close({ runBeforeUnload: false }); await app.close(); }
