import { _electron as electron } from 'playwright';
import { mkdtemp, mkdir } from 'node:fs/promises'; import { join } from 'node:path'; import { tmpdir } from 'node:os';
const root = await mkdtemp(join(tmpdir(), 'screenplay-002c-e2e-')); const profile = join(root, 'profile'); const storage = join(root, 'Writer Storage'); const artifacts = join(process.cwd(), '.artifacts'); await mkdir(artifacts, { recursive: true }); const executablePath = process.env.MIMICWRITER_EXECUTABLE;
async function launch() { const app = await electron.launch(executablePath ? { executablePath, args: [`--user-data-dir=${profile}`] } : { args: ['.', `--user-data-dir=${profile}`] }); return { app, page: await app.firstWindow() }; }
async function close(app, page) { if (!page.isClosed()) await page.close({ runBeforeUnload: false }); await app.close(); }
async function saved(page) { await page.getByText(/Unsaved changes|Saving…/, { exact: true }).waitFor({ timeout: 10_000 }); await page.getByText('Saved', { exact: true }).waitFor({ timeout: 10_000 }); }
let { app, page } = await launch();
try {
  await page.getByPlaceholder('Choose a folder…').fill(storage); await page.getByRole('button', { name: 'Use this folder' }).click(); await page.getByRole('button', { name: /New Project/i }).click(); await page.getByPlaceholder('Untitled story').fill('Workflow Draft'); await page.getByRole('button', { name: /^Feature/ }).click(); await page.getByRole('button', { name: 'Create project' }).click(); await page.getByRole('button', { name: /Workflow Draft/ }).click();
  await page.getByLabel('Scene heading').fill('INT. FIRST ROOM - DAY'); await page.getByLabel('Action').fill('Alpha waits with a mispelled note.');
  await page.getByRole('button', { name: 'Add scene' }).first().click(); await page.getByLabel('Scene heading').nth(1).fill('INT. SECOND ROOM - NIGHT'); await page.getByLabel('Action').nth(1).fill('Alpha enters.');
  await page.getByRole('button', { name: 'Add scene' }).first().click(); await page.getByLabel('Scene heading').nth(2).fill('EXT. THIRD ROAD - DAWN'); await page.getByLabel('Action').nth(2).fill('Alpha leaves.'); await saved(page);
  const ids = await page.locator('[data-scene-id]').evaluateAll((nodes) => nodes.map((node) => node.getAttribute('data-scene-id')));
  await page.getByRole('button', { name: 'Scene', exact: true }).click(); if (await page.locator('[data-scene-id]').count() !== 1) throw new Error('Scene View did not isolate the active scene.'); await page.getByLabel('Action').fill('Scene View edit.'); await page.getByRole('button', { name: 'Screenplay', exact: true }).click(); if (!(await page.getByLabel('Action').last().innerText()).includes('Scene View edit.')) throw new Error('Views did not share screenplay data.');
  const sidebar = page.locator('.scene-navigator>button'); await sidebar.nth(2).dragTo(sidebar.nth(0)); await saved(page); const moved = await page.locator('[data-scene-id]').evaluateAll((nodes) => nodes.map((node) => node.getAttribute('data-scene-id'))); if (moved[0] !== ids[2]) throw new Error('Drag reorder failed or changed identity.');
  await page.locator('.screenplay-heading').click(); await page.keyboard.press('Control+z'); await saved(page); const undone = await page.locator('[data-scene-id]').evaluateAll((nodes) => nodes.map((node) => node.getAttribute('data-scene-id'))); if (undone.join() !== ids.join()) throw new Error('Undo reorder failed.'); await page.keyboard.press('Control+y'); await saved(page);
  await page.locator('[data-scene-id]').nth(1).getByTitle('Delete scene').click(); await page.getByRole('button', { name: 'Delete scene permanently' }).click(); await saved(page); if (await page.locator('[data-scene-id]').count() !== 2) throw new Error('Scene deletion failed.'); await page.locator('.screenplay-heading').click(); await page.keyboard.press('Control+z'); await saved(page); if (await page.locator('[data-scene-id]').count() !== 3) throw new Error('Undo did not restore the deleted scene.');
  await page.keyboard.press('Control+f'); await page.getByLabel('Find text').fill('Alpha'); if (!(await page.locator('.find-panel').innerText()).includes('2')) throw new Error('Find did not search the screenplay.'); await page.getByRole('button', { name: 'Replace', exact: true }).click(); await page.getByLabel('Replace with').fill('Beta'); await page.getByRole('button', { name: 'Replace All' }).click(); await saved(page); if (await page.getByText('2 replacements').count() !== 1) throw new Error('Replace All did not report its scope.'); await page.locator('.screenplay-heading').click(); await page.keyboard.press('Control+z'); await saved(page);
  await sidebar.nth(0).click({ button: 'right' }); await page.getByRole('button', { name: 'Copy Scene' }).click(); await sidebar.nth(0).click({ button: 'right' }); await page.getByRole('button', { name: 'Paste Scene After' }).click(); await saved(page); const duplicated = await page.locator('[data-scene-id]').evaluateAll((nodes) => nodes.map((node) => node.getAttribute('data-scene-id'))); if (new Set(duplicated).size !== 4) throw new Error('Structured scene paste duplicated stable IDs.'); await page.locator('.screenplay-heading').click(); await page.keyboard.press('Control+z'); await saved(page);
  if ((await page.getByText(/words/).count()) === 0 || (await page.getByText(/scenes/).count()) === 0) throw new Error('Statistics are unavailable.'); if ((await page.getByLabel('Action').first().getAttribute('spellcheck')) !== 'true') throw new Error('Local spellcheck was not enabled.');
  await page.locator('.scene-navigator>button').nth(1).click(); await page.getByRole('button', { name: 'Scene', exact: true }).click(); await saved(page).catch(() => undefined); await page.screenshot({ path: join(artifacts, 'build002c-workflow.png'), fullPage: true }); await close(app, page);
  ({ app, page } = await launch()); await page.getByRole('button', { name: /Workflow Draft/ }).click(); await page.getByRole('button', { name: 'Scene', exact: true }).waitFor(); if (await page.locator('[data-scene-id]').count() !== 1) throw new Error('View/scene state was not restored after restart.');
  await page.getByRole('button', { name: 'Library', exact: true }).click(); await page.getByRole('button', { name: /New Project/i }).click(); await page.getByPlaceholder('Untitled story').fill('Episode Workflow'); await page.getByRole('button', { name: /^Series/ }).click(); await page.getByRole('button', { name: 'Create project' }).click(); await page.getByRole('button', { name: /Episode Workflow/ }).click(); await page.getByLabel('Episode title').fill('Pilot'); await page.getByRole('button', { name: 'Create episode' }).click(); await page.getByLabel('Scene heading').fill('INT. PILOT ROOM - DAY'); await page.getByRole('button', { name: 'Add scene' }).first().click(); await page.getByLabel('Scene heading').nth(1).fill('EXT. PILOT ROAD - NIGHT'); await page.getByRole('button', { name: 'Scene', exact: true }).click(); if (await page.locator('[data-scene-id]').count() !== 1) throw new Error('Series episode Scene View failed.'); await saved(page);
  console.log(JSON.stringify({ checks: ['shared screenplay/scene views','drag reorder','stable IDs/display numbers','undo/redo reorder','delete/undo restore identity','find','replace all/undo','structured scene clipboard','plain spellcheck foundation','statistics','view/scene restart restoration','Series episode workflow'], screenshot: '.artifacts/build002c-workflow.png' }, null, 2));
} finally { await close(app, page); }
